-- s01 · Conflict and TBD register. docs/SOURCE_CONFLICTS.md
--
-- Nothing here is silently resolved. Each row records the question, the disputing sources
-- and the ship-with default. The five frozen decisions are marked 'decided' while their
-- underlying factory question stays 'open'.

insert into public.conflict_register
  (conflict_id, kind, severity, question, sources, ship_with_default, status, blocks_phase)
values
-- PART 1 — SOP-internal conflicts
('C-01','conflict','blocks_build','Stage-0 target moisture: 68–69 % or 75–78 %?',
 'S1a 0A/0B/0C say 68–69 %; S4a Table 2 says 75–78 %; real actuals 68.2–72.9 % satisfy neither',
 'Two separate specs: S1a for the operator target, S4a for the lab verdict. Both shown side by side, no automatic deviation.','open','Step 7'),
('C-02','conflict','blocks_behaviour','Phase-1 cadence: 3-day or 8-day?',
 'S2b implies T0/T1/T2 same day; S6a traces an 8-day window; S1a requires a 24 h T0→T2 gap',
 'S6a authoritative. S2b treated as a superseded template.','open','Step 4'),
('C-03','conflict','blocks_behaviour','Stage-0 length: 6 days or 7?',
 'S2b gives 6; S6a column trace plus S3b give 7',
 'Batch start = bagasse pre-wet day = D−7.','open','Step 4'),
('C-04','conflict','blocks_behaviour','Phase-2C stage table has two transcription errors',
 'S1a data17.xml duplicates a row and mislabels Cooling-2',
 'Conditioning-2 48–45 °C 75–90 h; Cooling-2 to 24 °C in 8–20 h. Flagged in the seed.','open','Step 10'),
('C-05','conflict','blocks_behaviour','Conditioning-2 duration: spec 75–80 h, reality 89–111 h',
 'S1a P2D says 80–90 h; every recorded tunnel exceeds it',
 'Target 80–90 h, warn above 95 h, deviation above 100 h. Flagged as an assumption.','open','Step 10'),
('C-06','conflict','blocks_behaviour','Starting nitrogen: 1.75 %, 1.4–1.6 %, or 1.25–1.70 %?',
 'S1c states both 1.75 % and 1.4–1.6 %; S5a computes 1.25–1.70 %',
 'S5a historical band, informational only. The 1.75 % figure is not used.','open','Step 5'),
('C-07','conflict','blocks_behaviour','Phase-1 end pH: 7.8–8.2 or 8.2–8.5?',
 'Both appear in S1c two pages apart; S4a Table 2 shows pH falling through Phase-1',
 'Use S4a Table 2 per checkpoint.','open','Step 8'),
('C-08','conflict','cosmetic','Data-entry transposition in S3b',
 'Bagasse moisture 12.5 and wheat 56.8 are swapped relative to S4a Table 1',
 'Range-check raw assays at entry; correct the historical record on import.','open',null),
('C-09','conflict','cosmetic','Cooling-tower water EC unit inconsistency',
 'S4a Table 3 gives 4.2–6.5 where every other row is 700–900',
 'Import as-is, flag unit_uncertain, exclude from auto-verdict.','open','Step 8'),
('C-10','conflict','cosmetic','Three damaged calculations in the lab manual',
 'S4a moisture formula incomplete; ash formula garbled; Kjeldahl says 200 g where ~0.2 g is meant',
 'Method text carries the C-10 flag. A known-wrong procedure is never shown as authoritative.','open','Step 8'),
('C-11','conflict','cosmetic','Rooms Covered = 4 on a 3-batch, 3-tunnel record',
 'S3a Section 0 vs its own tables; S2a says 3 1/2; S4b shows a 3 (A) half room',
 'Rooms are a separate, fractional count. Not treated as an error.','open',null),
('C-12','conflict','blocks_behaviour','Section headers in batch records are stale',
 'S3f Section 3A header says 2 bunkers into 3 tunnels; the table lists 3 into 4',
 'Headers are boilerplate and are not used as data. Structure reads from table rows only.','open',null),
('C-13','conflict','blocks_behaviour','Legacy app mislabels two Phase-1 stages',
 'S8e STAGE_LABELS vs S1a',
 'S1a wins. Legacy labels are never domain vocabulary.','open',null),
('C-14','conflict','blocks_behaviour','Two flow-diagram revisions with different decomposition',
 'S1b vs S1a',
 'S1a authoritative. S1b retained as evidence that mustard was once part of 0A.','open',null),
('C-15','conflict','blocks_behaviour','Tunnel unload trigger EC > 2.5 vs recorded 1.69–2.16',
 'S1a P2D vs every batch record — not one tunnel reaches 2.5',
 'Recording-only. No EC gate at tunnel unload.','open','Step 8'),
('C-16','conflict','cosmetic','Tunnel unload moisture: 65–66 % vs 65–68 % vs recorded 66.5–69 %',
 'S1a P2D vs S4a Table 2 vs S3f/S3a actuals',
 'S4a 65–68 % for the verdict; S1a 65–66 % shown as the operational aim.','open','Step 8'),
('C-17','conflict','blocks_behaviour','Tunnel unload temperature: 22 °C or 24 °C?',
 'S1a P2D lists both; S1c says 24–26 ideal, above 28 not ready',
 'Cooling-2 target 24 °C, acceptable 22–26 °C, block above 28 °C.','open','Step 10'),
('C-18','conflict','cosmetic','Schedule vocabulary is not stable across months',
 'S6a older sheets carry tokens absent from the current SOP, plus numbers in activity cells',
 'Only the current 17 tokens map. Unmapped tokens go to a review queue, never guessed.','open','Step 4'),

-- PART 2 — conflicts introduced by the factory walkthrough
('C-19','conflict','blocks_build','The day-numbering base has moved',
 'W: Day 0 = weighment, tunnel load Day 15, 23 days. S6a+S1a: Day 0 = mixing, tunnel load Day 8',
 'PROCESS-2026B numbering exclusively. Old numbering survives only in archived ROUTE-2026A.','open','Step 4'),
('C-20','conflict','blocks_build','The monthly schedule may no longer map to the process',
 'S6a is a 19-day grid ending in room loading; W is 23 days ending at tunnel unload',
 'The slot supplies identity only. Per-activity dates are generated from the process. Stated on screen.','open','Step 4'),
('C-21','conflict','blocks_behaviour','Two hopper passes on Day 1, not one',
 'W gives HOP-1 with water then HOP-2 water-conditional; S1a 0A gives a single pass',
 'Two passes per the walkthrough.','open','Step 7'),
('C-22','conflict','blocks_behaviour','Stage-0 bunker structure: one reload, not two conditionings',
 'W: load, rest, unload+hopper+reload. S1a: 0B, 0C, 0D each with its own unload trigger',
 'Structure from W; SOP triggers carried as configurable gate content, defaulted OFF.','open','Step 7'),
('C-23','conflict','blocks_build','Straw soak durations: 8–10 hours vs 2–3 hours',
 'W says 8–10 h per soak plus 14–16 h rest; S1a 1C-A says 2–3 h and 1 h',
 'Walkthrough durations. SOP durations archived.','open','Step 7'),
('C-24','conflict','blocks_behaviour','Straw occupies a bunker',
 'W requires a bunker ID for straw storage; no SOP or movement log records it',
 'Modelled as a location occupancy that blocks compost exactly the same way.','open','Step 3'),
('C-25','conflict','blocks_build','One Phase-1 reload, or two?',
 'W describes one on Day 12; S1a, S7a and S3f all show two',
 'FROZEN DECISION 3: one reload. reload_2_included option exists, defaulted OFF.','decided','Step 4'),
('C-26','conflict','blocks_behaviour','Tunnel loading day',
 'W says Day 15; S6a trace says D+8',
 'C-19 restated. PROCESS-2026B numbering.','open','Step 4'),
('C-27','conflict','blocks_behaviour','Days 16–21 carry no process content in the walkthrough',
 'W names no monitoring; S1a P2C and S1c specify six named stages and seven control bands',
 'FROZEN DECISION 5: SOP content retained as configured monitoring, configuration-driven and visibly sourced.','decided','Step 10'),
('C-28','conflict','blocks_behaviour','The walkthrough carries no temperature, moisture or fill-height limits',
 'W specifies durations, evidence, machines, movements — and none of the ~110 SOP limits',
 'SOP limits mapped where unambiguous. sop_inferred and unmapped load DISABLED. Review report required.','open','Step 4'),
('C-29','conflict','blocks_build','What moisture threshold drives the conditional hopper pass?',
 'W makes the water/dry decision depend on a threshold it never states. See C-01',
 'FROZEN DECISION 1: auto-selection DISABLED. Operator chooses with both candidate bands shown and a mandatory reason.','decided','Step 7'),
('C-30','conflict','blocks_behaviour','One destination bunker per reload, or several?',
 'W shows one-to-one swaps; S7a records a line reloading into two bunkers on one day',
 'The movement ledger supports a list; the UI defaults to one.','open','Step 7'),
('C-31','conflict','cosmetic','Legacy app stage labels are now doubly wrong',
 'S8e labels were already wrong per C-13; the whole 17-stage vocabulary is now superseded',
 'Terminology locked per PROCESS_V2 §19 and enforced by lint.','open',null),

-- OPEN TBDs
('TBD-01','tbd',null,'Is the bunker-line to tunnel correspondence real, or is pooling always total?','S4b vs S3f','Pooling modelled as N:M.','open','Step 3'),
('TBD-02','tbd',null,'Are wheat/mustard wetting separate activities, a variant of 0A, or a Day-0 option?','S6a tokens vs S1a','See TBD-39.','open','Step 2'),
('TBD-08','tbd',null,'Tunnel probe data: manual entry every 4 h, or ingested from the controller?','S3f notes a communication failure, implying a feed exists','Manual entry. No controller integration.','open','Step 10'),
('TBD-09','tbd',null,'Is Compost Manager a distinct role from Supervisor?','S2b vs S3f','Two fields on the batch, one person. Six roles only.','open','Step 1'),
('TBD-10','tbd',null,'Shift boundaries.','S2b Day/Night column; S7a times span 24 h','Not modelled yet.','open','Step 7'),
('TBD-11','tbd',null,'Does a Manager role exist at this factory today?','—','Shipped as a role; can be held by Admin.','open','Step 1'),
('TBD-12','tbd',null,'Do any sensory values act as gates?','S1a P2D implies actinomycetes is one','Recording-only until confirmed.','open','Step 8'),
('TBD-13','tbd',null,'Is there an intended operating band for compost EC?','S3f reasons about it; no source gives one','verdict = no_spec.','open','Step 8'),
('TBD-14','tbd',null,'Is ammonia measured, and with what?','S1c specifies 800–1000 ppm; absent from S4b','Not seeded.','open','Step 8'),
('TBD-15','tbd',null,'New Supabase project or reuse the old one?','Legacy project carries a 4-account seed and a documented auth bug','RESOLVED: new project. Old one abandoned.','resolved','Step 1'),
('TBD-19','tbd',null,'2 straw piles or 3?','The written frame implies 3; the dictation says 2','2 straw + 1 mixed = 3 piles at the turner. Configurable.','open','Step 2'),
('TBD-20','tbd',null,'21 MT primary fibre against 66.66 MT fresh in the historical formulations',
 'Smaller batch, one of three lines, or dry weight?','FROZEN DECISION 4: 21 MT target, load count derived. Never store 10 or 11.','decided','Step 2'),
('TBD-21','tbd',null,'Rest durations are never stated — D2–D3, D10–D11, D13–D14',
 'W gives rest days but no hours; S1a 0B gives 48–60 h with a temperature trigger',
 'FROZEN DECISION 2: Day-0 configurable, mandatory, NO default. Amber marker at the point of use.','decided','Step 7'),
('TBD-22','tbd',null,'Day 4: is ~3 hours the unload, the hopper pass, or both?','W states it once for both','Day-0 value per activity.','open','Step 7'),
('TBD-23','tbd',null,'Which day do straw receipt and bale cutting happen?','W places them after the Day-4 reload without naming a day','Interim: Day 4.','open','Step 2'),
('TBD-24','tbd',null,'Rest after straw bunker storage — 2 h or 12 h?','The dictation is ambiguous','Day-0 value, required, no default.','open','Step 7'),
('TBD-25','tbd',null,'Day 7 flips and Day 8 flips — four distinct, or two restated?','2 h each vs 4 h each','Four distinct.','open','Step 2'),
('TBD-26','tbd',null,'Day 12 reload: 9 h per bunker or 9 h total?','The frame says per bunker; the Day-8 precedent says 3 h each','Day-0 value, required, no default.','open','Step 7'),
('TBD-27','tbd',null,'Does the yard have finite named bays?','—','Yard is unbounded space for now.','open','Step 3'),
('TBD-28','tbd',null,'How many bunkers does straw occupy, and for how long?','W says a bunker during soaking','1 per batch, Day-0 configurable.','open','Step 3'),
('TBD-29','tbd',null,'Is a source bunker released at the start of unload or the end of reload?','—','Released at the end of reload.','open','Step 7'),
('TBD-30','tbd',null,'Do machine operators need certification?','—','Warn, do not refuse.','open','Step 7'),
('TBD-31','tbd',null,'Is fuel recorded today, and at what granularity?','W lists it as optional','Optional per stint.','open','Step 7'),
('TBD-32','tbd',null,'Do machines have hour meters that are read?','—','Optional meter columns exist.','open','Step 7'),
('TBD-33','tbd',null,'Real fleet size — how many turners, JCBs, hoppers?','T1 parallel with T2 needs at least two turners','Seed 2 turners, 2 JCBs, 1 hopper, 1 rotavator.','open','Step 2'),
('TBD-34','tbd',null,'Evidence per weighment load?','11 loads is a lot of capture on a phone','1 photo per load, Day-0 configurable.','open','Step 7'),
('TBD-35','tbd',null,'Is video genuinely wanted on the Day-4 hopper pass?','Roughly 40x the storage of a photo','Allowed, capped 30 s / 720p.','open','Step 7'),
('TBD-36','tbd',null,'Which lab checkpoints attach to which PROCESS-2026B activities?','W names none; S4b defines 18','Map the unambiguous ones; leave the rest unmapped and visible.','open','Step 8'),
('TBD-37','tbd',null,'Is growing-room loading and harvest out of scope, or only out of demo scope?','—','Out of demo scope. Retained as outcome entities.','open','Step 12'),
('TBD-38','tbd',null,'Do durations change when a different material leads a role?','S1c implies waxy straws need longer pre-wet than bagasse','Duration defaults on the role only. Flagged in the Day-0 UI when a non-default material leads.','open','Step 5'),
('TBD-39','tbd',null,'Is SECONDARY_FIBRE the wheat/mustard wetting stream?','S6a tokens exist; the walkthrough did not cover them','Stream defined, DISABLED by default, no activities seeded.','open','Step 2'),
('TBD-40','tbd',null,'Can STRUCTURAL_STRAW ever be something other than paddy?','Every record uses paddy','Role allows any material; the demo binds paddy.','open','Step 2'),
('TBD-41','tbd',null,'How many named Day-0 templates does the factory want, and who owns them?','—','Not modelled yet.','open','Step 5')
on conflict (conflict_id) do update set
  kind = excluded.kind,
  severity = excluded.severity,
  question = excluded.question,
  sources = excluded.sources,
  ship_with_default = excluded.ship_with_default,
  status = excluded.status,
  blocks_phase = excluded.blocks_phase;
