-- s12 · PROCESS-2026C becomes the current standard.
--
-- WHY A SEED AND NOT A MIGRATION
--   Publishing and pointing the catalogue are DECISIONS, and 0044 made both of them RPCs
--   with an `assert_role(['admin','gm'])` on the front. A migration runs as the database
--   owner, which has no app role at all, so calling those RPCs from a migration would mean
--   either weakening the guard or bypassing it. Seeds run in the same connection and write
--   the same rows directly, which is what every other seed in this set already does.
--
--   The RPCs remain the only path for a person. This file is the bootstrap.
--
-- WHAT THIS DOES NOT DO
--   It does not archive PROCESS-2026B. Batches were generated from it and their baselines
--   are frozen; the definition has to stay readable for as long as one of those batches
--   exists. It stops being the DEFAULT, which is a different thing from ceasing to exist.
--
-- Idempotent. Re-running is a no-op on a healthy database.

-- ── 1 · Publish. ────────────────────────────────────────────────────────────
-- The same three checks publish_process_definition makes, stated as a guard here so a
-- half-seeded definition cannot become the factory standard.

do $$
declare
  d_id uuid;
  n    int;
begin
  select id into d_id from public.process_definition
   where code = 'PROCESS-2026C' and version = 1;

  if d_id is null then
    raise exception
      'PROCESS-2026C v1 is not present. Run migration 0043 (generated by '
      'scripts/gen-process-2026c.mjs) before this seed.';
  end if;

  select count(*) into n from public.process_activity where process_definition_id = d_id;
  if n = 0 then
    raise exception
      'PROCESS-2026C v1 has no activities. Refusing to publish an empty standard — every '
      'batch created against it would freeze an empty baseline.';
  end if;

  -- ⚠ NO HOUR FIGURE APPEARS IN THIS CHECK, DELIBERATELY.
  --
  -- 470 h is a property of PROCESS-2026C, not of MushroomOS, and a literal here would be the
  -- application asserting a number that belongs to one SOP. The invariant that generalises to
  -- every future standard is that the SOP AGREES WITH ITSELF: what its activities compute and
  -- what the factory wrote down beside them describe the same process. PROCESS-2027A will
  -- compute whatever its own stages compute, and this same check will hold it to the same rule.
  if exists (select 1 from public.v_process_envelope
              where process_definition_id = d_id and envelope_disagrees) then
    raise exception
      'PROCESS-2026C v1 disagrees with itself: its activities compute %h against a stated '
      'envelope of %h. Refusing to make it the factory standard.',
      (select calculated_standard_hr from public.v_process_envelope where process_definition_id = d_id),
      (select stated_envelope_hr     from public.v_process_envelope where process_definition_id = d_id);
  end if;

  if (select standard_hr from public.v_process_envelope where process_definition_id = d_id) is null then
    raise exception
      'PROCESS-2026C v1 computes no standard duration — none of its activities carry a '
      'standard hour, so no batch could be planned against it.';
  end if;

  update public.process_definition
     set status = 'published', published_at = coalesce(published_at, now())
   where id = d_id and status <> 'published';

  -- ── 2 · Point the catalogue at it. ───────────────────────────────────────
  insert into public.process_catalogue (id, current_definition_id, set_at, reason)
  values (1, d_id, now(),
          'PROCESS-2026C, the 470-hour standard, confirmed by the process owner 30 Aug 2026. '
          'Supersedes PROCESS-2026B (552 h) as the default for new batches. 2026B stays '
          'published and readable for the batches already planned against it.')
  on conflict (id) do update set
    current_definition_id = excluded.current_definition_id,
    set_at                = excluded.set_at,
    reason                = excluded.reason;
end $$;
