-- ─────────────────────────────────────────────────────────────────────────────
-- 0043 · PROCESS-2026C — the 470-hour standard.
--
-- GENERATED by scripts/gen-process-2026c.mjs from docs/01-process/schedule.json.
-- DO NOT EDIT BY HAND. Change schedule.json and regenerate, or the two disagree and
-- nobody finds out until a variance is wrong.
--
--   activities   69
--   envelope     H470   (stream 1 discharge — the standard end)
--   anchor       H174   (Turner)
--   discharged   H474   (stream 3 — all three streams out)
--   rel_day      0 … 19
--
-- PROCESS-2026B IS NOT TOUCHED. Batches were generated from it and their baselines are
-- frozen; a new standard is a new version beside the old one, never an edit to it.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1 · One named instance, stated by the definition. ───────────────────────
-- evaluate_cardinality had six kinds and none of them said "exactly one, and it is
-- called this". A Turner pass belongs to pile 4 and to no other; PER_SCOPE_INSTANCE
-- would put all six piles on one hour, and SINGLETON would label it "Whole batch".
-- The label is data in the rule, so no count and no pile name enters any code path.

-- The six original kinds move aside under their own name rather than being retyped here.
-- Retyping them is how a rule that has been correct since 0005 acquires a difference.
do $$
begin
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = 'evaluate_cardinality_v1') then
    alter function public.evaluate_cardinality(jsonb, jsonb) rename to evaluate_cardinality_v1;
  end if;
end $$;

create or replace function public.evaluate_cardinality(
  p_rule jsonb, p_config jsonb
) returns table (instance_no int, scope_label text, planned_qty_mt numeric)
language plpgsql stable as $fn$
begin
  if p_rule->>'kind' = 'FIXED_LABEL' then
    if coalesce(p_rule->>'label', '') = '' then
      raise exception 'A FIXED_LABEL cardinality rule must carry a label.';
    end if;
    return query select 1, p_rule->>'label', null::numeric;
    return;
  end if;
  return query select * from public.evaluate_cardinality_v1(p_rule, p_config);
end;
$fn$;

comment on function public.evaluate_cardinality(jsonb, jsonb) is
  'Seven rule kinds. FIXED_LABEL (0043) is one instance carrying a label the definition
  states — a Turner pile-pass, a bunker line, a tunnel stream. Everything else delegates
  to evaluate_cardinality_v1, which is 0005 unchanged.';


-- ── 2 · A hold is not a task. ──────────────────────────────────────────────
-- Six of the fifteen rail activities and both bunker conditionings are HOLD: material
-- resting, nobody working. 128 of the first 174 hours are holds. Without this column
-- the operator's queue offers a 63-hour bunker conditioning as something to press
-- START on, and the two kinds become indistinguishable the moment they are planned.

alter table public.process_activity add column if not exists is_hold boolean not null default false;
alter table public.batch_activity   add column if not exists is_hold boolean not null default false;

comment on column public.process_activity.is_hold is
  'true = material is resting and no one is working. STANDARD.md KIND = HOLD. 0043.';


-- ── 3 · The definition. ────────────────────────────────────────────────────

insert into public.process_definition
  (code, name, version, status, source_ref, anchor_day_label, total_days)
values
  ('PROCESS-2026C', 'The 470-hour standard', 1, 'draft', 'docs/01-process/schedule.json · PROCESS-2026C v1, confirmed 30 Aug 2026',
   'H0 = fibre wetting, hopper pass 1', 19)
on conflict (code, version) do update set
  name = excluded.name, source_ref = excluded.source_ref, total_days = excluded.total_days,
  -- Back to draft for the length of this file. 0044 freezes a PUBLISHED definition's
  -- activities at the table, so regenerating from schedule.json would otherwise be refused
  -- on every run after the first. s12 publishes it again once the rows are in. The window
  -- is one migration long and it is inside the same run.
  status = 'draft';

-- The envelope is a factory statement, not (total_days + 1) × 24. 0041 / F7.
-- 470 is not a multiple of 24 and baseline_hours physically cannot hold it.
update public.process_definition
   set envelope_hours       = 470,
       envelope_hour_source = 'factory_stated',
       envelope_confidence  = 'FACTORY_CONFIRMED'
 where code = 'PROCESS-2026C' and version = 1;

-- Days exist so the calendar screens have a title per rel_day. The day grid is not the
-- envelope — 0041 §2 — it is a label.
with pd as (select id from public.process_definition where code = 'PROCESS-2026C' and version = 1)
insert into public.process_day (process_definition_id, rel_day, title, source_ref)
select pd.id, d, 'Day ' || d, 'docs/01-process/schedule.json · PROCESS-2026C v1, confirmed 30 Aug 2026' from pd, generate_series(0, 19) d
on conflict (process_definition_id, rel_day) do update set title = excluded.title;


-- ── 4 · 69 activities. ─────────────────────────────────────────

with pd as (select id from public.process_definition where code = 'PROCESS-2026C' and version = 1)
insert into public.process_activity (
  process_definition_id, code, label_template, material_role, stream, rel_day, seq, scope,
  cardinality_rule, duration_target_min_hr, duration_target_max_hr,
  standard_start_hour, standard_end_hour, standard_hour_source,
  is_hold, responsible_role, golden_rule, source_ref, timing_confidence, lab_parameters)
select pd.id, a.code, a.label, a.material_role::material_role_code, a.stream::stream_code,
       a.rel_day, a.seq, a.scope::activity_scope, a.cardinality::jsonb,
       a.dmin, a.dmax, a.hstart, a.hend, 'factory_stated',
       a.is_hold, a.role::app_role, a.golden, 'docs/01-process/schedule.json · PROCESS-2026C v1, confirmed 30 Aug 2026',
       a.confidence::process_confidence, a.lab_params
from pd, (values
  ('FIB-WET-1', '{role_lead} wetting — hopper pass 1 (full water, target 69–71% moisture)', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 0, 10, 'MASTER', '{"kind":"SINGLETON"}', 3, 3, 0, 3, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-REST-1', 'Material rest', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 0, 20, 'MASTER', '{"kind":"SINGLETON"}', 8, 8, 3, 11, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-HOP-2', 'Hopper pass 2 (dry, or water to reach target moisture)', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 0, 30, 'MASTER', '{"kind":"SINGLETON"}', 3, 3, 11, 14, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-HEAP', 'Heap formation (height ≤1.5 m) + rest', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 0, 40, 'MASTER', '{"kind":"SINGLETON"}', 8, 12, 14, 26, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-BUNK-LOAD', 'Flipping + bunker filling (ht 2.6–2.7 m), no water', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 1, 50, 'BUNKER_LINE', '{"kind":"SINGLETON"}', 2, 2, 26, 28, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-COND-1', 'Bunker conditioning, 45–55 °C. Unload trigger ≥58 °C or ≥60 h', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 1, 60, 'BUNKER_LINE', '{"kind":"SINGLETON"}', 48, 60, 28, 88, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-RELOAD-1', 'Loader unload, flipping, reload to new bunker (no water)', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 3, 70, 'MASTER', '{"kind":"SINGLETON"}', 5, 5, 88, 93, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-COND-2', 'Conditioning. Unload trigger ≥58 °C or ≥40 h', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 3, 80, 'BUNKER_LINE', '{"kind":"SINGLETON"}', 40, 40, 93, 133, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('FIB-MOIST-DEC', 'Unload. If moisture ≥68% proceed; if <67% controlled mist via hopper', 'PRIMARY_FIBRE', 'PRIMARY_FIBRE', 5, 90, 'MASTER', '{"kind":"SINGLETON"}', 3, 3, 133, 136, false, 'operator', 'A reading between 67 % and 68 % is recorded, flagged and referred. It does not auto-proceed and it does not auto-mist.', 'FACTORY_CONFIRMED', null::text[]),
  ('MIX-CM-ADD', 'Add {role_lead} mix to conditioned fibre + loader mix + flip 1 + flip 2', 'NITROGEN_SOURCE', 'YARD', 5, 100, 'MASTER', '{"kind":"SINGLETON"}', 8, 8, 136, 144, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('MIX-HOP-WATER', 'Hopper pass, full water (target 73% moisture, temp <45–50 °C)', null, 'YARD', 6, 110, 'MASTER', '{"kind":"SINGLETON"}', 4, 4, 144, 148, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('MIX-REST', 'Rest', null, 'YARD', 6, 120, 'MASTER', '{"kind":"SINGLETON"}', 8, 12, 148, 160, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('YARD-PILES', 'Preparation of 2 equal piles on platform', null, 'YARD', 6, 130, 'MASTER', '{"kind":"SINGLETON"}', 4, 4, 160, 164, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('YARD-ADD', 'Add fibre + nitrogen mix gradually onto the 2 straw piles', null, 'YARD', 6, 140, 'MASTER', '{"kind":"SINGLETON"}', 2, 2, 164, 166, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('YARD-FLIP', 'Flipping 1 + flipping 2, back to back', null, 'YARD', 6, 150, 'MASTER', '{"kind":"SINGLETON"}', 8, 8, 166, 174, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('STR-WEIGH', '{role_lead} bale weighment + cutting + thread removal', 'STRUCTURAL_STRAW', 'STRUCTURAL_STRAW', 3, 160, 'MASTER', '{"kind":"SINGLETON"}', 12, 12, 74, 86, false, 'operator', 'Latest start H74. Eighty-six hours of work against eighty-six hours of room — one hour late here is one hour late on the batch, and nothing on the main rail will show why.', 'FACTORY_CONFIRMED', null::text[]),
  ('STR-SOAK-1', 'Soaking 1 — push in, tilt 1, tilt 2, push out (8–10 h) + rest in bunker (10–12 h)', 'STRUCTURAL_STRAW', 'STRUCTURAL_STRAW', 3, 170, 'MASTER', '{"kind":"SINGLETON"}', 22, 22, 86, 108, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('STR-SOAK-2', 'Soaking 2 — push in, tilt 1, tilt 2, push out (8–10 h) + rest in bunker (18 h)', 'STRUCTURAL_STRAW', 'STRUCTURAL_STRAW', 4, 180, 'MASTER', '{"kind":"SINGLETON"}', 28, 28, 108, 136, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('STR-SOAK-3', 'Soaking 3 — push in, tilt 1, tilt 2, push out (8–10 h) + rest in bunker (12–14 h)', 'STRUCTURAL_STRAW', 'STRUCTURAL_STRAW', 5, 190, 'MASTER', '{"kind":"SINGLETON"}', 24, 24, 136, 160, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('CM-WEIGH', '{role_lead} + mineral weighment', 'NITROGEN_SOURCE', 'NITROGEN_MINERAL', 5, 200, 'MASTER', '{"kind":"SINGLETON"}', 2, 2, 130, 132, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('CM-DRYMIX', 'Dry mix + rotavator to break lumps (no water)', 'NITROGEN_SOURCE', 'NITROGEN_MINERAL', 5, 210, 'MASTER', '{"kind":"SINGLETON"}', 4, 4, 132, 136, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P1-T0', 'Turner T0 — pile 1', null, 'YARD', 7, 220, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 1"}', 1.5, 1.5, 174, 175.5, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P1-T1', 'Turner T1 — pile 1', null, 'YARD', 7, 230, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 1"}', 1.5, 1.5, 177, 178.5, false, 'operator', 'The gap after T0 is normal — 1.5 to 4.5 h. The continuity belongs to the machines, not to the pile.', 'FACTORY_CONFIRMED', array['moisture']::text[]),
  ('TRN-P1-T2', 'Turner T2 — pile 1', null, 'YARD', 7, 240, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 1"}', 1.5, 1.5, 186.5, 188, false, 'operator', 'Eligible eight hours after THIS pile’s own T1 actual end. Not T0 start + 24 h.', 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P1-T3', 'Turner T3 — pile 1', null, 'YARD', 8, 250, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 1"}', 1.5, 1.5, 192.5, 194, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P2-T0', 'Turner T0 — pile 2', null, 'YARD', 7, 260, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 2"}', 1.5, 1.5, 175.5, 177, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P2-T1', 'Turner T1 — pile 2', null, 'YARD', 7, 270, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 2"}', 1.5, 1.5, 180, 181.5, false, 'operator', 'The gap after T0 is normal — 1.5 to 4.5 h. The continuity belongs to the machines, not to the pile.', 'FACTORY_CONFIRMED', array['moisture']::text[]),
  ('TRN-P2-T2', 'Turner T2 — pile 2', null, 'YARD', 7, 280, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 2"}', 1.5, 1.5, 189.5, 191, false, 'operator', 'Eligible eight hours after THIS pile’s own T1 actual end. Not T0 start + 24 h.', 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P2-T3', 'Turner T3 — pile 2', null, 'YARD', 8, 290, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 2"}', 1.5, 1.5, 194, 195.5, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P3-T0', 'Turner T0 — pile 3', null, 'YARD', 7, 300, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 3"}', 1.5, 1.5, 174, 175.5, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P3-T1', 'Turner T1 — pile 3', null, 'YARD', 7, 310, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 3"}', 1.5, 1.5, 178.5, 180, false, 'operator', 'The gap after T0 is normal — 1.5 to 4.5 h. The continuity belongs to the machines, not to the pile.', 'FACTORY_CONFIRMED', array['moisture']::text[]),
  ('TRN-P3-T2', 'Turner T2 — pile 3', null, 'YARD', 7, 320, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 3"}', 1.5, 1.5, 188, 189.5, false, 'operator', 'Eligible eight hours after THIS pile’s own T1 actual end. Not T0 start + 24 h.', 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P3-T3', 'Turner T3 — pile 3', null, 'YARD', 8, 330, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 3"}', 1.5, 1.5, 192.5, 194, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P4-T0', 'Turner T0 — pile 4', null, 'YARD', 7, 340, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 4"}', 1.5, 1.5, 175.5, 177, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P4-T1', 'Turner T1 — pile 4', null, 'YARD', 7, 350, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 4"}', 1.5, 1.5, 181.5, 183, false, 'operator', 'The gap after T0 is normal — 1.5 to 4.5 h. The continuity belongs to the machines, not to the pile.', 'FACTORY_CONFIRMED', array['moisture']::text[]),
  ('TRN-P4-T2', 'Turner T2 — pile 4', null, 'YARD', 7, 360, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 4"}', 1.5, 1.5, 191, 192.5, false, 'operator', 'Eligible eight hours after THIS pile’s own T1 actual end. Not T0 start + 24 h.', 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P4-T3', 'Turner T3 — pile 4', null, 'YARD', 8, 370, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 4"}', 1.5, 1.5, 194, 195.5, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P5-T0', 'Turner T0 — pile 5', null, 'YARD', 7, 380, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 5"}', 1.5, 1.5, 177, 178.5, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P5-T1', 'Turner T1 — pile 5', null, 'YARD', 7, 390, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 5"}', 1.5, 1.5, 180, 181.5, false, 'operator', 'The gap after T0 is normal — 1.5 to 4.5 h. The continuity belongs to the machines, not to the pile.', 'FACTORY_CONFIRMED', array['moisture']::text[]),
  ('TRN-P5-T2', 'Turner T2 — pile 5', null, 'YARD', 7, 400, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 5"}', 1.5, 1.5, 189.5, 191, false, 'operator', 'Eligible eight hours after THIS pile’s own T1 actual end. Not T0 start + 24 h.', 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P5-T3', 'Turner T3 — pile 5', null, 'YARD', 8, 410, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 5"}', 1.5, 1.5, 195.5, 197, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P6-T0', 'Turner T0 — pile 6', null, 'YARD', 7, 420, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 6"}', 1.5, 1.5, 178.5, 180, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P6-T1', 'Turner T1 — pile 6', null, 'YARD', 7, 430, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 6"}', 1.5, 1.5, 181.5, 183, false, 'operator', 'The gap after T0 is normal — 1.5 to 4.5 h. The continuity belongs to the machines, not to the pile.', 'FACTORY_CONFIRMED', array['moisture']::text[]),
  ('TRN-P6-T2', 'Turner T2 — pile 6', null, 'YARD', 7, 440, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 6"}', 1.5, 1.5, 191, 192.5, false, 'operator', 'Eligible eight hours after THIS pile’s own T1 actual end. Not T0 start + 24 h.', 'FACTORY_CONFIRMED', null::text[]),
  ('TRN-P6-T3', 'Turner T3 — pile 6', null, 'YARD', 8, 450, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 6"}', 1.5, 1.5, 195.5, 197, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B1-FILL', 'Bunker fill — bunker 1', null, 'BUNKER', 8, 460, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 2, 2, 194, 196, false, 'operator', 'Rolling. The bunker opens when the first of piles 1 + 2 leaves T3; the second joins as it finishes. There is no six-pile barrier.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B1-HOLD-1', 'Conditioning hold 1 — bunker 1', null, 'BUNKER', 8, 470, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 63, 63, 196, 259, true, 'operator', 'Approximately 15 h to reach 70 °C, then 48 h at temperature. Reload trigger 73–74 °C with the hold satisfied, whichever comes first. Both recorded.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B1-RELOAD', 'Unload, flip and reload — bunker 1', null, 'BUNKER', 10, 480, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 2, 2, 259, 261, false, 'operator', 'Shrunken height is recorded FIRST — it determines the reload height. Then moisture. If water is added, pH, EC and moisture are taken again and the original reading is never overwritten.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B1-HOLD-2', 'Conditioning hold 2 — bunker 1', null, 'BUNKER', 10, 490, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 63, 63, 261, 324, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B1-TUN-LOAD', 'Tunnel loading — bunker 1', null, 'BUNKER', 13, 500, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 2, 2, 324, 326, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B2-FILL', 'Bunker fill — bunker 2', null, 'BUNKER', 8, 510, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 2, 2, 196, 198, false, 'operator', 'Rolling. The bunker opens when the first of piles 3 + 4 leaves T3; the second joins as it finishes. There is no six-pile barrier.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B2-HOLD-1', 'Conditioning hold 1 — bunker 2', null, 'BUNKER', 8, 520, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 63, 63, 198, 261, true, 'operator', 'Approximately 15 h to reach 70 °C, then 48 h at temperature. Reload trigger 73–74 °C with the hold satisfied, whichever comes first. Both recorded.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B2-RELOAD', 'Unload, flip and reload — bunker 2', null, 'BUNKER', 10, 530, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 2, 2, 261, 263, false, 'operator', 'Shrunken height is recorded FIRST — it determines the reload height. Then moisture. If water is added, pH, EC and moisture are taken again and the original reading is never overwritten.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B2-HOLD-2', 'Conditioning hold 2 — bunker 2', null, 'BUNKER', 10, 540, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 63, 63, 263, 326, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B2-TUN-LOAD', 'Tunnel loading — bunker 2', null, 'BUNKER', 13, 550, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 2, 2, 326, 328, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B3-FILL', 'Bunker fill — bunker 3', null, 'BUNKER', 8, 560, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 2, 2, 198, 200, false, 'operator', 'Rolling. The bunker opens when the first of piles 5 + 6 leaves T3; the second joins as it finishes. There is no six-pile barrier.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B3-HOLD-1', 'Conditioning hold 1 — bunker 3', null, 'BUNKER', 8, 570, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 63, 63, 200, 263, true, 'operator', 'Approximately 15 h to reach 70 °C, then 48 h at temperature. Reload trigger 73–74 °C with the hold satisfied, whichever comes first. Both recorded.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B3-RELOAD', 'Unload, flip and reload — bunker 3', null, 'BUNKER', 10, 580, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 2, 2, 263, 265, false, 'operator', 'Shrunken height is recorded FIRST — it determines the reload height. Then moisture. If water is added, pH, EC and moisture are taken again and the original reading is never overwritten.', 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B3-HOLD-2', 'Conditioning hold 2 — bunker 3', null, 'BUNKER', 11, 590, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 65, 65, 265, 330, true, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('BNK-B3-TUN-LOAD', 'Tunnel loading — bunker 3', null, 'BUNKER', 13, 600, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 2, 2, 330, 332, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TN-LEVEL', 'Levelling & conditioning 1', null, 'TUNNEL', 13, 610, 'TUNNEL', '{"kind":"SINGLETON"}', 18, 20, 326, 345, true, 'operator', null, 'FACTORY_RANGE', null::text[]),
  ('TN-HEAT', 'Heating up', null, 'TUNNEL', 14, 620, 'TUNNEL', '{"kind":"SINGLETON"}', 8, 12, 345, 355, true, 'operator', null, 'FACTORY_RANGE', null::text[]),
  ('TN-PAST', 'Pasteurisation', null, 'TUNNEL', 14, 630, 'TUNNEL', '{"kind":"SINGLETON"}', 9, 10, 355, 364.5, true, 'operator', null, 'FACTORY_RANGE', null::text[]),
  ('TN-COOL-1', 'Cooling down 1', null, 'TUNNEL', 15, 640, 'TUNNEL', '{"kind":"SINGLETON"}', 12, 14, 364.5, 377.5, true, 'operator', null, 'FACTORY_RANGE', null::text[]),
  ('TN-COND-2', 'Conditioning 2', null, 'TUNNEL', 15, 650, 'TUNNEL', '{"kind":"SINGLETON"}', 80, 85, 377.5, 459, true, 'operator', null, 'FACTORY_RANGE', null::text[]),
  ('TN-COOL-2', 'Cooling down 2', null, 'TUNNEL', 19, 660, 'TUNNEL', '{"kind":"SINGLETON"}', 8, 14, 459, 470, true, 'operator', null, 'FACTORY_RANGE', null::text[]),
  ('TUN-DISCHARGE-1', 'Tunnel discharge to grow-room — stream 1', null, 'TUNNEL', 19, 670, 'TUNNEL', '{"kind":"FIXED_LABEL","label":"Stream 1"}', null, null, 470, null, false, 'operator', 'H470 is the standard end, and it is measured on stream 1.', 'FACTORY_CONFIRMED', null::text[]),
  ('TUN-DISCHARGE-2', 'Tunnel discharge to grow-room — stream 2', null, 'TUNNEL', 19, 680, 'TUNNEL', '{"kind":"FIXED_LABEL","label":"Stream 2"}', null, null, 472, null, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[]),
  ('TUN-DISCHARGE-3', 'Tunnel discharge to grow-room — stream 3', null, 'TUNNEL', 19, 690, 'TUNNEL', '{"kind":"FIXED_LABEL","label":"Stream 3"}', null, null, 474, null, false, 'operator', null, 'FACTORY_CONFIRMED', null::text[])
) as a(code, label, material_role, stream, rel_day, seq, scope, cardinality, dmin, dmax,
       hstart, hend, is_hold, role, golden, confidence, lab_params)
on conflict (process_definition_id, code) do update set
  label_template = excluded.label_template,
  material_role  = excluded.material_role,
  stream         = excluded.stream,
  rel_day        = excluded.rel_day,
  seq            = excluded.seq,
  scope          = excluded.scope,
  cardinality_rule = excluded.cardinality_rule,
  duration_target_min_hr = excluded.duration_target_min_hr,
  duration_target_max_hr = excluded.duration_target_max_hr,
  standard_start_hour  = excluded.standard_start_hour,
  standard_end_hour    = excluded.standard_end_hour,
  standard_hour_source = excluded.standard_hour_source,
  is_hold          = excluded.is_hold,
  responsible_role = excluded.responsible_role,
  golden_rule      = excluded.golden_rule,
  timing_confidence = excluded.timing_confidence,
  lab_parameters   = excluded.lab_parameters;


-- ── 5 · Two photographs on every activity someone actually performs. ───────
-- Master PRD: BEFORE / START and AFTER / FINISH. A hold has nobody to photograph it,
-- so holds are excluded — which is also why is_hold exists.

with pa as (
  select pa.id from public.process_activity pa
  join public.process_definition pd on pd.id = pa.process_definition_id
  where pd.code = 'PROCESS-2026C' and pd.version = 1
    and not pa.is_hold
    -- ⚠ AND NOT A LABORATORY ACTIVITY. 0053 adds 41 of them to this same definition,
    -- and on a REPLAY they already exist when this statement runs — so 'every non-hold
    -- activity' silently gave a moisture reading a BEFORE and an AFTER photograph on top
    -- of the SAMPLE_PHOTO its checkpoint actually asks for. Laboratory evidence is
    -- checkpoint-specific and 0053 is the only thing that may seed it.
    and pa.responsible_role <> 'lab_tech')
insert into public.evidence_requirement
  (process_activity_id, key, label, media_kinds, min_count, is_required, gates_submission,
   capture_hint, ordering)
select pa.id, r.key, r.label, array['photo']::text[], 1, true, true, r.hint, r.ord
from pa, (values
  ('BEFORE_PHOTO', 'Before starting', 'Photograph the material and the position before you begin.', 10),
  ('AFTER_PHOTO',  'After finishing', 'Photograph the result before you finish the task.', 20)
) as r(key, label, hint, ord)
on conflict do nothing;


-- ── 6 · The gate the Turner actually has. ──────────────────────────────────
-- Eight hours from THAT pile's own T1 ACTUAL end (F10). It is a condition on an actual,
-- so it is a gate rule and never a planned hour. T2 = T0 start + 24 h was rejected on
-- 30 Aug and must not be built.

with pd as (select id from public.process_definition where code = 'PROCESS-2026C' and version = 1)
insert into public.gate_rule
  (process_activity_id, phase, kind, config, predecessor_binding, is_enabled,
   mapping_confidence, blocked_reason_template, ordering)
select t2.id, 'entry', 'PREDECESSOR',
       jsonb_build_object('activity_codes', jsonb_build_array(t1.code), 'min_rest_hr', 8),
       'SAME_SCOPE_INSTANCE', true, 'dictated',
       'Locked — {predecessor_label} finished less than 8 hours ago. This pile''s T2 is eligible 8 hours after its own T1 actual end.',
       10
from pd
join public.process_activity t2 on t2.process_definition_id = pd.id and t2.code like 'TRN-P%-T2'
join public.process_activity t1 on t1.process_definition_id = pd.id
  and t1.code = replace(t2.code, '-T2', '-T1')
where not exists (
  select 1 from public.gate_rule g
   where g.process_activity_id = t2.id and g.phase = 'entry' and g.kind = 'PREDECESSOR');

