-- ─────────────────────────────────────────────────────────────────────────────
-- 0053 · LAB-2026A, as PROCESS-2026C runs it.
--
-- GENERATED by scripts/gen-lab-2026a.mjs from docs/01-process/lab_checkpoints.json and
-- schedule.json. DO NOT EDIT BY HAND.
--
--   checkpoints   25  (4 gates · 1 decision · 20 records)
--   planned       23 of them produce work in PROCESS-2026C
--   activities    41
--
-- The laboratory is PARALLEL: every activity below is PARALLEL_NO_WALLCLOCK and contributes
-- nothing to the 470-hour envelope. And no lab activity carries a duration — no source states
-- a laboratory turnaround time, and this file does not invent one.
--
-- LAB-RLD2-UNL and LAB-RLD2-RE are seeded as DEFINITIONS and produce no activity: their own
-- note says "only where the process runs a second reload", and PROCESS-2026C runs one.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1 · The checkpoint set is a version of its own. ────────────────────────
-- Beside LAB_DICTATION and S4B_COLUMNS, never replacing them: batches reference those maps and
-- a lab result points at the checkpoint it was taken against.

do $$
begin
  if not exists (select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid
                 where t.typname = 'lab_checkpoint_map' and e.enumlabel = 'LAB_2026A') then
    alter type public.lab_checkpoint_map add value 'LAB_2026A';
  end if;
end $$;


-- ── 2 · What a checkpoint is, beyond its parameters. ───────────────────────
-- `kind` is the whole of LAB-2026A's gate model: a GATE stops production until approved, a
-- DECISION branches the process, a RECORD is evidence and nothing else. It was nowhere in the
-- schema, so no engine could tell them apart.

alter table public.lab_checkpoint
  add column if not exists kind           text not null default 'RECORD',
  add column if not exists evidence_kinds text[] not null default array[]::text[],
  add column if not exists per_pile       boolean not null default false,
  add column if not exists stage          text,
  add column if not exists where_note     text,
  add column if not exists guidance       text,
  add column if not exists sort_order     int,
  add column if not exists confidence     text;

alter table public.lab_checkpoint drop constraint if exists lab_checkpoint_kind_known;
alter table public.lab_checkpoint add constraint lab_checkpoint_kind_known check (
  kind in ('GATE', 'DECISION', 'RECORD'));

comment on column public.lab_checkpoint.kind is
  'GATE stops production until an APPROVED result exists. DECISION branches the process. '
  'RECORD is evidence. LAB-2026A: 4 gates, 1 decision, 20 records. 0052.';

comment on column public.lab_checkpoint.evidence_kinds is
  'The checkpoint-specific evidence LAB-2026A asks for — LOT_PHOTO, WEIGHMENT_SLIP, '
  'SAMPLE_PHOTO, BEFORE_PHOTO, HEIGHT_PHOTO, TUNNEL_PHOTO, AFTER_PHOTO. Not one generic '
  'upload: a weighment slip and a height photo answer different questions. 0052.';


-- ── 3 · The 25 checkpoints. ───────────────────────────────────────────

insert into public.lab_checkpoint
  (checkpoint_map, code, name, kind, stage, where_note, guidance, parameters, evidence_kinds,
   per_pile, sort_order, confidence, scope, source_ref)
values
  ('LAB_2026A', 'LAB-RM-01', 'Raw material / bagasse weighment', 'RECORD', 'PRE-H0', 'Incoming lot, before the clock starts', 'ADVISORY. Recorded, never gates H0.', array['moisture_pct','ph','dry_weight']::text[], array['LOT_PHOTO','WEIGHMENT_SLIP']::text[], false, 10, 'ADVISORY', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-WET-01', 'Bagasse wetting — first hopper pass', 'RECORD', '0A', 'During / at the end of hopper pass 1', 'Target moisture 69–71 %.', array['moisture_pct','ph','ec']::text[], array['SAMPLE_PHOTO']::text[], false, 20, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-WET-02', 'Second hopper pass', 'RECORD', '0A', 'At the end of hopper pass 2', null, array['moisture_pct','ph','ec']::text[], array['SAMPLE_PHOTO']::text[], false, 30, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-BNK-PRE', 'Before first bunker loading', 'GATE', '0A→0B', 'Immediately before bunker filling begins', 'Bunker filling stays locked until approved.', array['moisture_pct','ph','ec']::text[], array['SAMPLE_PHOTO']::text[], false, 40, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-UNL-01', 'Bunker unloading', 'RECORD', '0C', 'At unload, on the sample taken', null, array['moisture_pct','ph','ec']::text[], array['SAMPLE_PHOTO']::text[], false, 50, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-HOP-PRE', 'Before hopper pass', 'RECORD', '0C', 'Between unload and the hopper pass', null, array['moisture_pct','ph','ec']::text[], array['SAMPLE_PHOTO']::text[], false, 60, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-RLD-01', 'Reloading to new bunker', 'RECORD', '0C', 'During reload', null, array['moisture_pct','ph','ec']::text[], array['SAMPLE_PHOTO']::text[], false, 70, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-CM-ARR', 'Chicken manure — on arrival', 'RECORD', '1A', 'When the manure is received', 'Initial composition of the incoming lot.', array['moisture_pct','ph','n_pct','ash_pct']::text[], array['LOT_PHOTO']::text[], false, 80, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-CM-USE', 'Chicken manure — before use in mixing', 'GATE', '1A→1B', 'On unload for the final mix', 'CONFIGURABLE. Required only when the gap since arrival exceeds the configured window. Where arrival is under 12 h before use, this checkpoint is skipped and the arrival reading stands.', array['moisture_pct','ph','n_pct','ash_pct']::text[], array['SAMPLE_PHOTO']::text[], false, 90, 'CONFIGURABLE', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-MOIST-DEC', 'Moisture decision point', 'DECISION', '0C→1B', 'After the second conditioning cycle', '≥ 68 % proceed. < 67 % controlled mist, then re-measure. 67–68 % is UNRESOLVED — record, flag, refer.', array['moisture_pct']::text[], array['SAMPLE_PHOTO']::text[], false, 100, 'UNRESOLVED_BAND', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-PDY-WGH', 'Paddy weighment', 'RECORD', '1C-A', 'At bale weighment, before soaking', 'Parallel stream.', array['moisture_pct','dry_weight']::text[], array['WEIGHMENT_SLIP']::text[], false, 110, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-PDY-S1', 'Paddy soak 1 — pit water', 'RECORD', '1C-A', 'During soaking 1', 'Parallel stream. The water is tested, not the paddy.', array['ph','ec','tds']::text[], array['SAMPLE_PHOTO']::text[], false, 120, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-PDY-S2', 'Paddy soak 2 — pit water', 'RECORD', '1C-A', 'During soaking 2', 'Parallel stream.', array['ph','ec','tds']::text[], array['SAMPLE_PHOTO']::text[], false, 130, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-PDY-S3', 'Paddy soak 3 — pit water', 'RECORD', '1C-A', 'During soaking 3', 'Parallel stream.', array['ph','ec','tds']::text[], array['SAMPLE_PHOTO']::text[], false, 140, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-PRE-T', 'Pre-Turner check', 'RECORD', '1C-B', 'After the second yard flip, before the Turner begins', 'The last check before the material becomes piles.', array['moisture_pct','ph']::text[], array['SAMPLE_PHOTO']::text[], false, 150, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-T1-PRE', 'Moisture before T1', 'RECORD', 'Turner', 'After T0, before T1 — ONE READING PER PILE', 'PER PILE. Six readings for a six-pile batch. Each tied to its own pile.', array['moisture_pct']::text[], array['SAMPLE_PHOTO']::text[], true, 160, 'CONFIRMED', 'pile', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-T1-POST', 'Moisture after T1', 'RECORD', 'Turner', 'Immediately after T1 — ONE READING PER PILE', 'PER PILE. Six readings. This is the last Turner-stage laboratory work.', array['moisture_pct']::text[], array['SAMPLE_PHOTO']::text[], true, 170, 'CONFIRMED', 'pile', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-BNK-LOAD', 'Bunker loading', 'GATE', '1C', 'At each bunker fill — ONE PER BUNKER', 'Height is measured FIRST — it sets the fill.', array['bunker_height','ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], array['BEFORE_PHOTO','HEIGHT_PHOTO']::text[], false, 180, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-RLD-UNL', 'Bunker unloading — reload 1', 'RECORD', '1D-A', 'At unload, before reloading', 'Shrunken height determines the reload height.', array['shrunken_height','moisture_pct']::text[], array['HEIGHT_PHOTO']::text[], false, 190, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-RLD-RE', 'Bunker reloading — reload 1', 'RECORD', '1D-A', 'During reload', 'If moisture is short: water during handling, then re-measure pH, EC, moisture. The original reading is never overwritten.', array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], array['SAMPLE_PHOTO']::text[], false, 200, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-RLD2-UNL', 'Bunker unloading — reload 2', 'RECORD', '1D-B', 'At unload, before the second reload', null, array['shrunken_height','moisture_pct']::text[], array['HEIGHT_PHOTO']::text[], false, 210, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-RLD2-RE', 'Bunker reloading — reload 2', 'RECORD', '1D-B', 'During the second reload', 'Only where the process runs a second reload.', array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], array['SAMPLE_PHOTO']::text[], false, 220, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-TUN-PRE', 'Tunnel readiness', 'RECORD', '2A', 'After tunnel preparation, before filling', 'Height checked first.', array['tunnel_height']::text[], array['TUNNEL_PHOTO']::text[], false, 230, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-TUN-LOAD', 'Tunnel loading', 'GATE', '2B', 'During tunnel filling', 'Locked until height and the full set are approved.', array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], array['BEFORE_PHOTO']::text[], false, 240, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'),
  ('LAB_2026A', 'LAB-QC-FINAL', 'Final QC — tunnel unloading', 'RECORD', '2D', 'At 24 °C, when unloading begins', 'The release record for the batch.', array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','shrunken_height','actinomycetes','smell','colour','spring']::text[], array['SAMPLE_PHOTO','AFTER_PHOTO']::text[], false, 250, 'CONFIRMED', 'master', 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json')
on conflict (checkpoint_map, code) do update set
  name = excluded.name, kind = excluded.kind, stage = excluded.stage,
  where_note = excluded.where_note, guidance = excluded.guidance,
  parameters = excluded.parameters, evidence_kinds = excluded.evidence_kinds,
  per_pile = excluded.per_pile, sort_order = excluded.sort_order,
  confidence = excluded.confidence, scope = excluded.scope;


-- ── 4 · The work, on the hour axis of PROCESS-2026C. ───────────────────────
-- A published definition is frozen (0044), so the standard drops to draft for the length of
-- this file and is published again at the end. Nothing can be planned against a draft, so no
-- baseline can be generated while the window is open.

update public.process_definition set status = 'draft'
 where code = 'PROCESS-2026C' and version = 1;

with pd as (select id from public.process_definition where code = 'PROCESS-2026C' and version = 1)
insert into public.process_activity (
  process_definition_id, code, label_template, stream, rel_day, seq, scope, cardinality_rule,
  standard_start_hour, standard_hour_source, responsible_role, lab_parameters,
  timing_confidence, is_pre_h0, pre_h0_offset, source_ref)
select pd.id, a.code, a.label, 'YARD'::stream_code, a.rel_day, a.seq, a.scope::activity_scope,
       a.cardinality::jsonb, a.hour, 'factory_stated', 'lab_tech'::app_role, a.params,
       'PARALLEL_NO_WALLCLOCK'::process_confidence,
       (a.pre_h0 is not null), a.pre_h0, 'LAB-2026A · docs/01-process/lab_checkpoints.json + schedule.json'
from pd, (values
  ('LAB-RM-01', 'Raw material / bagasse weighment', 0, 10010, 'MASTER', '{"kind":"SINGLETON"}', 0, array['moisture_pct','ph','dry_weight']::text[], 10),
  ('LAB-WET-01', 'Bagasse wetting — first hopper pass', 0, 10020, 'MASTER', '{"kind":"SINGLETON"}', 3, array['moisture_pct','ph','ec']::text[], null::int),
  ('LAB-WET-02', 'Second hopper pass', 0, 10030, 'MASTER', '{"kind":"SINGLETON"}', 14, array['moisture_pct','ph','ec']::text[], null::int),
  ('LAB-BNK-PRE', 'Before first bunker loading', 1, 10040, 'MASTER', '{"kind":"SINGLETON"}', 26, array['moisture_pct','ph','ec']::text[], null::int),
  ('LAB-UNL-01', 'Bunker unloading', 3, 10050, 'MASTER', '{"kind":"SINGLETON"}', 88, array['moisture_pct','ph','ec']::text[], null::int),
  ('LAB-HOP-PRE', 'Before hopper pass', 3, 10060, 'MASTER', '{"kind":"SINGLETON"}', 90, array['moisture_pct','ph','ec']::text[], null::int),
  ('LAB-RLD-01', 'Reloading to new bunker', 3, 10070, 'MASTER', '{"kind":"SINGLETON"}', 93, array['moisture_pct','ph','ec']::text[], null::int),
  ('LAB-CM-ARR', 'Chicken manure — on arrival', 5, 10080, 'MASTER', '{"kind":"SINGLETON"}', 130, array['moisture_pct','ph','n_pct','ash_pct']::text[], null::int),
  ('LAB-CM-USE', 'Chicken manure — before use in mixing', 5, 10090, 'MASTER', '{"kind":"SINGLETON"}', 136, array['moisture_pct','ph','n_pct','ash_pct']::text[], null::int),
  ('LAB-MOIST-DEC', 'Moisture decision point', 5, 10100, 'MASTER', '{"kind":"SINGLETON"}', 133, array['moisture_pct']::text[], null::int),
  ('LAB-PDY-WGH', 'Paddy weighment', 3, 10110, 'MASTER', '{"kind":"SINGLETON"}', 74, array['moisture_pct','dry_weight']::text[], null::int),
  ('LAB-PDY-S1', 'Paddy soak 1 — pit water', 3, 10120, 'MASTER', '{"kind":"SINGLETON"}', 86, array['ph','ec','tds']::text[], null::int),
  ('LAB-PDY-S2', 'Paddy soak 2 — pit water', 4, 10130, 'MASTER', '{"kind":"SINGLETON"}', 108, array['ph','ec','tds']::text[], null::int),
  ('LAB-PDY-S3', 'Paddy soak 3 — pit water', 5, 10140, 'MASTER', '{"kind":"SINGLETON"}', 136, array['ph','ec','tds']::text[], null::int),
  ('LAB-PRE-T', 'Pre-Turner check', 7, 10150, 'MASTER', '{"kind":"SINGLETON"}', 174, array['moisture_pct','ph']::text[], null::int),
  ('LAB-T1-PRE-P1', 'Moisture before T1 — pile 1', 7, 10160, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 1"}', 177, array['moisture_pct']::text[], null::int),
  ('LAB-T1-PRE-P2', 'Moisture before T1 — pile 2', 7, 10170, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 2"}', 180, array['moisture_pct']::text[], null::int),
  ('LAB-T1-PRE-P3', 'Moisture before T1 — pile 3', 7, 10180, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 3"}', 178.5, array['moisture_pct']::text[], null::int),
  ('LAB-T1-PRE-P4', 'Moisture before T1 — pile 4', 7, 10190, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 4"}', 181.5, array['moisture_pct']::text[], null::int),
  ('LAB-T1-PRE-P5', 'Moisture before T1 — pile 5', 7, 10200, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 5"}', 180, array['moisture_pct']::text[], null::int),
  ('LAB-T1-PRE-P6', 'Moisture before T1 — pile 6', 7, 10210, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 6"}', 181.5, array['moisture_pct']::text[], null::int),
  ('LAB-T1-POST-P1', 'Moisture after T1 — pile 1', 7, 10220, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 1"}', 178.5, array['moisture_pct']::text[], null::int),
  ('LAB-T1-POST-P2', 'Moisture after T1 — pile 2', 7, 10230, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 2"}', 181.5, array['moisture_pct']::text[], null::int),
  ('LAB-T1-POST-P3', 'Moisture after T1 — pile 3', 7, 10240, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 3"}', 180, array['moisture_pct']::text[], null::int),
  ('LAB-T1-POST-P4', 'Moisture after T1 — pile 4', 7, 10250, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 4"}', 183, array['moisture_pct']::text[], null::int),
  ('LAB-T1-POST-P5', 'Moisture after T1 — pile 5', 7, 10260, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 5"}', 181.5, array['moisture_pct']::text[], null::int),
  ('LAB-T1-POST-P6', 'Moisture after T1 — pile 6', 7, 10270, 'PILE', '{"kind":"FIXED_LABEL","label":"Pile 6"}', 183, array['moisture_pct']::text[], null::int),
  ('LAB-BNK-LOAD-B1', 'Bunker loading — bunker 1', 8, 10280, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 194, array['bunker_height','ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-BNK-LOAD-B2', 'Bunker loading — bunker 2', 8, 10290, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 196, array['bunker_height','ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-BNK-LOAD-B3', 'Bunker loading — bunker 3', 8, 10300, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 198, array['bunker_height','ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-RLD-UNL-B1', 'Bunker unloading — reload 1 — bunker 1', 10, 10310, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 259, array['shrunken_height','moisture_pct']::text[], null::int),
  ('LAB-RLD-UNL-B2', 'Bunker unloading — reload 1 — bunker 2', 10, 10320, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 261, array['shrunken_height','moisture_pct']::text[], null::int),
  ('LAB-RLD-UNL-B3', 'Bunker unloading — reload 1 — bunker 3', 10, 10330, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 263, array['shrunken_height','moisture_pct']::text[], null::int),
  ('LAB-RLD-RE-B1', 'Bunker reloading — reload 1 — bunker 1', 10, 10340, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 261, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-RLD-RE-B2', 'Bunker reloading — reload 1 — bunker 2', 10, 10350, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 263, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-RLD-RE-B3', 'Bunker reloading — reload 1 — bunker 3', 11, 10360, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 265, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-TUN-PRE', 'Tunnel readiness', 13, 10370, 'MASTER', '{"kind":"SINGLETON"}', 324, array['tunnel_height']::text[], null::int),
  ('LAB-TUN-LOAD-B1', 'Tunnel loading — bunker 1', 13, 10380, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 1"}', 324, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-TUN-LOAD-B2', 'Tunnel loading — bunker 2', 13, 10390, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 2"}', 326, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-TUN-LOAD-B3', 'Tunnel loading — bunker 3', 13, 10400, 'BUNKER_LINE', '{"kind":"FIXED_LABEL","label":"Bunker 3"}', 330, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','smell','colour','spring']::text[], null::int),
  ('LAB-QC-FINAL', 'Final QC — tunnel unloading', 19, 10410, 'MASTER', '{"kind":"SINGLETON"}', 470, array['ph','ec','moisture_pct','n_pct','ash_pct','cn_ratio','shrunken_height','actinomycetes','smell','colour','spring']::text[], null::int)
) as a(code, label, rel_day, seq, scope, cardinality, hour, params, pre_h0)
on conflict (process_definition_id, code) do update set
  label_template = excluded.label_template, rel_day = excluded.rel_day, seq = excluded.seq,
  scope = excluded.scope, cardinality_rule = excluded.cardinality_rule,
  standard_start_hour = excluded.standard_start_hour,
  standard_hour_source = excluded.standard_hour_source,
  responsible_role = excluded.responsible_role, lab_parameters = excluded.lab_parameters,
  timing_confidence = excluded.timing_confidence, is_pre_h0 = excluded.is_pre_h0,
  pre_h0_offset = excluded.pre_h0_offset;


-- ── 5 · Which activity carries which checkpoint. ───────────────────────────
-- The join 0053 needs to bind a gate, and the join a client needs to render a checkpoint form
-- from its definition rather than from twenty-five hand-written screens.

create table if not exists public.lab_checkpoint_activity (
  checkpoint_map      public.lab_checkpoint_map not null,
  checkpoint_code     text not null,
  process_activity_id uuid not null references public.process_activity(id) on delete cascade,
  gates_activity_code text,
  primary key (checkpoint_map, checkpoint_code, process_activity_id)
);

comment on table public.lab_checkpoint_activity is
  'Which planned activity carries which laboratory checkpoint, and — for a GATE — which '
  'PRODUCTION activity it holds. lab_checkpoints.json supplies blocks_activity_code as null on '
  'purpose: real activity codes are read from process_activity, never invented. 0052.';

alter table public.lab_checkpoint_activity enable row level security;
drop policy if exists lab_checkpoint_activity_read on public.lab_checkpoint_activity;
create policy lab_checkpoint_activity_read on public.lab_checkpoint_activity
  for select to authenticated using (true);
grant select on public.lab_checkpoint_activity to authenticated;

with pd as (select id from public.process_definition where code = 'PROCESS-2026C' and version = 1)
insert into public.lab_checkpoint_activity
  (checkpoint_map, checkpoint_code, process_activity_id, gates_activity_code)
select 'LAB_2026A', m.checkpoint_code, pa.id, m.gates_code
from pd
join (values
  ('LAB-RM-01', 'LAB-RM-01', 'FIB-WET-1'),
  ('LAB-WET-01', 'LAB-WET-01', 'FIB-WET-1'),
  ('LAB-WET-02', 'LAB-WET-02', 'FIB-HOP-2'),
  ('LAB-BNK-PRE', 'LAB-BNK-PRE', 'FIB-BUNK-LOAD'),
  ('LAB-UNL-01', 'LAB-UNL-01', 'FIB-RELOAD-1'),
  ('LAB-HOP-PRE', 'LAB-HOP-PRE', 'FIB-RELOAD-1'),
  ('LAB-RLD-01', 'LAB-RLD-01', 'FIB-RELOAD-1'),
  ('LAB-CM-ARR', 'LAB-CM-ARR', 'CM-WEIGH'),
  ('LAB-CM-USE', 'LAB-CM-USE', 'MIX-CM-ADD'),
  ('LAB-MOIST-DEC', 'LAB-MOIST-DEC', 'FIB-MOIST-DEC'),
  ('LAB-PDY-WGH', 'LAB-PDY-WGH', 'STR-WEIGH'),
  ('LAB-PDY-S1', 'LAB-PDY-S1', 'STR-SOAK-1'),
  ('LAB-PDY-S2', 'LAB-PDY-S2', 'STR-SOAK-2'),
  ('LAB-PDY-S3', 'LAB-PDY-S3', 'STR-SOAK-3'),
  ('LAB-PRE-T', 'LAB-PRE-T', 'YARD-FLIP'),
  ('LAB-T1-PRE-P1', 'LAB-T1-PRE', 'TRN-P1-T1'),
  ('LAB-T1-PRE-P2', 'LAB-T1-PRE', 'TRN-P2-T1'),
  ('LAB-T1-PRE-P3', 'LAB-T1-PRE', 'TRN-P3-T1'),
  ('LAB-T1-PRE-P4', 'LAB-T1-PRE', 'TRN-P4-T1'),
  ('LAB-T1-PRE-P5', 'LAB-T1-PRE', 'TRN-P5-T1'),
  ('LAB-T1-PRE-P6', 'LAB-T1-PRE', 'TRN-P6-T1'),
  ('LAB-T1-POST-P1', 'LAB-T1-POST', 'TRN-P1-T1'),
  ('LAB-T1-POST-P2', 'LAB-T1-POST', 'TRN-P2-T1'),
  ('LAB-T1-POST-P3', 'LAB-T1-POST', 'TRN-P3-T1'),
  ('LAB-T1-POST-P4', 'LAB-T1-POST', 'TRN-P4-T1'),
  ('LAB-T1-POST-P5', 'LAB-T1-POST', 'TRN-P5-T1'),
  ('LAB-T1-POST-P6', 'LAB-T1-POST', 'TRN-P6-T1'),
  ('LAB-BNK-LOAD-B1', 'LAB-BNK-LOAD', 'BNK-B1-FILL'),
  ('LAB-BNK-LOAD-B2', 'LAB-BNK-LOAD', 'BNK-B2-FILL'),
  ('LAB-BNK-LOAD-B3', 'LAB-BNK-LOAD', 'BNK-B3-FILL'),
  ('LAB-RLD-UNL-B1', 'LAB-RLD-UNL', 'BNK-B1-RELOAD'),
  ('LAB-RLD-UNL-B2', 'LAB-RLD-UNL', 'BNK-B2-RELOAD'),
  ('LAB-RLD-UNL-B3', 'LAB-RLD-UNL', 'BNK-B3-RELOAD'),
  ('LAB-RLD-RE-B1', 'LAB-RLD-RE', 'BNK-B1-RELOAD'),
  ('LAB-RLD-RE-B2', 'LAB-RLD-RE', 'BNK-B2-RELOAD'),
  ('LAB-RLD-RE-B3', 'LAB-RLD-RE', 'BNK-B3-RELOAD'),
  ('LAB-TUN-PRE', 'LAB-TUN-PRE', 'BNK-B1-TUN-LOAD'),
  ('LAB-TUN-LOAD-B1', 'LAB-TUN-LOAD', 'BNK-B1-TUN-LOAD'),
  ('LAB-TUN-LOAD-B2', 'LAB-TUN-LOAD', 'BNK-B2-TUN-LOAD'),
  ('LAB-TUN-LOAD-B3', 'LAB-TUN-LOAD', 'BNK-B3-TUN-LOAD'),
  ('LAB-QC-FINAL', 'LAB-QC-FINAL', 'TUN-DISCHARGE-1')
) as m(activity_code, checkpoint_code, gates_code) on true
join public.process_activity pa on pa.process_definition_id = pd.id and pa.code = m.activity_code
on conflict do nothing;


-- ── 6 · Checkpoint-specific evidence. ──────────────────────────────────────
-- LAB-2026A asks for seven distinct kinds and the difference matters: a HEIGHT_PHOTO proves the
-- measurement that sets the reload height, and a WEIGHMENT_SLIP is a document. Collapsing them
-- into one "upload image" would lose the question each was answering.

with pd as (select id from public.process_definition where code = 'PROCESS-2026C' and version = 1)
insert into public.evidence_requirement
  (process_activity_id, key, label, media_kinds, min_count, is_required, gates_submission,
   capture_hint, ordering)
select pa.id, e.key, e.label, array['photo']::text[], 1, true, true, e.hint, e.ord
from pd
join (values
  ('LAB-RM-01', 'LOT_PHOTO', 'Lot photograph', 'Photograph the incoming lot as received.', 10),
  ('LAB-RM-01', 'WEIGHMENT_SLIP', 'Weighment slip', 'Photograph the weighbridge slip so the figure is traceable.', 20),
  ('LAB-WET-01', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-WET-02', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-BNK-PRE', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-UNL-01', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-HOP-PRE', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-RLD-01', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-CM-ARR', 'LOT_PHOTO', 'Lot photograph', 'Photograph the incoming lot as received.', 10),
  ('LAB-CM-USE', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-MOIST-DEC', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-PDY-WGH', 'WEIGHMENT_SLIP', 'Weighment slip', 'Photograph the weighbridge slip so the figure is traceable.', 10),
  ('LAB-PDY-S1', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-PDY-S2', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-PDY-S3', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-PRE-T', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-PRE-P1', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-PRE-P2', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-PRE-P3', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-PRE-P4', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-PRE-P5', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-PRE-P6', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-POST-P1', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-POST-P2', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-POST-P3', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-POST-P4', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-POST-P5', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-T1-POST-P6', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-BNK-LOAD-B1', 'BEFORE_PHOTO', 'Before photograph', 'Photograph the material before the operation begins.', 10),
  ('LAB-BNK-LOAD-B1', 'HEIGHT_PHOTO', 'Height photograph', 'Photograph the height measurement — it sets what happens next.', 20),
  ('LAB-BNK-LOAD-B2', 'BEFORE_PHOTO', 'Before photograph', 'Photograph the material before the operation begins.', 10),
  ('LAB-BNK-LOAD-B2', 'HEIGHT_PHOTO', 'Height photograph', 'Photograph the height measurement — it sets what happens next.', 20),
  ('LAB-BNK-LOAD-B3', 'BEFORE_PHOTO', 'Before photograph', 'Photograph the material before the operation begins.', 10),
  ('LAB-BNK-LOAD-B3', 'HEIGHT_PHOTO', 'Height photograph', 'Photograph the height measurement — it sets what happens next.', 20),
  ('LAB-RLD-UNL-B1', 'HEIGHT_PHOTO', 'Height photograph', 'Photograph the height measurement — it sets what happens next.', 10),
  ('LAB-RLD-UNL-B2', 'HEIGHT_PHOTO', 'Height photograph', 'Photograph the height measurement — it sets what happens next.', 10),
  ('LAB-RLD-UNL-B3', 'HEIGHT_PHOTO', 'Height photograph', 'Photograph the height measurement — it sets what happens next.', 10),
  ('LAB-RLD-RE-B1', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-RLD-RE-B2', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-RLD-RE-B3', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-TUN-PRE', 'TUNNEL_PHOTO', 'Tunnel photograph', 'Photograph the prepared tunnel.', 10),
  ('LAB-TUN-LOAD-B1', 'BEFORE_PHOTO', 'Before photograph', 'Photograph the material before the operation begins.', 10),
  ('LAB-TUN-LOAD-B2', 'BEFORE_PHOTO', 'Before photograph', 'Photograph the material before the operation begins.', 10),
  ('LAB-TUN-LOAD-B3', 'BEFORE_PHOTO', 'Before photograph', 'Photograph the material before the operation begins.', 10),
  ('LAB-QC-FINAL', 'SAMPLE_PHOTO', 'Sample photograph', 'Photograph the sample as taken, before testing.', 10),
  ('LAB-QC-FINAL', 'AFTER_PHOTO', 'After photograph', 'Photograph the result.', 20)
) as e(activity_code, key, label, hint, ord) on true
join public.process_activity pa on pa.process_definition_id = pd.id and pa.code = e.activity_code
on conflict (process_activity_id, key) do update set
  label = excluded.label, capture_hint = excluded.capture_hint, ordering = excluded.ordering;


-- ── 7 · Published again, and the envelope must not have moved. ─────────────

update public.process_definition
   set status = 'published', published_at = coalesce(published_at, now())
 where code = 'PROCESS-2026C' and version = 1;

do $$
declare s record;
begin
  select * into s from public.v_process_envelope where code = 'PROCESS-2026C';
  if s.envelope_disagrees then
    raise exception
      'Seeding the laboratory moved PROCESS-2026C''s standard: its activities now compute %h against a stated envelope of %h. Laboratory work is parallel and must contribute no wall clock — check that every lab activity is PARALLEL_NO_WALLCLOCK.',
      s.calculated_standard_hr, s.stated_envelope_hr;
  end if;
end $$;
