-- ─────────────────────────────────────────────────────────────────────────────
-- 0071 · What fifty tired people with phones can do to this system.
--
-- Everything here was found by attacking the deployed system over HTTP as a real signed-in person,
-- with the public anon key and nothing else — no service-role key, no direct SQL. Fifty users is a
-- scalability question and it is not interesting. The interesting question is whether fifty
-- ordinary people, with duplicate taps, dead signal, stale screens, two phones and the wrong
-- account, can corrupt a batch. Seventy-seven attacks were repelled. These four were not.
--
--   start_activity   answered 204 for a LOCKED activity, and audited every duplicate tap
--   bind_evidence    accepted a zero-byte file as a photograph, satisfying the evidence gate
--   submit_activity  let an OPERATOR finish work that was never started, stamping a permanent
--                    actual_start for work nobody did
--   submit_activity  raced with itself, so two of five concurrent submits both wrote to the trail
--
-- WHAT WAS NOT BROKEN, AND IS WORTH SAYING. No gate opened that should not have. No plan moved
-- after activation, by any role or any path. No batch reached another batch — not by evidence, not
-- by storage path, not by lab sample, not by completion. No client-supplied timestamp was ever
-- stored. A rejected lab submission opened nothing, and a lab technician could not decide their
-- own. Every pile waited on its own Turner T1. The two process versions each computed their own
-- standard, 470 and 536. The append-only rule held against a superuser connection.
--
-- Generated by scripts/break/_gen0071.mjs from the deployed bodies, patched between statement
-- anchors rather than retyped.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.start_activity(p_activity uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform public.assert_role(array['operator', 'supervisor', 'lab_tech']::app_role[], 'start an activity');

  perform public.assert_may_execute(p_activity, 'start an activity');
  -- 0071 · WHAT HAPPENED, AND WHY THIS IS NOT A COSMETIC CHANGE.
  --
  -- The update below has always been guarded by `state in ('READY','RETURNED')`, so a LOCKED
  -- activity was never started and the gate always held. But the audit insert that followed ran
  -- unconditionally, and the function returned void either way. Two things came of that:
  --
  --   · Starting a LOCKED activity over HTTP answered 204 — success — while the row stayed LOCKED.
  --     A refusal that reports success is worse than a refusal, because the caller believes it.
  --   · Five duplicate taps wrote five 'Work started' rows for one start. The trail then reads as
  --     though the work began five times. This product exists to answer "what did happen"; a trail
  --     that says something happened five times when it happened once is a defect in the answer.
  --
  -- So the audit row now follows the update instead of accompanying it, and a genuine refusal says
  -- why — using the reason the engine already computed, rather than inventing a second opinion.
  declare
    touched int;
    st      text;
    why     text;
    ttl     text;
  begin
    update batch_activity
       set state = 'IN_PROGRESS',
           actual_start = coalesce(actual_start, now()),
           blocked_reason = null
     where id = p_activity and state in ('READY','RETURNED');
    get diagnostics touched = row_count;

    if touched = 0 then
      select ba.state::text, ba.blocked_reason, ba.title
        into st, why, ttl
        from batch_activity ba where ba.id = p_activity;

      -- Not found is not this function's business — 0067 settled that for assert_may_execute, and
      -- the same reasoning holds here.
      if st is null then
        return;
      end if;

      -- Already running. The second, third and fifth tap of a jittery thumb, or a phone retrying
      -- because it never heard the answer. Idempotent, and deliberately silent: nothing changed,
      -- so nothing is recorded.
      if st = 'IN_PROGRESS' then
        return;
      end if;

      raise exception '%', coalesce(
        nullif(why, ''),
        ttl || ' is ' || st || ', so it cannot be started yet. It opens when the conditions on '
             || 'its card are met.')
        using errcode = 'check_violation';
    end if;

    insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
    values (auth.uid(), public.current_app_role(), 'start_activity', 'batch_activity',
            p_activity::text, 'Work started');
  end;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.bind_evidence(p_activity uuid, p_requirement_key text, p_storage_path text, p_media_kind text DEFAULT 'photo'::text, p_supersedes uuid DEFAULT NULL::uuid, p_supersede_reason text DEFAULT NULL::text)
 RETURNS TABLE(media_id uuid, requirement_key text, satisfied_count integer, min_count integer, uploaded_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba      batch_activity;
  req     batch_activity_evidence_req;
  obj     record;
  segs    text[];
  new_id  uuid;
  live    int;
begin
  if auth.uid() is null then
    raise exception 'bind_evidence needs a signed-in user — the uploader is taken from the JWT, never from a parameter'
      using errcode = 'insufficient_privilege';
  end if;

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  -- 5 · entitlement first, so an unauthorised caller learns nothing about the rest.
  if not public.can_capture_for_activity(p_activity) then
    raise exception
      'Not permitted: % may not capture evidence for %. Evidence is captured by the assigned '
      'operator or lab technician, or by a supervisor (ROLE_AND_APPROVAL_MODEL §2).',
      coalesce(public.current_app_role()::text, 'an unknown role'), ba.title
      using errcode = 'insufficient_privilege';
  end if;

  -- 3 · the requirement must be this activity's.
  select * into req from batch_activity_evidence_req
   where batch_activity_id = p_activity and key = p_requirement_key;
  if not found then
    raise exception 'Activity % has no evidence requirement named %', ba.title, p_requirement_key;
  end if;

  -- 4 · the kind must be one this requirement accepts.
  if not (p_media_kind = any (req.media_kinds)) then
    raise exception '% accepts % — % was offered',
      req.label, array_to_string(req.media_kinds, ' or '), p_media_kind;
  end if;

  -- 2 · the path must name this batch and this activity.
  segs := string_to_array(p_storage_path, '/');
  if array_length(segs, 1) <> 3
     or segs[1] <> ba.master_batch_id::text
     or segs[2] <> p_activity::text then
    raise exception
      'Storage path % does not belong to this activity. Expected %/%/<file>',
      p_storage_path, ba.master_batch_id, p_activity;
  end if;

  -- 1 · THE INTEGRITY RULE. The object has to be there already.
  select o.id, o.metadata into obj
    from storage.objects o
   where o.bucket_id = 'evidence' and o.name = p_storage_path;
  if not found then
    raise exception
      'No object at evidence/% — upload the file first, then bind it. A row claiming a photograph '
      'that is not in storage is a false record.', p_storage_path
      using errcode = 'no_data_found';
  end if;

  -- 0071 · AN EMPTY FILE IS NOT A PHOTOGRAPH.
  --
  -- The object-exists rule above asks whether something is in storage. It does not ask whether that
  -- something is anything. A zero-byte upload was accepted and bound, and satisfied the requirement
  -- outright — satisfied_count 1 of 1 — so an evidence gate could be cleared with nothing at all.
  -- That is not a hypothetical: a camera that fails, a file picker cancelled at the wrong instant
  -- and a dropped connection all produce exactly this, and the operator is then told they are done.
  --
  -- Found by uploading Buffer.alloc(0) as a real signed-in operator.
  if coalesce(nullif(obj.metadata->>'size', '')::bigint, 0) <= 0 then
    raise exception
      'The file uploaded for % is empty (0 bytes). That is usually a photograph that did not '
      'capture, or an upload cut short. Take it again.', req.label
      using errcode = 'check_violation';
  end if;

  -- 6 · already satisfied? Only an explicit retake may proceed.
  select count(*) into live from evidence_media
   where requirement_id = req.id and superseded_by_id is null;

  if p_supersedes is null and live >= req.min_count then
    raise exception
      '% already has % of % item(s). Pass the id of the item this one replaces, with a reason.',
      req.label, live, req.min_count;
  end if;

  if p_supersedes is not null then
    if coalesce(trim(p_supersede_reason), '') = '' then
      raise exception 'Replacing an evidence item needs a reason — the original is kept, not deleted';
    end if;
    if not exists (
      select 1 from evidence_media
       where id = p_supersedes and requirement_id = req.id and superseded_by_id is null
    ) then
      raise exception 'No live evidence item % on %', p_supersedes, req.label;
    end if;
  end if;

  insert into evidence_media (
    master_batch_id, batch_activity_id, requirement_id, requirement_key,
    storage_path, media_kind, mime_type, byte_size, uploaded_by
  ) values (
    ba.master_batch_id, p_activity, req.id, req.key,
    p_storage_path, p_media_kind,
    nullif(obj.metadata->>'mimetype', ''),
    nullif(obj.metadata->>'size', '')::bigint,
    auth.uid()
  )
  returning id into new_id;

  -- §6 — retaking does not delete. The original stays, pointing at what replaced it.
  if p_supersedes is not null then
    update evidence_media
       set superseded_by_id = new_id, superseded_reason = p_supersede_reason
     where id = p_supersedes;
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'bind_evidence', 'evidence_media', new_id::text,
          jsonb_build_object('activity', p_activity, 'requirement', req.key, 'path', p_storage_path),
          case when p_supersedes is null then 'Evidence captured for ' || req.label
               else 'Retake of ' || req.label || ': ' || p_supersede_reason end);

  return query
    select new_id, req.key, r.satisfied_count, r.min_count,
           (select m.uploaded_at from evidence_media m where m.id = new_id)
      from batch_activity_evidence_req r where r.id = req.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_activity(p_activity uuid, p_values jsonb DEFAULT '{}'::jsonb, p_remarks text DEFAULT NULL::text, p_actual_start timestamp with time zone DEFAULT NULL::timestamp with time zone, p_actual_end timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS TABLE(new_state text, out_of_range integer, outstanding_evidence text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba          batch_activity;
  b           master_batch;
  k           text;
  v           text;
  fld         batch_activity_value;
  flag        text;
  target      numeric;
  target_src  text;
  dev_count   int := 0;
  reasons     text := '';
  outstanding text;
  entered_at  timestamptz := now();
  h0          timestamptz;
  eff_start   timestamptz;
  eff_end     timestamptz;
  -- Each failing field, captured so the deviation rows can be written after the state settles.
  fails       jsonb := '[]'::jsonb;
  f           jsonb;
begin
  perform public.assert_role(array['operator', 'supervisor', 'lab_tech']::app_role[], 'submit an activity');

  -- 0071 · LOCK THE ROW, THEN DECIDE.
  -- The state check below is a read followed by a write. Five phones submitting at once all read
  -- IN_PROGRESS, and two of them got through before either had committed — one completion, one
  -- actual_end, but two 'submit_activity' rows in the trail. Taking the row lock here serialises
  -- them, so the second caller re-reads a COMPLETED row and receives the refusal that already
  -- exists a few lines below.
  select * into ba from batch_activity where id = p_activity for update;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  -- 0050 · An operator records work by doing it, not by typing when it happened.
  if (p_actual_start is not null or p_actual_end is not null)
     and coalesce(public.current_app_role()::text, '') = 'operator' then
    raise exception
      'An operator may not state a start or end time. Use start_activity and '
      'complete_activity and the server records when it happened. If a time has to be '
      'entered after the fact, a supervisor does it.'
      using errcode = 'insufficient_privilege';
  end if;


  select * into b from master_batch where id = ba.master_batch_id;
  if b.status <> 'active' then
    raise exception 'Batch % is % — activate it before recording work', b.code, b.status;
  end if;
  if ba.state not in ('READY','IN_PROGRESS','RETURNED') then
    raise exception '% is %, so it cannot be submitted', ba.title, ba.state;
  end if;

  -- 0071 · AN OPERATOR CANNOT FINISH WHAT THEY NEVER STARTED.
  --
  -- Submitting from READY is deliberate and stays: a supervisor recording a paper slip after the
  -- fact has no start_activity call to lean on. But for an OPERATOR it produced a quiet lie. One
  -- stray tap on Finish stamped actual_start = now() for work that never began, and
  -- fn_actual_is_append_only then makes that stamp permanent — there is no un-happen, by design.
  -- So the mistake is unrecoverable, which is the wrong price for a mis-tap on a factory phone.
  --
  -- The refusal names the fix, because the operator's own screen has the button.
  if ba.actual_start is null
     and coalesce(public.current_app_role()::text, '') = 'operator' then
    raise exception
      '% has not been started, so it cannot be finished. Tap Start on the task first — the server '
      'records when it began.', ba.title
      using errcode = 'check_violation';
  end if;

  -- ── Recorded actuals are validated BEFORE anything is written ─────────────
  -- Carried unchanged from 0016. A refusal must leave the row exactly as it was, and a refusal an
  -- operator cannot act on is barely better than a silent one — so every message names the
  -- activity and the value it rejected.

  if p_actual_start is not null and p_actual_start > entered_at then
    raise exception
      'Cannot record a start of % for %: that is in the future. An actual is something that has '
      'already happened.', p_actual_start, ba.title
      using errcode = 'invalid_datetime_format';
  end if;

  if p_actual_end is not null and p_actual_end > entered_at then
    raise exception
      'Cannot record an end of % for %: that is in the future. An actual is something that has '
      'already happened.', p_actual_end, ba.title
      using errcode = 'invalid_datetime_format';
  end if;

  -- The EFFECTIVE pair, so a stated end earlier than an already-recorded start is refused too —
  -- start_activity may have written actual_start when the operator opened the card.
  eff_start := coalesce(p_actual_start, ba.actual_start);
  eff_end   := coalesce(p_actual_end, ba.actual_end);

  if eff_start is not null and eff_end is not null and eff_end < eff_start then
    raise exception
      'Cannot record % ending at % when it started at %: work does not end before it begins.',
      ba.title, eff_end, eff_start
      using errcode = 'invalid_datetime_format';
  end if;

  -- NEW in B2 · a STATED actual may not precede H0. `batchHour()` already throws on it —
  -- "nothing in a batch happens before H0" — so the server agrees with the domain function
  -- rather than accepting what the client would refuse to render.
  --
  -- SCOPED TO WHAT THE SUBMITTER STATES, deliberately. Applying it to the `now()` default would
  -- also refuse a live recording on a batch whose `start_at` is still in the future — and that
  -- situation is reachable today: `activate_batch` does not require H0 to have passed, and
  -- `start_activity` stamps `now()` with no H0 check, so an activity can already carry an
  -- `actual_start` a month before its own batch began. Refusing at submit would strand an
  -- operator over a value they did not state.
  --
  -- That incoherence is REAL and PRE-EXISTING, and it is registered as TBD-52 rather than
  -- resolved here: whether "active" should mean "started" is a factory question, and answering
  -- it inside a deviations migration would be the wrong place and the wrong authority.
  h0 := b.start_at;
  if h0 is not null and p_actual_start is not null and p_actual_start < h0 then
    raise exception
      'Cannot record % starting at %: the batch begins at % and nothing in it happens before '
      'that.', ba.title, p_actual_start, h0
      using errcode = 'invalid_datetime_format';
  end if;
  if h0 is not null and p_actual_end is not null and p_actual_end < h0 then
    raise exception
      'Cannot record % ending at %: the batch begins at % and nothing in it happens before '
      'that.', ba.title, p_actual_end, h0
      using errcode = 'invalid_datetime_format';
  end if;

  for k, v in select * from jsonb_each_text(p_values) loop
    select * into fld from batch_activity_value
     where batch_activity_id = p_activity and field_key = k;
    continue when not found;

    flag := 'not_applicable';

    if v ~ '^-?[0-9]+(\.[0-9]+)?$' then
      target := null;
      target_src := null;

      if fld.day0_value ~ '^-?[0-9]+(\.[0-9]+)?$' then
        target := fld.day0_value::numeric;
        target_src := 'the Day-0 plan';
      elsif ba.planned_qty_mt is not null and k like '%qty%' then
        target := ba.planned_qty_mt;
        target_src := 'the Day-0 plan';
      end if;

      if fld.sop_min is not null or fld.sop_max is not null then
        if (fld.sop_min is not null and v::numeric < fld.sop_min)
           or (fld.sop_max is not null and v::numeric > fld.sop_max) then
          flag := 'out_of_range';
          dev_count := dev_count + 1;
          reasons := reasons || fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                     || ' outside the SOP band ' || coalesce(fld.sop_min::text,'')
                     || '–' || coalesce(fld.sop_max::text,'') || '; ';
          fails := fails || jsonb_build_object(
            'kind', 'VALUE_OUT_OF_SOP',
            'summary', fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                       || ' is outside the SOP band '
                       || coalesce(fld.sop_min::text,'') || '–' || coalesce(fld.sop_max::text,''),
            'detail', jsonb_build_object(
              'field_key', k, 'label', fld.label, 'value', v, 'unit', fld.unit,
              'sop_min', fld.sop_min, 'sop_max', fld.sop_max,
              'sop_source_ref', fld.sop_source_ref, 'conflict_id', fld.conflict_id,
              'day0_value', fld.day0_value));
        else
          flag := 'in_range';
        end if;

      elsif target is not null and target > 0 then
        if abs(v::numeric - target) / target > 0.10 then
          flag := 'out_of_range';
          dev_count := dev_count + 1;
          reasons := reasons || fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                     || ' against ' || target || coalesce(' ' || fld.unit,'')
                     || ' in ' || target_src || ' ('
                     || case when v::numeric > target then '+' else '' end
                     || round(v::numeric - target, 2) || '); ';
          fails := fails || jsonb_build_object(
            'kind', 'VALUE_OFF_DAY0_TARGET',
            'summary', fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                       || ' against ' || target || coalesce(' ' || fld.unit,'')
                       || ' planned at Day 0 ('
                       || case when v::numeric > target then '+' else '' end
                       || round(v::numeric - target, 2) || ')',
            'detail', jsonb_build_object(
              'field_key', k, 'label', fld.label, 'value', v, 'unit', fld.unit,
              'target', target, 'target_source', target_src,
              'tolerance_pct', 10, 'conflict_id', fld.conflict_id,
              -- No SOP band exists here. Saying so is information: docs/LAB_MODEL.md §9.
              'sop_source_ref', fld.sop_source_ref));
        else
          flag := 'in_range';
        end if;
      end if;
    end if;

    update batch_activity_value
       set actual_value = v,
           actual_recorded_at = entered_at,
           actual_recorded_by = auth.uid(),
           variance_flag = flag,
           remarks = coalesce(nullif(p_remarks,''), remarks)
     where id = fld.id;
  end loop;

  select gv.reason into outstanding
  from public.evaluate_gates(p_activity, 'exit') gv
  where gv.kind = 'EVIDENCE_COMPLETE' and gv.verdict = 'fail'
  order by gv.ordering
  limit 1;

  if outstanding is not null then
    update batch_activity
       set state = 'IN_PROGRESS',
           actual_start = coalesce(actual_start, p_actual_start, entered_at),
           actual_end = coalesce(actual_end, p_actual_end),
           actual_recorded_at = entered_at,
           blocked_reason = null
     where id = p_activity;

    insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                             after_state, reason)
    values (auth.uid(), public.current_app_role(), 'submit_blocked_on_evidence',
            'batch_activity', p_activity::text,
            jsonb_build_object('actual_start', p_actual_start, 'actual_end', p_actual_end,
                               'recorded_at', entered_at),
            outstanding);

    return query select 'IN_PROGRESS'::text, dev_count, outstanding;
    return;
  end if;

  update batch_activity
     set state = case when dev_count > 0 then 'DEVIATION'::activity_state
                      else 'COMPLETED'::activity_state end,
         actual_start = coalesce(actual_start, p_actual_start, entered_at),
         actual_end = coalesce(actual_end, p_actual_end, entered_at),
         actual_recorded_at = entered_at,
         submitted_at = entered_at,
         submitted_by = auth.uid(),
         blocked_reason = case when dev_count > 0
           then rtrim(reasons, '; ') || ' — held for supervisor review' end
   where id = p_activity;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                           after_state, reason)
  select auth.uid(), public.current_app_role(), 'submit_activity', 'batch_activity',
         p_activity::text,
         jsonb_build_object(
           'actual_start', cur.actual_start,
           'actual_end', cur.actual_end,
           'recorded_at', cur.actual_recorded_at,
           'duration_actual_min', cur.duration_actual_min,
           'variance_minutes', cur.variance_minutes,
           'stated_by_submitter', (p_actual_start is not null or p_actual_end is not null)),
         case when dev_count > 0 then 'DEVIATION · ' || rtrim(reasons,'; ')
              else coalesce(nullif(p_remarks,''), 'submitted') end
    from batch_activity cur where cur.id = p_activity;

  -- ── B2 · every failing field becomes a record someone can act on ──────────────
  -- One row per failing condition, not one per submission: §3.1 waives "one failing condition"
  -- at a time, so a supervisor must be able to accept one and refuse another.
  for f in select * from jsonb_array_elements(fails) loop
    insert into deviation (master_batch_id, batch_activity_id, kind, summary, detail,
                           raised_by, raised_by_role)
    values (ba.master_batch_id, p_activity, (f->>'kind')::deviation_kind,
            f->>'summary', f->'detail', auth.uid(), public.current_app_role());
  end loop;

  if dev_count = 0 then
    perform public.advance_batch(ba.master_batch_id);
  else
    update batch_activity nxt
       set state = 'BLOCKED',
           blocked_reason = 'Blocked — ' || ba.title || ' (' || ba.scope_label
                            || ') is in deviation: ' || rtrim(reasons, '; ')
     where nxt.master_batch_id = ba.master_batch_id
       and nxt.stream = ba.stream
       and nxt.seq > ba.seq
       and nxt.state in ('LOCKED','READY','WAITING_TIME')
       and nxt.seq = (
         select min(n2.seq) from batch_activity n2
         where n2.master_batch_id = ba.master_batch_id
           and n2.stream = ba.stream
           and n2.seq > ba.seq
           and n2.state in ('LOCKED','READY','WAITING_TIME'));
  end if;

  return query
    select (select state::text from batch_activity where id = p_activity), dev_count, null::text;
end;
$function$
;

-- ── Assertions ───────────────────────────────────────────────────────────────

do $a$
declare
  n int;
begin
  -- The three patches are actually in the deployed bodies, not merely in this file.
  if position('get diagnostics touched' in pg_get_functiondef('public.start_activity(uuid)'::regprocedure)) = 0 then
    raise exception '0071 failed: start_activity does not check whether it changed anything';
  end if;
  if position('is empty (0 bytes)' in pg_get_functiondef(
       'public.bind_evidence(uuid,text,text,text,uuid,text)'::regprocedure)) = 0 then
    raise exception '0071 failed: bind_evidence does not reject an empty file';
  end if;
  if position('for update' in pg_get_functiondef(
       'public.submit_activity(uuid,jsonb,text,timestamptz,timestamptz)'::regprocedure)) = 0 then
    raise exception '0071 failed: submit_activity does not lock the row';
  end if;
  if position('has not been started, so it cannot be finished' in pg_get_functiondef(
       'public.submit_activity(uuid,jsonb,text,timestamptz,timestamptz)'::regprocedure)) = 0 then
    raise exception '0071 failed: submit_activity still lets an operator finish an unstarted task';
  end if;

  -- The guards these functions already carried must all still be there. A patch that silently
  -- drops one is the failure mode 0062 was rebuilt to avoid.
  for n in 1..1 loop
    if position('An operator may not state a start or end time' in pg_get_functiondef(
         'public.submit_activity(uuid,jsonb,text,timestamptz,timestamptz)'::regprocedure)) = 0 then
      raise exception '0071 failed: the client-timestamp refusal is gone from submit_activity';
    end if;
    if position('does not belong to this activity' in pg_get_functiondef(
         'public.bind_evidence(uuid,text,text,text,uuid,text)'::regprocedure)) = 0 then
      raise exception '0071 failed: the storage-path check is gone from bind_evidence';
    end if;
    if position('No object at evidence/' in pg_get_functiondef(
         'public.bind_evidence(uuid,text,text,text,uuid,text)'::regprocedure)) = 0 then
      raise exception '0071 failed: the object-exists check is gone from bind_evidence';
    end if;
    if position('assert_may_execute' in pg_get_functiondef('public.start_activity(uuid)'::regprocedure)) = 0 then
      raise exception '0071 failed: the role check is gone from start_activity';
    end if;
  end loop;

  raise notice '0071 · a locked task refuses out loud, an empty file is not evidence, and a task '
               'cannot be finished before it starts';
end $a$;
