-- ─────────────────────────────────────────────────────────────────────────────
-- 0072 · A gate that opened can shut again, and a reading belongs to its own checkpoint.
--
-- Wave 2 of the adversarial pass. Both defects here are of the same family: everything looks
-- correct in isolation, and the relationship between two correct things is what is wrong.
--
-- P0 · A REJECTION AFTER AN APPROVAL LEFT PRODUCTION OPEN.
--      lab_decision seq 368 approved (supervisor), seq 369 rejected (gm).
--      v_lab_approval_queue.latest_verdict said 'rejected'. BNK-B3-FILL stayed READY.
--      evaluate_gates was never at fault — its LAB_APPROVED rule already reads the latest
--      decision. advance_batch simply never asked again, because its scan only ever considered
--      activities that were already shut.
--
-- P1 · A LABORATORY SAMPLE COULD BE FILED AT ANY CHECKPOINT, BY ANYONE.
--      No role check: an operator opened a lab sample and was given HTTP 200.
--      No pairing check: the specification band comes from the sample's checkpoint, so the same
--      reading could be judged against 72.5-74 or 65-68 depending on where it was filed.
--
-- Neither was reachable through the screens. Both were reachable with a phone, a login and the
-- public anon key, which is the only test that counts.
--
-- Generated by scripts/break/_gen0072.mjs from the deployed bodies.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.advance_batch(p_batch uuid)
 RETURNS TABLE(opened integer, resting integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  n_opened  int := 0;
  n_resting int := 0;
  cand      record;
  fail      record;
  touched   boolean;
begin
  -- 1 · A rest window that has elapsed opens.
  for cand in
    select ba.id, ba.title, ba.scope_label, ba.unblocks_at
    from batch_activity ba
    where ba.master_batch_id = p_batch and ba.state = 'WAITING_TIME'
      and ba.unblocks_at is not null
  loop
    if not exists (
      select 1 from evaluate_gates(cand.id, 'exit') v
      where v.kind = 'DAY0_DURATION' and v.verdict = 'fail'
    ) then
      update batch_activity set state = 'READY', blocked_reason = null where id = cand.id;
      n_opened := n_opened + 1;

      insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                               after_state, reason)
      values (null, null, 'rest_released', 'batch_activity', cand.id::text,
              jsonb_build_object('unblocks_at', cand.unblocks_at, 'released_at', now()),
              cand.title || ' — ' || cand.scope_label
              || ': rest window elapsed on the server clock');
    end if;
  end loop;

  -- 2 · Anything still shut is re-evaluated against its OWN entry rules.
  for cand in
    select ba.id, ba.is_time_gate, ba.day0_duration_hr, ba.actual_start, ba.unblocks_at,
           ba.title, ba.scope_label, (ba.state = 'READY') as was_ready
    from batch_activity ba
    where ba.master_batch_id = p_batch
      and (ba.state = 'LOCKED'
           or (ba.state = 'WAITING_TIME' and ba.unblocks_at is null)
           -- 0072 · READY IS NOT A ONE-WAY DOOR.
           --
           -- This scan used to consider only activities that were already shut, so a gate could
           -- open and never close again. The laboratory case makes the consequence plain:
           --
           --     supervisor approves  -> BNK-B3-FILL becomes READY
           --     GM rejects           -> lab_decision seq 369 = 'rejected'
           --                             v_lab_approval_queue.latest_verdict = 'rejected'
           --                             BNK-B3-FILL is still READY
           --
           -- evaluate_gates was right the whole time: its LAB_APPROVED rule already reads the
           -- LATEST decision. Nothing ever asked it again. So the queue said rejected while
           -- production stood open, which is the one shape that is genuinely hard to explain
           -- afterwards.
           --
           -- READY only. An activity that is IN_PROGRESS or beyond represents work that has
           -- actually begun, and shutting that would rewrite what happened; the answer there is a
           -- deviation, not a demotion. Time gates are excluded because their path is
           -- LOCKED -> WAITING_TIME and re-entering it would restamp actual_start.
           or (ba.state = 'READY' and not ba.is_time_gate))
    order by ba.seq, ba.instance_no
  loop
    select v.reason, v.kind into fail
    from evaluate_gates(cand.id, 'entry') v
    where v.verdict = 'fail'
    order by v.ordering
    limit 1;

    if fail.reason is not null then
      -- Still shut, and it says why in the rule's own words. No event when it was already shut:
      -- nothing happened. But a READY activity closing again IS something happening, and the
      -- people who saw it open need to find out why it went away.
      update batch_activity
         set state = 'LOCKED', blocked_reason = fail.reason
       where id = cand.id and (state <> 'LOCKED' or coalesce(blocked_reason,'') <> fail.reason);

      if cand.was_ready then
        insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                                 before_state, after_state, reason)
        values (auth.uid(), public.current_app_role(), 'gate_closed', 'batch_activity',
                cand.id::text,
                jsonb_build_object('state', 'READY'),
                jsonb_build_object('state', 'LOCKED', 'kind', fail.kind),
                cand.title || ' — ' || coalesce(cand.scope_label, 'whole batch')
                  || ' was open and is shut again: ' || fail.reason);
      end if;
      continue;
    end if;

    if cand.is_time_gate then
      update batch_activity ba
         set state = 'WAITING_TIME',
             actual_start = coalesce(ba.actual_start, now()),
             unblocks_at = case
               when ba.day0_duration_hr is not null
                 then coalesce(ba.actual_start, now())
                      + make_interval(secs => (ba.day0_duration_hr * 3600)::int)
               else ba.unblocks_at end,
             blocked_reason = case
               when ba.day0_duration_hr is null then
                 'Rest duration has not been set for this batch'
                 || coalesce(' — ' || ba.tbd_marker || ' is unresolved', '')
               when ba.day0_duration_hr >= 1 then
                 'Resting — ' || round(ba.day0_duration_hr, 2)::text || ' h required'
               else
                 'Resting — ' || round(ba.day0_duration_hr * 60)::text || ' min required'
             end
       where ba.id = cand.id;
      n_resting := n_resting + 1;

      insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                               after_state, reason)
      select null, null, 'rest_started', 'batch_activity', cand.id::text,
             jsonb_build_object('unblocks_at', cur.unblocks_at,
                                'day0_duration_hr', cur.day0_duration_hr),
             cur.title || ' — ' || cur.scope_label || ': ' || coalesce(cur.blocked_reason, 'resting')
        from batch_activity cur where cur.id = cand.id;
    else
      update batch_activity set state = 'READY', blocked_reason = null where id = cand.id;
      n_opened := n_opened + 1;

      insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
      values (null, null, 'gate_opened', 'batch_activity', cand.id::text,
              cand.title || ' — ' || cand.scope_label || ': every entry gate is satisfied');
    end if;
  end loop;

  return query select n_opened, n_resting;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.open_lab_sample(p_activity uuid, p_checkpoint uuid, p_label text DEFAULT NULL::text, p_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba     batch_activity;
  cp     lab_checkpoint;
  at_    timestamptz;
  new_id uuid;
begin
  -- 0072 · WHO MAY COLLECT A SAMPLE.
  --
  -- There was no role check here at all. An OPERATOR could open a laboratory sample — measured,
  -- HTTP 200 — which every other laboratory entry point refuses. Sampling is laboratory work.
  perform public.assert_role(
    array['lab_tech', 'supervisor', 'manager', 'admin', 'gm']::app_role[], 'collect a lab sample');

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  select * into cp from lab_checkpoint where id = p_checkpoint;
  if not found then raise exception 'No such lab checkpoint: %', p_checkpoint; end if;

  -- 0072 · A CORRECT READING FILED AGAINST THE WRONG CHECKPOINT IS A WRONG READING.
  --
  -- The activity was checked, and the checkpoint was checked, but never the two together. So a
  -- sample for one activity could be filed at any checkpoint in the catalogue — and because
  -- request_lab_test freezes the specification band from the SAMPLE's checkpoint, the same
  -- moisture reading was then judged against whichever band was chosen:
  --
  --     bound checkpoint      TUNNEL_LOAD    72.5 .. 74
  --     unrelated checkpoint  COMPOST_OUT    65   .. 68
  --
  -- Nothing about the resulting row looks wrong. That is what makes it dangerous.
  --
  -- lab_checkpoint_activity already states which checkpoints each activity performs, and every one
  -- of the 41 laboratory activities in PROCESS-2026C carries a binding, so there is always
  -- something to check against. Where an activity genuinely has no binding the rule cannot be
  -- applied and the sample is allowed, rather than inventing a pairing that the process does not
  -- state.
  if exists (select 1 from lab_checkpoint_activity lca
              where lca.process_activity_id = ba.process_activity_id)
     and not exists (
       select 1 from lab_checkpoint_activity lca
        where lca.process_activity_id = ba.process_activity_id
          and lca.checkpoint_code = cp.code
          and lca.checkpoint_map  = cp.checkpoint_map)
  then
    raise exception
      '% is not a checkpoint of %. That activity samples at %. Filing a reading under another '
      'checkpoint would judge it against that checkpoint''s band.',
      cp.code, ba.title,
      (select string_agg(distinct lca.checkpoint_code, ', ' order by lca.checkpoint_code)
         from lab_checkpoint_activity lca
        where lca.process_activity_id = ba.process_activity_id)
      using errcode = 'check_violation';
  end if;

  -- Same rule as every other recorded actual: not in the future. Consistent with 0016/0017/0021
  -- rather than a second opinion about time.
  at_ := coalesce(p_at, now());
  if at_ > now() then
    raise exception 'A sample cannot be collected in the future (% is ahead of now)', at_
      using errcode = 'invalid_datetime_format';
  end if;

  insert into lab_sample (checkpoint_id, master_batch_id, batch_activity_id, scope_ref,
                          vessel_id, sample_ref_label, collected_at, collected_by)
  values (cp.id, ba.master_batch_id, ba.id, ba.scope_label,
          ba.destination_location_id, p_label, at_, auth.uid())
  returning id into new_id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'open_lab_sample', 'lab_sample', new_id::text,
          jsonb_build_object('checkpoint', cp.code, 'map', cp.checkpoint_map, 'activity', ba.title),
          'Sample collected at ' || cp.code || ' for ' || ba.title);
  return new_id;
end;
$function$
;

-- ── Assertions ───────────────────────────────────────────────────────────────

do $a$
begin
  if position('was_ready' in pg_get_functiondef('public.advance_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0072 failed: advance_batch does not re-evaluate READY activities';
  end if;
  if position('gate_closed' in pg_get_functiondef('public.advance_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0072 failed: advance_batch records no event when a gate shuts again';
  end if;
  if position('collect a lab sample' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0 then
    raise exception '0072 failed: open_lab_sample has no role check';
  end if;
  if position('is not a checkpoint of' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0 then
    raise exception '0072 failed: open_lab_sample does not check the checkpoint belongs to the activity';
  end if;

  -- What advance_batch already did must survive. A patch that quietly drops the rest-release or
  -- the time-gate branch would pass every check above and break the process.
  if position('rest_released' in pg_get_functiondef('public.advance_batch(uuid)'::regprocedure)) = 0
     or position('rest_started' in pg_get_functiondef('public.advance_batch(uuid)'::regprocedure)) = 0
     or position('WAITING_TIME' in pg_get_functiondef('public.advance_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0072 failed: advance_batch lost its rest handling';
  end if;
  if position('cannot be collected in the future' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0 then
    raise exception '0072 failed: open_lab_sample lost its future-time refusal';
  end if;

  -- IN_PROGRESS must never be demoted: that would rewrite work that actually happened.
  if position('ba.state = ''READY'' and not ba.is_time_gate' in
       pg_get_functiondef('public.advance_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0072 failed: the re-evaluation scope is not READY-and-not-a-time-gate';
  end if;

  raise notice '0072 · a rejection shuts the gate again, and a reading is judged against its own band';
end $a$;
