-- ─────────────────────────────────────────────────────────────────────────────
-- 0073 · Two more places where the answer was "yes" and the truth was "nothing happened".
--
-- Wave 2 of the adversarial pass, continued. Both of these are the shape 0071 fixed for
-- start_activity, found again elsewhere:
--
--   P1 · activate_batch on a CANCELLED batch returned HTTP 204 and wrote
--        'activate_batch / Baseline frozen' to the audit trail. Nothing changed - the update is
--        guarded by status = 'draft' and cancellation IS terminal, which was verified by measuring
--        the row rather than trusting the response. But the trail recorded a baseline freeze that
--        never occurred, which is a false record of the most load-bearing event in a batch's life.
--
--   P1 · open_lab_sample refused a collection time in the future and accepted one two days BEFORE
--        H0. A reading of material that had not arrived yet, on record, feeding a checkpoint.
--        correct_actual already refuses this; the rule simply was not applied here.
--
-- Re-activating an ALREADY ACTIVE batch deliberately stays a silent success: an admin whose phone
-- lost the response has to be able to try again.
--
-- Generated by scripts/break/_gen0073.mjs from the deployed bodies.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.activate_batch(p_batch_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  blockers   text;
  cur_status text;
begin
  perform public.assert_role(array['admin', 'gm']::app_role[], 'activate a batch');

  select string_agg(message, '; ') into blockers
  from public.validate_batch(p_batch_id) where severity = 'blocking';

  if blockers is not null then
    raise exception 'Cannot activate — %', left(blockers, 400) using errcode = 'check_violation';
  end if;

  -- 0073 · ACTIVATION EITHER HAPPENS OR IS REFUSED. IT NEVER PRETENDS.
  --
  -- The update below has always been guarded by `status = 'draft'`, so an active or cancelled
  -- batch was never touched - the state machine was right. But the audit row at the end of this
  -- function ran unconditionally, and the function returns void, so:
  --
  --     activate a CANCELLED batch  ->  HTTP 204, nothing changed,
  --                                     and 'activate_batch / Baseline frozen' in the trail
  --
  -- A trail that records a baseline freeze that did not happen is worse than a silent no-op,
  -- because it is evidence of something untrue. Same shape as start_activity in 0071.
  --
  -- Re-activating an ALREADY ACTIVE batch stays silent and successful: an admin whose phone lost
  -- the response needs to be able to try again. Re-activating a CANCELLED one is refused, because
  -- cancellation is terminal and the caller is asking for something that will not happen.
  update master_batch
     set status = 'active', activated_at = now(), activated_by = auth.uid()
   where id = p_batch_id and status = 'draft';

  if not found then
    select mb.status::text into cur_status from master_batch mb where mb.id = p_batch_id;

    if cur_status is null then
      raise exception 'No such batch: %', p_batch_id using errcode = 'no_data_found';
    end if;

    if cur_status = 'active' then
      return;                      -- already done; a retry, not an error
    end if;

    raise exception
      'This batch is %, so it cannot be activated. Cancellation is final — create a new batch '
      'rather than restarting this one.', cur_status
      using errcode = 'check_violation';
  end if;

  -- Whatever the gates say is available becomes available. Nothing else.
  perform public.advance_batch(p_batch_id);

  insert into notification (master_batch_id, to_role, kind, message, sent_by)
  select p_batch_id, ba.responsible_role, 'gate_opened', ba.title || ' is ready', auth.uid()
  from batch_activity ba
  where ba.master_batch_id = p_batch_id and ba.state = 'READY';

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'activate_batch', 'master_batch',
          p_batch_id::text, 'Baseline frozen');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.open_lab_sample(p_activity uuid, p_checkpoint uuid, p_label text DEFAULT NULL::text, p_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba     batch_activity;
  cp     lab_checkpoint;
  at_    timestamptz;
  h0_    timestamptz;
  new_id uuid;
begin
  -- 0072 · WHO MAY COLLECT A SAMPLE.
  --
  -- There was no role check here at all. An OPERATOR could open a laboratory sample — measured,
  -- HTTP 200 — which every other laboratory entry point refuses. Sampling is laboratory work.
  perform public.assert_role(
    array['lab_tech', 'supervisor', 'manager', 'admin', 'gm']::app_role[], 'collect a lab sample');

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  select * into cp from lab_checkpoint where id = p_checkpoint;
  if not found then raise exception 'No such lab checkpoint: %', p_checkpoint; end if;

  -- 0072 · A CORRECT READING FILED AGAINST THE WRONG CHECKPOINT IS A WRONG READING.
  --
  -- The activity was checked, and the checkpoint was checked, but never the two together. So a
  -- sample for one activity could be filed at any checkpoint in the catalogue — and because
  -- request_lab_test freezes the specification band from the SAMPLE's checkpoint, the same
  -- moisture reading was then judged against whichever band was chosen:
  --
  --     bound checkpoint      TUNNEL_LOAD    72.5 .. 74
  --     unrelated checkpoint  COMPOST_OUT    65   .. 68
  --
  -- Nothing about the resulting row looks wrong. That is what makes it dangerous.
  --
  -- lab_checkpoint_activity already states which checkpoints each activity performs, and every one
  -- of the 41 laboratory activities in PROCESS-2026C carries a binding, so there is always
  -- something to check against. Where an activity genuinely has no binding the rule cannot be
  -- applied and the sample is allowed, rather than inventing a pairing that the process does not
  -- state.
  if exists (select 1 from lab_checkpoint_activity lca
              where lca.process_activity_id = ba.process_activity_id)
     and not exists (
       select 1 from lab_checkpoint_activity lca
        where lca.process_activity_id = ba.process_activity_id
          and lca.checkpoint_code = cp.code
          and lca.checkpoint_map  = cp.checkpoint_map)
  then
    raise exception
      '% is not a checkpoint of %. That activity samples at %. Filing a reading under another '
      'checkpoint would judge it against that checkpoint''s band.',
      cp.code, ba.title,
      (select string_agg(distinct lca.checkpoint_code, ', ' order by lca.checkpoint_code)
         from lab_checkpoint_activity lca
        where lca.process_activity_id = ba.process_activity_id)
      using errcode = 'check_violation';
  end if;

  -- Same rule as every other recorded actual: not in the future. Consistent with 0016/0017/0021
  -- rather than a second opinion about time.
  at_ := coalesce(p_at, now());
  if at_ > now() then
    raise exception 'A sample cannot be collected in the future (% is ahead of now)', at_
      using errcode = 'invalid_datetime_format';
  end if;

  -- 0073 · NOR BEFORE THE BATCH EXISTED.
  --
  -- Only the future was refused, so a sample could be dated two days before H0 and accepted — a
  -- reading of material that had not been delivered yet, on record, feeding a checkpoint verdict.
  -- correct_actual already refuses exactly this ("the batch begins at X and nothing in it happened
  -- before that"); this is the same rule, applied where it was missing rather than a new opinion.
  --
  -- The incoming-material assay is deliberately NOT affected: it belongs before H0 by design, and
  -- it goes through open_prebatch_sample, which is a different function.
  select mb.start_at into h0_ from master_batch mb where mb.id = ba.master_batch_id;
  if h0_ is not null and at_ < h0_ then
    raise exception
      'A sample for % cannot be dated %: the batch begins at % and nothing in it happened before '
      'that. The incoming-material assay is the one that precedes H0, and it is recorded '
      'separately.', ba.title, at_, h0_
      using errcode = 'invalid_datetime_format';
  end if;

  insert into lab_sample (checkpoint_id, master_batch_id, batch_activity_id, scope_ref,
                          vessel_id, sample_ref_label, collected_at, collected_by)
  values (cp.id, ba.master_batch_id, ba.id, ba.scope_label,
          ba.destination_location_id, p_label, at_, auth.uid())
  returning id into new_id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'open_lab_sample', 'lab_sample', new_id::text,
          jsonb_build_object('checkpoint', cp.code, 'map', cp.checkpoint_map, 'activity', ba.title),
          'Sample collected at ' || cp.code || ' for ' || ba.title);
  return new_id;
end;
$function$
;

-- ── Assertions ───────────────────────────────────────────────────────────────

do $a$
begin
  if position('Cancellation is final' in pg_get_functiondef('public.activate_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0073 failed: activate_batch still pretends on a cancelled batch';
  end if;
  if position('return;                      -- already done' in
       pg_get_functiondef('public.activate_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0073 failed: activate_batch is no longer idempotent for an active batch';
  end if;
  if position('nothing in it happened before' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0 then
    raise exception '0073 failed: open_lab_sample accepts a sample dated before H0';
  end if;

  -- Everything these two already enforced must survive.
  if position('Cannot activate' in pg_get_functiondef('public.activate_batch(uuid)'::regprocedure)) = 0
     or position('validate_batch' in pg_get_functiondef('public.activate_batch(uuid)'::regprocedure)) = 0
     or position('advance_batch' in pg_get_functiondef('public.activate_batch(uuid)'::regprocedure)) = 0 then
    raise exception '0073 failed: activate_batch lost its validation or its gate evaluation';
  end if;
  if position('collect a lab sample' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0
     or position('is not a checkpoint of' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0
     or position('cannot be collected in the future' in pg_get_functiondef(
       'public.open_lab_sample(uuid,uuid,text,timestamptz)'::regprocedure)) = 0 then
    raise exception '0073 failed: open_lab_sample lost a guard 0072 added';
  end if;

  raise notice '0073 · activation is honest, and a sample cannot predate its own batch';
end $a$;
