-- ─────────────────────────────────────────────────────────────────────────────
-- 0097 · PROCESS-2026J v1 — PROCESS-2026I with TIME GATES (user rulings, 15 Sep 2026).
--
--   1 · FIELD WORK: the after photo and Finish wait for the SOP time from Start — the upper number
--       where the SOP gives a range (duration_target_max_hr). Every production task with a stated
--       duration gets an exit MIN_DURATION gate; its AFTER_PHOTO becomes capture_phase 'after_duration'.
--   2 · HOLDS: confirmed only when their SOP condition is met, exactly as the SOP states it:
--       plain rests by time; FIB-COND-2 temperature ≥58 °C OR 40 h; FIB-COND-1 ≥58 °C AND 60 h;
--       bunker Holding 1 ≥73 °C AND its hours; Holding 2 ≥70 °C AND its hours (hours = the process's
--       stated upper duration). The temperature is the hold's own "Temperature at confirmation" reading.
--   3 · LAB CHECKS are locked to their field step: an "after X" check opens when X has finished; a
--       "before X" check (and every GATE-kind check) opens when the step before X has finished, so it
--       can be done before X starts; every other check opens when X has started. Raw material (LAB-RM-01)
--       stays open: it is tested on arrival.
-- Everything else is copied unchanged from PROCESS-2026I. Needs 0096 (engine). Created as DRAFT.
-- Generated by build_0097.py.
-- ─────────────────────────────────────────────────────────────────────────────

do $$
begin
  if exists (select 1 from public.process_definition where code = 'PROCESS-2026J' and version = 1) then
    raise exception 'PROCESS-2026J v1 already exists; 0097 does not overwrite a process definition.';
  end if;
  if not exists (select 1 from public.process_definition where code = 'PROCESS-2026I' and version = 1) then
    raise exception '0097 needs PROCESS-2026I v1 as its base.';
  end if;
  if not exists (select 1 from pg_proc where proname = 'time_gate_status') then
    raise exception '0097 needs 0096 (time gate engine).';
  end if;
end $$;

insert into public.conflict_register (conflict_id, kind, severity, question, sources, ship_with_default, status) values
  ('SOP-C16', 'conflict', null,
   'May a supervisor or lab technician record the after photo or finish a task before its SOP time has passed?',
   'User 15 Sep 2026 ("there was supposed to be a time gate")',
   'No. After photo and Finish wait for the SOP time from Start (upper number of a range). Holds finish on their SOP condition (time, temperature OR/AND as written). Lab checks open with their field step: after X when X finished, before X when the step before X finished, otherwise when X started.',
   'decided')
on conflict (conflict_id) do nothing;

insert into public.process_definition (code, name, version, status, source_ref, anchor_day_label, total_days,
  envelope_confidence, envelope_hours, envelope_hour_source)
select 'PROCESS-2026J', 'Current factory process 15-09-2026 with time gates', 1, 'draft',
       e.source_ref || ' · time gates 15 Sep 2026: finish and after photo wait for the SOP time; holds on their SOP trigger; Lab checks with their field step',
       e.anchor_day_label, e.total_days, e.envelope_confidence, e.envelope_hours, e.envelope_hour_source
from public.process_definition e where e.code = 'PROCESS-2026I' and e.version = 1;

insert into public.process_activity (process_definition_id, code, label_template, material_role, stream, rel_day, seq,
  scope, cardinality_rule, duration_target_min_hr, duration_target_max_hr, duration_required_at_day0, is_time_gate,
  is_optional, default_enabled, golden_rule, source_ref, tbd_marker, responsible_role, lab_parameters, admin_question,
  day_span_label, standard_start_hour, standard_end_hour, standard_hour_source, is_pre_h0, pre_h0_offset,
  timing_confidence, is_hold, stage, instructions, skip_policy, parallel_group, notes, planning_unresolved)
select (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1), e.code, e.label_template, e.material_role, e.stream, e.rel_day, e.seq,
  e.scope, e.cardinality_rule, e.duration_target_min_hr, e.duration_target_max_hr,
  e.duration_required_at_day0, e.is_time_gate, e.is_optional, e.default_enabled, e.golden_rule,
  e.source_ref, e.tbd_marker, e.responsible_role, e.lab_parameters, e.admin_question,
  e.day_span_label, e.standard_start_hour, e.standard_end_hour, e.standard_hour_source, e.is_pre_h0, e.pre_h0_offset,
  e.timing_confidence, e.is_hold, e.stage, e.instructions, e.skip_policy, e.parallel_group, e.notes, e.planning_unresolved
from public.process_activity e
where e.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026I' and version = 1);

insert into public.activity_field (process_activity_id, key, label, datatype, unit, sop_value, sop_min, sop_max,
  sop_source_ref, conflict_id, day0_editable, day0_required, default_variance, operator_input, remarks_default, section,
  step_no, display_order)
select n.id, af.key, af.label, af.datatype, af.unit, af.sop_value, af.sop_min, af.sop_max,
  af.sop_source_ref, af.conflict_id, af.day0_editable, af.day0_required, af.default_variance, af.operator_input,
  af.remarks_default, af.section, af.step_no, af.display_order
from public.activity_field af
join public.process_activity e on e.id = af.process_activity_id
join public.process_activity n on n.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1) and n.code = e.code
where e.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026I' and version = 1);

-- photos: copied; a production task's after photo waits for the SOP time
insert into public.evidence_requirement (process_activity_id, key, label, media_kinds, min_count, max_count, is_required,
  gates_submission, capture_hint, ordering, capture_phase)
select n.id, er.key, er.label, er.media_kinds, er.min_count, er.max_count, er.is_required,
  er.gates_submission, er.capture_hint, er.ordering,
  case when er.key = 'AFTER_PHOTO' and coalesce(e.responsible_role::text, '') <> 'lab_tech'
            and not e.is_hold and e.duration_target_max_hr is not null
       then 'after_duration' else er.capture_phase end
from public.evidence_requirement er
join public.process_activity e on e.id = er.process_activity_id
join public.process_activity n on n.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1) and n.code = e.code
where e.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026I' and version = 1);

insert into public.gate_rule (process_activity_id, phase, kind, config, predecessor_binding, is_enabled,
  mapping_confidence, conflict_id, blocked_reason_template, ordering, is_protected)
select n.id, gr.phase, gr.kind, gr.config, gr.predecessor_binding, gr.is_enabled, gr.mapping_confidence, gr.conflict_id,
  gr.blocked_reason_template, gr.ordering, gr.is_protected
from public.gate_rule gr
join public.process_activity e on e.id = gr.process_activity_id
join public.process_activity n on n.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1) and n.code = e.code
where e.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026I' and version = 1);

-- 1 + 2 · the time gate on every production task and hold with a stated duration
insert into public.gate_rule (process_activity_id, phase, kind, config, blocked_reason_template, ordering, mapping_confidence)
select n.id, 'exit', 'MIN_DURATION',
  jsonb_build_object('hours', n.duration_target_max_hr,
                     'source', 'duration_target_max_hr (upper number) · user 15 Sep 2026')
  || case when t.code is null then '{}'::jsonb
          else jsonb_build_object('trigger', jsonb_build_object('field_key', t.field_key, 'min', t.min_value,
                                                                'join', t.join_kind, 'source', t.source)) end,
  '{time_gate}', 5, 'sop_direct'
from public.process_activity n
left join (values
  ('FIB-COND-1', 'temperature_c', 58, 'and', 'SOP: unload trigger ≥58 °C AND ≥60 h'),
  ('FIB-COND-2', 'temperature_c', 58, 'or', 'SOP: trigger ≥58 °C OR ≥40 h'),
  ('BNK-B1-HOLD-1', 'temperature_c', 73, 'and', 'SOP: reload trigger 73–74 °C + hours'),
  ('BNK-B2-HOLD-1', 'temperature_c', 73, 'and', 'SOP: reload trigger 73–74 °C + hours'),
  ('BNK-B3-HOLD-1', 'temperature_c', 73, 'and', 'SOP: reload trigger 73–74 °C + hours'),
  ('BNK-B1-HOLD-2', 'temperature_c', 70, 'and', 'SOP: unload trigger 70 °C + hours'),
  ('BNK-B2-HOLD-2', 'temperature_c', 70, 'and', 'SOP: unload trigger 70 °C + hours'),
  ('BNK-B3-HOLD-2', 'temperature_c', 70, 'and', 'SOP: unload trigger 70 °C + hours')
) t(code, field_key, min_value, join_kind, source) on t.code = n.code
where n.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1)
  and coalesce(n.responsible_role::text, '') <> 'lab_tech'
  and n.duration_target_max_hr is not null;

-- 3 · Lab checks locked to their field step
with lab(code, rel, x) as (values
  ('LAB-WET-01', 'after', 'FIB-WET-1'),
  ('LAB-WET-02', 'after', 'FIB-HOP-2'),
  ('LAB-BNK-PRE', 'before', 'FIB-BUNK-LOAD'),
  ('LAB-UNL-01', 'with', 'FIB-RELOAD-1'),
  ('LAB-HOP-PRE', 'before', 'FIB-RELOAD-1'),
  ('LAB-RLD-01', 'with', 'FIB-RELOAD-1'),
  ('LAB-CM-ARR', 'with', 'CM-WEIGH'),
  ('LAB-CM-USE', 'before', 'MIX-CM-ADD'),
  ('LAB-MOIST-DEC', 'with', 'FIB-MOIST-DEC'),
  ('LAB-PDY-WGH', 'with', 'STR-WEIGH'),
  ('LAB-PDY-S1', 'with', 'STR-SOAK-1'),
  ('LAB-PDY-S2', 'with', 'STR-SOAK-2'),
  ('LAB-PDY-S3', 'with', 'STR-SOAK-3'),
  ('LAB-PRE-T', 'after', 'YARD-FLIP'),
  ('LAB-T1-PRE-P1', 'before', 'TRN-P1-T1'),
  ('LAB-T1-PRE-P2', 'before', 'TRN-P2-T1'),
  ('LAB-T1-PRE-P3', 'before', 'TRN-P3-T1'),
  ('LAB-T1-PRE-P4', 'before', 'TRN-P4-T1'),
  ('LAB-T1-PRE-P5', 'before', 'TRN-P5-T1'),
  ('LAB-T1-PRE-P6', 'before', 'TRN-P6-T1'),
  ('LAB-T1-POST-P1', 'after', 'TRN-P1-T1'),
  ('LAB-T1-POST-P2', 'after', 'TRN-P2-T1'),
  ('LAB-T1-POST-P3', 'after', 'TRN-P3-T1'),
  ('LAB-T1-POST-P4', 'after', 'TRN-P4-T1'),
  ('LAB-T1-POST-P5', 'after', 'TRN-P5-T1'),
  ('LAB-T1-POST-P6', 'after', 'TRN-P6-T1'),
  ('LAB-BNK-LOAD-B1', 'before', 'BNK-B1-FILL'),
  ('LAB-BNK-LOAD-B2', 'before', 'BNK-B2-FILL'),
  ('LAB-BNK-LOAD-B3', 'before', 'BNK-B3-FILL'),
  ('LAB-RLD-UNL-B1', 'with', 'BNK-B1-RELOAD'),
  ('LAB-RLD-UNL-B2', 'with', 'BNK-B2-RELOAD'),
  ('LAB-RLD-UNL-B3', 'with', 'BNK-B3-RELOAD'),
  ('LAB-RLD-RE-B1', 'with', 'BNK-B1-RELOAD'),
  ('LAB-RLD-RE-B2', 'with', 'BNK-B2-RELOAD'),
  ('LAB-RLD-RE-B3', 'with', 'BNK-B3-RELOAD'),
  ('LAB-TUN-PRE', 'before', 'BNK-B1-TUN-LOAD'),
  ('LAB-TUN-LOAD-B1', 'before', 'BNK-B1-TUN-LOAD'),
  ('LAB-TUN-LOAD-B2', 'before', 'BNK-B2-TUN-LOAD'),
  ('LAB-TUN-LOAD-B3', 'before', 'BNK-B3-TUN-LOAD'),
  ('LAB-QC-FINAL', 'with', 'TUN-DISCHARGE-1')
),
x_pred as (
  select xa.code, gr.config->'activity_codes' as codes, gr.predecessor_binding
    from public.process_activity xa
    join public.gate_rule gr on gr.process_activity_id = xa.id and gr.phase = 'entry' and gr.kind = 'PREDECESSOR'
   where xa.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1)
)
insert into public.gate_rule (process_activity_id, phase, kind, config, predecessor_binding, blocked_reason_template,
  ordering, mapping_confidence)
select n.id, 'entry', 'PREDECESSOR',
  case lab.rel
    when 'after'  then jsonb_build_object('activity_codes', jsonb_build_array(lab.x), 'lab_relation', 'after', 'field_step', lab.x)
    when 'with'   then jsonb_build_object('activity_codes', jsonb_build_array(lab.x), 'when', 'started', 'lab_relation', 'with', 'field_step', lab.x)
    else jsonb_build_object('activity_codes', xp.codes, 'lab_relation', 'before', 'field_step', lab.x)
  end,
  case when lab.rel = 'before' then coalesce(xp.predecessor_binding, 'ALL_INSTANCES') else 'ALL_INSTANCES' end,
  case lab.rel
    when 'after' then 'Locked — this check opens when {predecessor_label} has finished.'
    when 'with'  then 'Locked — this check opens when {predecessor_label} starts.'
    else 'Locked — this check opens when {predecessor_label} has finished, before the next step starts.'
  end,
  10, 'dictated'
from lab
join public.process_activity n on n.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1) and n.code = lab.code
left join x_pred xp on xp.code = lab.x
where lab.rel <> 'before' or xp.codes is not null;

insert into public.lab_checkpoint_activity (checkpoint_map, checkpoint_code, process_activity_id, gates_activity_code)
select lca.checkpoint_map, lca.checkpoint_code, n.id, lca.gates_activity_code
from public.lab_checkpoint_activity lca
join public.process_activity e on e.id = lca.process_activity_id
join public.process_activity n on n.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1) and n.code = e.code
where e.process_definition_id = (select id from public.process_definition where code = 'PROCESS-2026I' and version = 1);

-- self-check
do $$
declare j uuid := (select id from public.process_definition where code = 'PROCESS-2026J' and version = 1); i uuid := (select id from public.process_definition where code = 'PROCESS-2026I' and version = 1); n int; m int;
begin
  select count(*) into n from public.process_activity where process_definition_id = j;
  if n <> 113 then raise exception '0097: expected 113 activities, found %', n; end if;
  select count(*) into n from public.gate_rule gr join public.process_activity pa on pa.id = gr.process_activity_id
   where pa.process_definition_id = j and gr.kind = 'MIN_DURATION';
  select count(*) into m from public.process_activity where process_definition_id = j
     and coalesce(responsible_role::text, '') <> 'lab_tech' and duration_target_max_hr is not null;
  if n <> m or n < 60 then raise exception '0097: time gates % for % timed tasks', n, m; end if;
  select count(*) into n from public.gate_rule gr join public.process_activity pa on pa.id = gr.process_activity_id
   where pa.process_definition_id = j and gr.kind = 'MIN_DURATION' and gr.config ? 'trigger';
  if n <> 8 then raise exception '0097: expected 8 temperature triggers, found %', n; end if;
  select count(*) into n from public.gate_rule gr join public.process_activity pa on pa.id = gr.process_activity_id
   where pa.process_definition_id = j and pa.responsible_role::text = 'lab_tech' and gr.phase = 'entry';
  if n <> 40 then raise exception '0097: expected 40 Lab entry gates, found %', n; end if;
  select count(*) into n from public.evidence_requirement er join public.process_activity pa on pa.id = er.process_activity_id
   where pa.process_definition_id = j and er.capture_phase = 'after_duration';
  select count(*) into m from public.evidence_requirement er join public.process_activity pa on pa.id = er.process_activity_id
   where pa.process_definition_id = j and er.key = 'AFTER_PHOTO' and pa.responsible_role::text <> 'lab_tech' and pa.duration_target_max_hr is not null;
  if n <> m or n = 0 then raise exception '0097: after_duration photos % of %', n, m; end if;
  select count(*) into n from public.activity_field af join public.process_activity pa on pa.id = af.process_activity_id
   where pa.process_definition_id = j and af.key = 'temperature_c' and pa.code in ('FIB-COND-1', 'FIB-COND-2', 'BNK-B1-HOLD-1', 'BNK-B2-HOLD-1', 'BNK-B3-HOLD-1', 'BNK-B1-HOLD-2', 'BNK-B2-HOLD-2', 'BNK-B3-HOLD-2');
  if n <> 8 then raise exception '0097: every triggered hold needs its temperature reading, found %', n; end if;
  select count(*) into n from public.lab_checkpoint_activity lca join public.process_activity pa on pa.id = lca.process_activity_id where pa.process_definition_id = j;
  if n <> 41 then raise exception '0097: expected 41 lab bindings, found %', n; end if;
end $$;

notify pgrst, 'reload schema';
