-- ─────────────────────────────────────────────────────────────────────────────
-- 0100 · LATE WORK NEEDS A TICKET; GRANTED TIME MOVES THE LATER STEPS (user, 15 Sep 2026).
--   "bunker unloading was supposed to be done at 12, but he did not upload the after photo, now he will ask
--    for the extension … he added 1 hour, other processes will move by an hour … variance of actual and extended"
-- Rulings: deadline = the DAY-PLAN time; 30 minutes grace; while a ticket waits for Admin the task stays
-- blocked (rejected = still blocked, raise a new one); Lab checks are due with their field step.
--
--   · extended end = planned_end_at + every approved ticket's hours on this task AND on every step upstream of
--     it (the entry-rule chain). A Lab check uses its field step's extended end, plus its own tickets.
--   · due = extended end + extension_policy.late_grace_min (Admin-configurable, 30).
--   · Past due, submit_activity (Finish / Confirm / Lab submit) and bind_evidence (after photo, Lab photos) are
--     refused with the due time and "raise a late ticket". Holds (confirmed on their condition), DEMO / TEST
--     batches, and tasks with no planned time are not blocked.
--   · v_activity_schedule: planned, shift, extended, due, actual, and the variance of actual against the plan
--     and against the extended time, per task.
-- Generated by build_0100.py. Rollback: run pre_0100__functions.sql; drop view v_activity_schedule;
--   drop function activity_due, late_block_reason; alter table extension_policy drop column late_grace_min.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.extension_policy add column if not exists late_grace_min integer not null default 30
  check (late_grace_min >= 0 and late_grace_min <= 720);

create or replace function public.activity_due(p_activity uuid)
returns table (target_activity_id uuid, planned_end_at timestamptz, shift_hr numeric, extended_end_at timestamptz,
               due_at timestamptz, open_ticket boolean, applies boolean)
language plpgsql stable security definer set search_path = public
as $fn$
declare
  ba     batch_activity;
  tgt    batch_activity;
  v_grace int;
  v_shift numeric;
  v_open boolean;
  v_applies boolean;
begin
  select * into ba from batch_activity where id = p_activity;
  if not found then return; end if;

  if coalesce(ba.responsible_role::text, '') = 'lab_tech' then
    select x.* into tgt
      from lab_checkpoint_activity lca
      join batch_activity x on x.master_batch_id = ba.master_batch_id and x.code = lca.gates_activity_code
     where lca.process_activity_id = ba.process_activity_id
     order by x.instance_no limit 1;
    if not found then tgt := ba; end if;
  else
    tgt := ba;
  end if;

  with recursive anc(id) as (
    select tgt.id
    union
    select pred.id
      from anc
      join batch_activity cur on cur.id = anc.id
      join gate_rule g on g.process_activity_id = cur.process_activity_id
                      and g.phase = 'entry' and g.kind = 'PREDECESSOR' and g.is_enabled
      join batch_activity pred
        on pred.master_batch_id = cur.master_batch_id
       and pred.code in (select jsonb_array_elements_text(g.config->'activity_codes'))
       and (coalesce(g.predecessor_binding, 'ALL_INSTANCES') <> 'SAME_SCOPE_INSTANCE' or pred.instance_no = cur.instance_no)
       and coalesce(pred.responsible_role::text, '') <> 'lab_tech'
  )
  select coalesce(sum(er.approved_extension_hr), 0) into v_shift
    from extension_request er
   where (er.batch_activity_id in (select id from anc) or er.batch_activity_id = ba.id)
     and public.extension_is_effective(er.status);

  v_open := exists (select 1 from extension_request er where er.batch_activity_id = ba.id and er.status = 'REQUESTED');
  select p.late_grace_min into v_grace from extension_policy p where p.id;
  v_grace := coalesce(v_grace, 30);

  v_applies := not ba.is_hold
    and not public.batch_clock_waived(ba.master_batch_id)
    and not ba.before_tracking
    and ba.state::text in ('READY', 'IN_PROGRESS', 'RETURNED')
    and tgt.planned_end_at is not null;

  return query select tgt.id, tgt.planned_end_at, v_shift,
    tgt.planned_end_at + make_interval(secs => (v_shift * 3600)::int),
    tgt.planned_end_at + make_interval(secs => (v_shift * 3600)::int) + make_interval(mins => v_grace),
    v_open, v_applies;
end;
$fn$;
revoke all on function public.activity_due(uuid) from public;
grant execute on function public.activity_due(uuid) to authenticated;

create or replace function public.late_block_reason(p_activity uuid)
returns text language plpgsql stable security definer set search_path = public
as $fn$
declare d record; tz text; lbl text;
begin
  select * into d from public.activity_due(p_activity);
  if not found or not d.applies or now() <= d.due_at then return null; end if;
  select fc.timezone into tz from factory_clock fc limit 1;
  tz := coalesce(tz, 'Asia/Kolkata');
  lbl := to_char(d.extended_end_at at time zone tz, 'DD Mon HH24:MI')
         || case when d.shift_hr > 0 then ' (planned ' || to_char(d.planned_end_at at time zone tz, 'HH24:MI')
                 || ' + ' || trim(trailing '.' from trim(to_char(d.shift_hr, 'FM999990.99'))) || ' h granted)' else '' end;
  if d.open_ticket then
    return 'This task was due ' || lbl || '. Your late ticket is waiting for Admin; it can be finished once more time is granted.';
  end if;
  return 'This task was due ' || lbl || '. Raise a late ticket to ask Admin for more time before taking the photo or finishing.';
end;
$fn$;
revoke all on function public.late_block_reason(uuid) from public;
grant execute on function public.late_block_reason(uuid) to authenticated;

CREATE OR REPLACE FUNCTION public.submit_activity(p_activity uuid, p_values jsonb DEFAULT '{}'::jsonb, p_remarks text DEFAULT NULL::text, p_actual_start timestamp with time zone DEFAULT NULL::timestamp with time zone, p_actual_end timestamp with time zone DEFAULT NULL::timestamp with time zone, p_skipped jsonb DEFAULT '{}'::jsonb)
 RETURNS TABLE(new_state text, out_of_range integer, outstanding_evidence text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba          batch_activity;
  b           master_batch;
  k           text;
  v           text;
  fld         batch_activity_value;
  flag        text;
  target      numeric;
  target_src  text;
  dev_count   int := 0;
  reasons     text := '';
  outstanding text;
  entered_at  timestamptz := now();
  h0          timestamptz;
  eff_start   timestamptz;
  eff_end     timestamptz;
  -- Each failing field, captured so the deviation rows can be written after the state settles.
  fails       jsonb := '[]'::jsonb;
  f           jsonb;
  n_samples   int;
  n_tests     int;
  n_pending   int;
  sk_key      text;
  sk_reason   text;
  missing_fields text;
  v_hold_start   timestamptz;
  v_timed        boolean;
  v_time_reason  text;
  v_late         text;
begin
  perform public.assert_role(array['operator', 'supervisor', 'lab_tech']::app_role[], 'submit an activity');
  -- 0091 · the same role boundary as starting: production for supervisors, Lab work for the laboratory.
  perform public.assert_may_execute(p_activity, 'submit an activity');

  -- 0071 · LOCK THE ROW, THEN DECIDE.
  -- The state check below is a read followed by a write. Five phones submitting at once all read
  -- IN_PROGRESS, and two of them got through before either had committed — one completion, one
  -- actual_end, but two 'submit_activity' rows in the trail. Taking the row lock here serialises
  -- them, so the second caller re-reads a COMPLETED row and receives the refusal that already
  -- exists a few lines below.
  select * into ba from batch_activity where id = p_activity for update;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  -- 0050 · An operator records work by doing it, not by typing when it happened.
  if (p_actual_start is not null or p_actual_end is not null)
     and coalesce(public.current_app_role()::text, '') = 'operator' then
    raise exception
      'An operator may not state a start or end time. Use start_activity and '
      'complete_activity and the server records when it happened. If a time has to be '
      'entered after the fact, a supervisor does it.'
      using errcode = 'insufficient_privilege';
  end if;


  -- 0096 · A TIMED TASK IS TIMED BY THE SERVER. Its start is the Start tap and its end is the Finish
  -- tap; a stated time would let the SOP duration be written instead of waited for.
  v_timed := exists (select 1 from gate_rule g
                      where g.process_activity_id = ba.process_activity_id
                        and g.phase = 'exit' and g.kind = 'MIN_DURATION' and g.is_enabled);
  if v_timed and (p_actual_start is not null or p_actual_end is not null) then
    raise exception '% is timed by the server: it starts when Start is tapped and finishes when Finish is tapped. A start or finish time cannot be typed in.', ba.title
      using errcode = 'insufficient_privilege';
  end if;
  if v_timed and not ba.is_hold and ba.actual_start is null then
    raise exception '% has not been started, so it cannot be finished. Tap Start first; the server records when it began.', ba.title
      using errcode = 'check_violation';
  end if;

  select * into b from master_batch where id = ba.master_batch_id;
  if b.status <> 'active' then
    raise exception 'Batch % is % — activate it before recording work', b.code, b.status;
  end if;
  if ba.state not in ('READY','IN_PROGRESS','RETURNED') then
    raise exception '% is %, so it cannot be submitted', ba.title, ba.state;
  end if;

  -- 0080 · G03 · A LAB ACTIVITY COMPLETES ONLY WITH ITS PACKAGE.
  -- A sample on record for this activity, at least one test requested on it, and a current result
  -- for every live test. Evidence is still enforced by the EVIDENCE_COMPLETE gate below. Pre-H0
  -- checks record their sample against the batch before any activity exists, so for those the
  -- sample is matched by the checkpoint the activity is bound to.
  if ba.responsible_role = 'lab_tech' then
    select count(distinct s.id),
           count(t.id) filter (where t.state not in ('superseded','cancelled')),
           count(t.id) filter (where t.state not in ('superseded','cancelled')
                                 and not exists (select 1 from lab_result r
                                                  where r.test_id = t.id
                                                    and r.superseded_by_result_id is null))
      into n_samples, n_tests, n_pending
      from lab_sample s
      left join lab_test t on t.sample_id = s.id
     where s.master_batch_id = ba.master_batch_id
       and (s.batch_activity_id = ba.id
            or (ba.is_pre_h0 and s.batch_activity_id is null and exists (
                  select 1 from lab_checkpoint lc
                    join lab_checkpoint_activity lca
                      on lca.checkpoint_code = lc.code and lca.checkpoint_map = lc.checkpoint_map
                   where lc.id = s.checkpoint_id
                     and lca.process_activity_id = ba.process_activity_id)));

    if n_samples = 0 then
      raise exception '% cannot be submitted: no sample is on record for it. Take the sample first.', ba.title
        using errcode = 'check_violation';
    end if;
    if n_tests = 0 then
      raise exception '% cannot be submitted: its sample has no readings requested. Record the readings first.', ba.title
        using errcode = 'check_violation';
    end if;
    if n_pending > 0 then
      raise exception '% cannot be submitted: % reading(s) still have no result.', ba.title, n_pending
        using errcode = 'check_violation';
    end if;
  end if;

  -- 0071 · AN OPERATOR CANNOT FINISH WHAT THEY NEVER STARTED.
  --
  -- Submitting from READY is deliberate and stays: a supervisor recording a paper slip after the
  -- fact has no start_activity call to lean on. But for an OPERATOR it produced a quiet lie. One
  -- stray tap on Finish stamped actual_start = now() for work that never began, and
  -- fn_actual_is_append_only then makes that stamp permanent — there is no un-happen, by design.
  -- So the mistake is unrecoverable, which is the wrong price for a mis-tap on a factory phone.
  --
  -- The refusal names the fix, because the operator's own screen has the button.
  if ba.actual_start is null
     and coalesce(public.current_app_role()::text, '') = 'operator' then
    raise exception
      '% has not been started, so it cannot be finished. Tap Start on the task first — the server '
      'records when it began.', ba.title
      using errcode = 'check_violation';
  end if;

  -- 0081 · A READING IS RECORDED, OR SKIPPED WITH A REASON — NEVER BOTH, NEVER SILENTLY.
  -- Validated before anything is written, so a refusal leaves every row as it was.
  if p_skipped is not null and jsonb_typeof(p_skipped) <> 'object' then
    raise exception 'Skipped readings must be given as field key → reason.';
  end if;
  for sk_key, sk_reason in select * from jsonb_each_text(coalesce(p_skipped, '{}'::jsonb)) loop
    select * into fld from batch_activity_value
     where batch_activity_id = p_activity and field_key = sk_key;
    if not found then
      raise exception '% has no reading named %', ba.title, sk_key;
    end if;
    if coalesce(trim(sk_reason), '') = '' then
      raise exception 'Skipping % on % needs a reason. Say why it was not recorded.', fld.label, ba.title
        using errcode = 'check_violation';
    end if;
    if nullif(trim(coalesce(p_values->>sk_key, '')), '') is not null then
      raise exception '% was both recorded and skipped. Record it or skip it, not both.', fld.label
        using errcode = 'check_violation';
    end if;
    if nullif(trim(coalesce(fld.actual_value, '')), '') is not null then
      raise exception '% is already recorded as %, so it cannot be skipped.', fld.label, fld.actual_value
        using errcode = 'check_violation';
    end if;
  end loop;
  for k, v in select * from jsonb_each_text(p_values) loop
    select * into fld from batch_activity_value
     where batch_activity_id = p_activity and field_key = k;
    continue when not found;
    if fld.datatype = 'numeric' and nullif(trim(v), '') is not null and v !~ '^-?[0-9]+(\.[0-9]+)?$' then
      raise exception '% must be a number; "%" was entered.', fld.label, v
        using errcode = 'invalid_text_representation';
    end if;
    if fld.datatype = 'check' and v not in ('true', 'false') then
      raise exception '% is a checklist item: it is ticked (true) or not (false); "%" was sent.', fld.label, v
        using errcode = 'invalid_text_representation';
    end if;
    -- 0091 · a controlled choice accepts only its stated options (sop_value, '|'-separated).
    if fld.datatype = 'choice' and nullif(trim(v), '') is not null
       and not (trim(v) = any (string_to_array(coalesce(fld.sop_value, ''), '|'))) then
      raise exception '% must be one of: %. "%" was entered.', fld.label, replace(coalesce(fld.sop_value, ''), '|', ', '), v
        using errcode = 'invalid_text_representation';
    end if;
  end loop;

  -- ── Recorded actuals are validated BEFORE anything is written ─────────────
  -- Carried unchanged from 0016. A refusal must leave the row exactly as it was, and a refusal an
  -- operator cannot act on is barely better than a silent one — so every message names the
  -- activity and the value it rejected.

  if p_actual_start is not null and p_actual_start > entered_at then
    raise exception
      'Cannot record a start of % for %: that is in the future. An actual is something that has '
      'already happened.', p_actual_start, ba.title
      using errcode = 'invalid_datetime_format';
  end if;

  if p_actual_end is not null and p_actual_end > entered_at then
    raise exception
      'Cannot record an end of % for %: that is in the future. An actual is something that has '
      'already happened.', p_actual_end, ba.title
      using errcode = 'invalid_datetime_format';
  end if;

  -- The EFFECTIVE pair, so a stated end earlier than an already-recorded start is refused too —
  -- start_activity may have written actual_start when the operator opened the card.
  -- 0082 · E-2 · A PASSIVE HOLD BEGINS WHEN THE STEP BEFORE IT FINISHED — the latest actual finish
  -- among the activities its entry PREDECESSOR rule(s) name. Never the confirmation time: with no
  -- finish on record the start stays unknown.
  if ba.is_hold then
    select max(pb.actual_end) into v_hold_start
      from gate_rule g
      join batch_activity pb
        on pb.master_batch_id = ba.master_batch_id
       and pb.code in (select jsonb_array_elements_text(g.config->'activity_codes'))
       and (coalesce(g.predecessor_binding, 'ALL_INSTANCES') <> 'SAME_SCOPE_INSTANCE'
            or pb.instance_no = ba.instance_no)
     where g.process_activity_id = ba.process_activity_id
       and g.phase = 'entry' and g.kind = 'PREDECESSOR' and g.is_enabled
       and pb.actual_end is not null;
  end if;

  eff_start := coalesce(p_actual_start, ba.actual_start, v_hold_start);
  eff_end   := coalesce(p_actual_end, ba.actual_end);

  if eff_start is not null and eff_end is not null and eff_end < eff_start then
    raise exception
      'Cannot record % ending at % when it started at %: work does not end before it begins.',
      ba.title, eff_end, eff_start
      using errcode = 'invalid_datetime_format';
  end if;

  -- NEW in B2 · a STATED actual may not precede H0. `batchHour()` already throws on it —
  -- "nothing in a batch happens before H0" — so the server agrees with the domain function
  -- rather than accepting what the client would refuse to render.
  --
  -- SCOPED TO WHAT THE SUBMITTER STATES, deliberately. Applying it to the `now()` default would
  -- also refuse a live recording on a batch whose `start_at` is still in the future — and that
  -- situation is reachable today: `activate_batch` does not require H0 to have passed, and
  -- `start_activity` stamps `now()` with no H0 check, so an activity can already carry an
  -- `actual_start` a month before its own batch began. Refusing at submit would strand an
  -- operator over a value they did not state.
  --
  -- That incoherence is REAL and PRE-EXISTING, and it is registered as TBD-52 rather than
  -- resolved here: whether "active" should mean "started" is a factory question, and answering
  -- it inside a deviations migration would be the wrong place and the wrong authority.
  h0 := b.start_at;
  if h0 is not null and p_actual_start is not null and p_actual_start < h0 then
    raise exception
      'Cannot record % starting at %: the batch begins at % and nothing in it happens before '
      'that.', ba.title, p_actual_start, h0
      using errcode = 'invalid_datetime_format';
  end if;
  if h0 is not null and p_actual_end is not null and p_actual_end < h0 then
    raise exception
      'Cannot record % ending at %: the batch begins at % and nothing in it happens before '
      'that.', ba.title, p_actual_end, h0
      using errcode = 'invalid_datetime_format';
  end if;

  for k, v in select * from jsonb_each_text(p_values) loop
    select * into fld from batch_activity_value
     where batch_activity_id = p_activity and field_key = k;
    continue when not found;

    flag := 'not_applicable';

    if v ~ '^-?[0-9]+(\.[0-9]+)?$' then
      target := null;
      target_src := null;

      if fld.day0_value ~ '^-?[0-9]+(\.[0-9]+)?$' then
        target := fld.day0_value::numeric;
        target_src := 'the Day-0 plan';
      elsif ba.planned_qty_mt is not null and k like '%qty%' then
        target := ba.planned_qty_mt;
        target_src := 'the Day-0 plan';
      end if;

      if fld.sop_min is not null or fld.sop_max is not null then
        if (fld.sop_min is not null and v::numeric < fld.sop_min)
           or (fld.sop_max is not null and v::numeric > fld.sop_max) then
          flag := 'out_of_range';
          dev_count := dev_count + 1;
          reasons := reasons || fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                     || ' outside the SOP band ' || coalesce(fld.sop_min::text,'')
                     || '–' || coalesce(fld.sop_max::text,'') || '; ';
          fails := fails || jsonb_build_object(
            'kind', 'VALUE_OUT_OF_SOP',
            'summary', fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                       || ' is outside the SOP band '
                       || coalesce(fld.sop_min::text,'') || '–' || coalesce(fld.sop_max::text,''),
            'detail', jsonb_build_object(
              'field_key', k, 'label', fld.label, 'value', v, 'unit', fld.unit,
              'sop_min', fld.sop_min, 'sop_max', fld.sop_max,
              'sop_source_ref', fld.sop_source_ref, 'conflict_id', fld.conflict_id,
              'day0_value', fld.day0_value));
        else
          flag := 'in_range';
        end if;

      elsif target is not null and target > 0 then
        if abs(v::numeric - target) / target > 0.10 then
          flag := 'out_of_range';
          dev_count := dev_count + 1;
          reasons := reasons || fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                     || ' against ' || target || coalesce(' ' || fld.unit,'')
                     || ' in ' || target_src || ' ('
                     || case when v::numeric > target then '+' else '' end
                     || round(v::numeric - target, 2) || '); ';
          fails := fails || jsonb_build_object(
            'kind', 'VALUE_OFF_DAY0_TARGET',
            'summary', fld.label || ' ' || v || coalesce(' ' || fld.unit,'')
                       || ' against ' || target || coalesce(' ' || fld.unit,'')
                       || ' planned at Day 0 ('
                       || case when v::numeric > target then '+' else '' end
                       || round(v::numeric - target, 2) || ')',
            'detail', jsonb_build_object(
              'field_key', k, 'label', fld.label, 'value', v, 'unit', fld.unit,
              'target', target, 'target_source', target_src,
              'tolerance_pct', 10, 'conflict_id', fld.conflict_id,
              -- No SOP band exists here. Saying so is information: docs/LAB_MODEL.md §9.
              'sop_source_ref', fld.sop_source_ref));
        else
          flag := 'in_range';
        end if;
      end if;
    end if;

    update batch_activity_value
       set actual_value = v,
           actual_recorded_at = entered_at,
           actual_recorded_by = auth.uid(),
           variance_flag = flag,
           remarks = coalesce(nullif(p_remarks,''), remarks),
           -- 0081 · a value recorded now replaces an earlier skip; the skip stays in the audit trail.
           skip_reason = case when nullif(trim(v), '') is not null then null else skip_reason end,
           skipped_by  = case when nullif(trim(v), '') is not null then null else skipped_by end,
           skipped_at  = case when nullif(trim(v), '') is not null then null else skipped_at end
     where id = fld.id;
  end loop;

  -- 0081 · skips, each with its reason, its person and the server's time. Flagged, never silent.
  for sk_key, sk_reason in select * from jsonb_each_text(coalesce(p_skipped, '{}'::jsonb)) loop
    update batch_activity_value
       set skip_reason = trim(sk_reason),
           skipped_by = auth.uid(),
           skipped_at = entered_at,
           variance_flag = 'skipped',
           remarks = coalesce(nullif(p_remarks,''), remarks)
     where batch_activity_id = p_activity and field_key = sk_key;
  end loop;

  -- 0081 · required readings and checklist items. Lab work is exempt: its readings are lab results,
  -- held by the package rule (G03) above.
  if coalesce(ba.responsible_role::text, '') <> 'lab_tech' then
    select string_agg(bav.label, ', ' order by bav.display_order, bav.label) into missing_fields
      from batch_activity_value bav
     where bav.batch_activity_id = p_activity
       and bav.operator_input = 'required'
       and bav.skip_reason is null
       and case when bav.datatype = 'check' then coalesce(bav.actual_value, '') <> 'true'
                else nullif(trim(coalesce(bav.actual_value, '')), '') is null end;
  end if;

  -- 0100 · LATE WORK NEEDS AN APPROVED TICKET. Past its due time (day plan + granted hours + grace) the
  -- task cannot be finished until Admin grants more time.
  v_late := public.late_block_reason(p_activity);
  if v_late is not null then
    raise exception '%', v_late using errcode = 'check_violation';
  end if;

  -- 0096 · THE TIME GATE, judged after this submission's readings are in place (a temperature trigger
  -- reads them). A refusal undoes the whole call, readings included.
  if v_timed then
    select gv.reason into v_time_reason
      from public.evaluate_gates(p_activity, 'exit') gv
     where gv.kind = 'MIN_DURATION' and gv.verdict = 'fail'
     order by gv.ordering limit 1;
    if v_time_reason is not null then
      raise exception '%', v_time_reason using errcode = 'check_violation';
    end if;
  end if;

  select gv.reason into outstanding
  from public.evaluate_gates(p_activity, 'exit') gv
  where gv.kind = 'EVIDENCE_COMPLETE' and gv.verdict = 'fail'
  order by gv.ordering
  limit 1;

  if missing_fields is not null then
    outstanding := concat_ws(' · ', 'Record or skip with a reason: ' || missing_fields, outstanding);
  end if;

  if outstanding is not null then
    update batch_activity
       set state = 'IN_PROGRESS',
           actual_start = coalesce(actual_start, p_actual_start,
                                  case when ba.is_hold then v_hold_start else entered_at end),
           actual_end = coalesce(actual_end, p_actual_end),
           actual_recorded_at = entered_at,
           blocked_reason = null
     where id = p_activity;

    insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                             after_state, reason)
    values (auth.uid(), public.current_app_role(),
            case when missing_fields is not null then 'submit_blocked_on_readings'
                 else 'submit_blocked_on_evidence' end,
            'batch_activity', p_activity::text,
            jsonb_build_object('actual_start', p_actual_start, 'actual_end', p_actual_end,
                               'recorded_at', entered_at),
            outstanding);

    return query select 'IN_PROGRESS'::text, dev_count, outstanding;
    return;
  end if;

  update batch_activity
     set state = case when dev_count > 0 then 'DEVIATION'::activity_state
                      else 'COMPLETED'::activity_state end,
         actual_start = coalesce(actual_start, p_actual_start,
                                  case when ba.is_hold then v_hold_start else entered_at end),
         actual_end = coalesce(actual_end, p_actual_end, entered_at),
         actual_recorded_at = entered_at,
         submitted_at = entered_at,
         submitted_by = auth.uid(),
         blocked_reason = case when dev_count > 0
           then rtrim(reasons, '; ') || ' — held for supervisor review' end
   where id = p_activity;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id,
                           after_state, reason)
  select auth.uid(), public.current_app_role(), 'submit_activity', 'batch_activity',
         p_activity::text,
         jsonb_build_object(
           'actual_start', cur.actual_start,
           'actual_end', cur.actual_end,
           'recorded_at', cur.actual_recorded_at,
           'duration_actual_min', cur.duration_actual_min,
           'variance_minutes', cur.variance_minutes,
           'skipped', coalesce(p_skipped, '{}'::jsonb),
           'stated_by_submitter', (p_actual_start is not null or p_actual_end is not null))
         || case when ba.is_hold then jsonb_build_object('hold_start_source',
              case when p_actual_start is not null then 'stated'
                   when ba.actual_start is not null then 'already_recorded'
                   when v_hold_start is not null then 'predecessor_actual_end'
                   else 'unknown' end)
            else '{}'::jsonb end,
         case when dev_count > 0 then 'DEVIATION · ' || rtrim(reasons,'; ')
              else coalesce(nullif(p_remarks,''), 'submitted') end
    from batch_activity cur where cur.id = p_activity;

  -- ── B2 · every failing field becomes a record someone can act on ──────────────
  -- One row per failing condition, not one per submission: §3.1 waives "one failing condition"
  -- at a time, so a supervisor must be able to accept one and refuse another.
  for f in select * from jsonb_array_elements(fails) loop
    insert into deviation (master_batch_id, batch_activity_id, kind, summary, detail,
                           raised_by, raised_by_role)
    values (ba.master_batch_id, p_activity, (f->>'kind')::deviation_kind,
            f->>'summary', f->'detail', auth.uid(), public.current_app_role());
  end loop;

  if dev_count = 0 then
    perform public.advance_batch(ba.master_batch_id);
  else
    update batch_activity nxt
       set state = 'BLOCKED',
           blocked_reason = 'Blocked — ' || ba.title || ' (' || ba.scope_label
                            || ') is in deviation: ' || rtrim(reasons, '; ')
     where nxt.master_batch_id = ba.master_batch_id
       and nxt.stream = ba.stream
       and nxt.seq > ba.seq
       and nxt.state in ('LOCKED','READY','WAITING_TIME')
       and nxt.seq = (
         select min(n2.seq) from batch_activity n2
         where n2.master_batch_id = ba.master_batch_id
           and n2.stream = ba.stream
           and n2.seq > ba.seq
           and n2.state in ('LOCKED','READY','WAITING_TIME'));
  end if;

  return query
    select (select state::text from batch_activity where id = p_activity), dev_count, null::text;
end;
$function$;

CREATE OR REPLACE FUNCTION public.bind_evidence(p_activity uuid, p_requirement_key text, p_storage_path text, p_media_kind text DEFAULT 'photo'::text, p_supersedes uuid DEFAULT NULL::uuid, p_supersede_reason text DEFAULT NULL::text)
 RETURNS TABLE(media_id uuid, requirement_key text, satisfied_count integer, min_count integer, uploaded_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba      batch_activity;
  req     batch_activity_evidence_req;
  obj     record;
  segs    text[];
  new_id  uuid;
  live    int;
  tg      record;
begin
  if auth.uid() is null then
    raise exception 'bind_evidence needs a signed-in user — the uploader is taken from the JWT, never from a parameter'
      using errcode = 'insufficient_privilege';
  end if;

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  -- 5 · entitlement first, so an unauthorised caller learns nothing about the rest.
  if not public.can_capture_for_activity(p_activity) then
    raise exception
      'Not permitted: % may not capture evidence for %. Evidence is captured by the assigned '
      'operator or lab technician, or by a supervisor (ROLE_AND_APPROVAL_MODEL §2).',
      coalesce(public.current_app_role()::text, 'an unknown role'), ba.title
      using errcode = 'insufficient_privilege';
  end if;

  -- 3 · the requirement must be this activity's.
  select * into req from batch_activity_evidence_req
   where batch_activity_id = p_activity and key = p_requirement_key;
  if not found then
    raise exception 'Activity % has no evidence requirement named %', ba.title, p_requirement_key;
  end if;

  -- 0096 · A LOCKED LAB CHECK TAKES NO PHOTOGRAPH: it opens with its field step.
  if coalesce(ba.responsible_role::text, '') = 'lab_tech' and ba.state in ('LOCKED', 'BLOCKED')
     and not coalesce(ba.is_pre_h0, false) then
    raise exception '%', coalesce(nullif(ba.blocked_reason, ''), ba.title || ' is not open yet.')
      using errcode = 'check_violation';
  end if;

  -- 0100 · past its due time, the after photo (and any Lab photo) waits for an approved late ticket.
  if req.capture_phase = 'after_duration' or coalesce(ba.responsible_role::text, '') = 'lab_tech' then
    if public.late_block_reason(p_activity) is not null then
      raise exception '%', public.late_block_reason(p_activity) using errcode = 'check_violation';
    end if;
  end if;

  -- 0096 · THE AFTER PHOTOGRAPH WAITS FOR THE SOP TIME. It shows the finished work, so it cannot be
  -- taken before the work could have finished.
  if req.capture_phase = 'after_duration' then
    if ba.actual_start is null then
      raise exception '% is taken after the work. Tap Start first.', req.label
        using errcode = 'check_violation';
    end if;
    select * into tg from public.time_gate_status(p_activity);
    if tg.has_gate and not coalesce(tg.time_ok, false) then
      raise exception '% can be taken from % (% to go). The work takes % h from Start.',
        req.label, tg.ready_label, tg.remaining_label,
        trim(trailing '.' from trim(to_char(tg.hours, 'FM999990.99')))
        using errcode = 'check_violation';
    end if;
  end if;

  -- 0081 · a photograph authored as after_start cannot exist before the work began.
  if req.capture_phase = 'after_start' and ba.actual_start is null then
    raise exception '% is taken after the work has started. Tap Start first.', req.label
      using errcode = 'check_violation';
  end if;

  -- 4 · the kind must be one this requirement accepts.
  if not (p_media_kind = any (req.media_kinds)) then
    raise exception '% accepts % — % was offered',
      req.label, array_to_string(req.media_kinds, ' or '), p_media_kind;
  end if;

  -- 2 · the path must name this batch and this activity.
  segs := string_to_array(p_storage_path, '/');
  if array_length(segs, 1) <> 3
     or segs[1] <> ba.master_batch_id::text
     or segs[2] <> p_activity::text then
    raise exception
      'Storage path % does not belong to this activity. Expected %/%/<file>',
      p_storage_path, ba.master_batch_id, p_activity;
  end if;

  -- 1 · THE INTEGRITY RULE. The object has to be there already.
  select o.id, o.metadata into obj
    from storage.objects o
   where o.bucket_id = 'evidence' and o.name = p_storage_path;
  if not found then
    raise exception
      'No object at evidence/% — upload the file first, then bind it. A row claiming a photograph '
      'that is not in storage is a false record.', p_storage_path
      using errcode = 'no_data_found';
  end if;

  -- 0071 · AN EMPTY FILE IS NOT A PHOTOGRAPH.
  --
  -- The object-exists rule above asks whether something is in storage. It does not ask whether that
  -- something is anything. A zero-byte upload was accepted and bound, and satisfied the requirement
  -- outright — satisfied_count 1 of 1 — so an evidence gate could be cleared with nothing at all.
  -- That is not a hypothetical: a camera that fails, a file picker cancelled at the wrong instant
  -- and a dropped connection all produce exactly this, and the operator is then told they are done.
  --
  -- Found by uploading Buffer.alloc(0) as a real signed-in operator.
  if coalesce(nullif(obj.metadata->>'size', '')::bigint, 0) <= 0 then
    raise exception
      'The file uploaded for % is empty (0 bytes). That is usually a photograph that did not '
      'capture, or an upload cut short. Take it again.', req.label
      using errcode = 'check_violation';
  end if;

  -- 6 · already satisfied? Only an explicit retake may proceed.
  select count(*) into live from evidence_media
   where requirement_id = req.id and superseded_by_id is null;

  if p_supersedes is null and live >= req.min_count then
    raise exception
      '% already has % of % item(s). Pass the id of the item this one replaces, with a reason.',
      req.label, live, req.min_count;
  end if;

  if p_supersedes is not null then
    if coalesce(trim(p_supersede_reason), '') = '' then
      raise exception 'Replacing an evidence item needs a reason — the original is kept, not deleted';
    end if;
    if not exists (
      select 1 from evidence_media
       where id = p_supersedes and requirement_id = req.id and superseded_by_id is null
    ) then
      raise exception 'No live evidence item % on %', p_supersedes, req.label;
    end if;
  end if;

  insert into evidence_media (
    master_batch_id, batch_activity_id, requirement_id, requirement_key,
    storage_path, media_kind, mime_type, byte_size, uploaded_by
  ) values (
    ba.master_batch_id, p_activity, req.id, req.key,
    p_storage_path, p_media_kind,
    nullif(obj.metadata->>'mimetype', ''),
    nullif(obj.metadata->>'size', '')::bigint,
    auth.uid()
  )
  returning id into new_id;

  -- §6 — retaking does not delete. The original stays, pointing at what replaced it.
  if p_supersedes is not null then
    update evidence_media
       set superseded_by_id = new_id, superseded_reason = p_supersede_reason
     where id = p_supersedes;
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'bind_evidence', 'evidence_media', new_id::text,
          jsonb_build_object('activity', p_activity, 'requirement', req.key, 'path', p_storage_path),
          case when p_supersedes is null then 'Evidence captured for ' || req.label
               else 'Retake of ' || req.label || ': ' || p_supersede_reason end);

  return query
    select new_id, req.key, r.satisfied_count, r.min_count,
           (select m.uploaded_at from evidence_media m where m.id = new_id)
      from batch_activity_evidence_req r where r.id = req.id;
end;
$function$;

create or replace view public.v_activity_schedule with (security_invoker = on) as
select ba.id as activity_id, ba.master_batch_id, mb.code as batch_code, ba.code as activity_code, ba.title, ba.scope_label,
       ba.responsible_role, ba.state, ba.is_hold,
       ba.planned_start_at, ba.planned_end_at,
       d.shift_hr,
       ba.planned_start_at + make_interval(secs => (coalesce(d.shift_hr, 0) * 3600)::int) as extended_start_at,
       d.extended_end_at, d.due_at, d.open_ticket,
       (d.applies and now() > d.due_at) as late_now,
       ba.actual_start, ba.actual_end,
       round(extract(epoch from (ba.actual_end - ba.planned_end_at)) / 60) as variance_vs_plan_min,
       round(extract(epoch from (ba.actual_end - d.extended_end_at)) / 60) as variance_vs_extended_min,
       (select coalesce(sum(er.approved_extension_hr), 0) from extension_request er
         where er.batch_activity_id = ba.id and public.extension_is_effective(er.status)) as own_granted_hr
  from batch_activity ba
  join master_batch mb on mb.id = ba.master_batch_id
  cross join lateral public.activity_due(ba.id) d;
grant select on public.v_activity_schedule to authenticated;

notify pgrst, 'reload schema';
