-- ─────────────────────────────────────────────────────────────────────────────
-- 0101 · CHEAT AUDIT (user, 15 Sep 2026: "they will try to find ways to break this or get around it").
-- Every server function a signed-in user can call was listed; these wrote data without checking the caller's
-- role, and now do: task assignment and planned times, movements, monthly schedule, vessel and machine
-- records (admin / manager, supervisor where it is field work), initial material data and lab test requests
-- (admin / Lab), ticket expiry (admin / GM). A late ticket is raised only by the role that does that task.
-- The same photo file (content hash) can no longer be bound as evidence twice.
-- Generated by build_0101.py. Rollback: run pre_0101__functions.sql.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.assign_activity(p_activity uuid, p_person uuid, p_reason text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare ba batch_activity; b master_batch; prev uuid;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'assign a task');
  select * into ba from batch_activity where id = p_activity;
  select * into b from master_batch where id = ba.master_batch_id;

  if b.status = 'active' and coalesce(p_reason,'') = '' then
    raise exception 'A forced assignment on a running batch needs a reason';
  end if;

  prev := ba.assigned_person_id;
  update batch_activity
     set assigned_person_id = p_person, assignment_reason = p_reason
   where id = p_activity;

  -- Notify both sides of the change, not just the new assignee.
  insert into notification (master_batch_id, batch_activity_id, to_person_id, to_role, kind, message, reason, sent_by)
  select ba.master_batch_id, p_activity, p_person, ba.responsible_role, 'assignment',
         ba.title || ' — ' || ba.scope_label || ' assigned to you', p_reason, auth.uid();

  if prev is not null and prev <> p_person then
    insert into notification (master_batch_id, batch_activity_id, to_person_id, to_role, kind, message, reason, sent_by)
    values (ba.master_batch_id, p_activity, prev, ba.responsible_role, 'assignment',
            ba.title || ' — ' || ba.scope_label || ' reassigned away from you', p_reason, auth.uid());
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'assign_activity', 'batch_activity', p_activity::text,
          jsonb_build_object('person', p_person), p_reason);
end;
$function$;

CREATE OR REPLACE FUNCTION public.clear_planned_time(p_activity uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  b master_batch;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'change a planned time');
  select mb.* into b from master_batch mb
    join batch_activity ba on ba.master_batch_id = mb.id
   where ba.id = p_activity;
  if not found then raise exception 'No such activity'; end if;

  -- The same refusal `set_activity_plan` makes, stated the same way.
  if b.status <> 'draft' then
    raise exception
      'The baseline is frozen - % is %. Change goes through a deviation or an override.',
      b.code, b.status;
  end if;

  update batch_activity set planned_time = null where id = p_activity;
  -- `trg_replan_hours` fires on planned_time and puts the activity back on the standard hour.

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'clear_planned_time', 'batch_activity',
          p_activity::text, 'Returned to the process standard hour');
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_individual_batches(p_batch uuid, p_numbers text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  b     master_batch;
  parts text[];
  n     text;
  i     int := 0;
  made  int := 0;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'change batch movements');
  select * into b from master_batch where id = p_batch;
  if not found then raise exception 'No such batch'; end if;
  if b.status <> 'draft' then
    raise exception
      'The baseline is frozen - % is %. The batches it covers cannot change now.', b.code, b.status;
  end if;

  -- Split on comma, slash or whitespace: the records use all three.
  parts := regexp_split_to_array(btrim(p_numbers), '[[:space:],/]+');

  delete from individual_batch where master_batch_id = p_batch;

  foreach n in array parts loop
    n := btrim(n);
    continue when n = '';
    i := i + 1;
    insert into individual_batch (master_batch_id, batch_no, seq) values (p_batch, n, i);
    made := made + 1;
  end loop;

  if made = 0 then
    raise exception 'No batch numbers found in "%". Write them as the factory does: 366,367,368',
      p_numbers using errcode = 'invalid_parameter_value';
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'set_individual_batches', 'master_batch',
          p_batch::text, format('%s covers %s', b.code, p_numbers));
  return made;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_movement_vessel(p_batch uuid, p_movement text, p_location uuid, p_individual uuid DEFAULT NULL::uuid, p_planned_at timestamp with time zone DEFAULT NULL::timestamp with time zone, p_note text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  t      movement_template;
  loc    location;
  b      master_batch;
  clash  record;
  prev   uuid;
  new_id uuid;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'change batch movements');
  select * into t from movement_template where code = p_movement;
  if not found then raise exception 'Unknown movement "%"', p_movement; end if;

  select * into b from master_batch where id = p_batch;
  if not found then raise exception 'No such batch'; end if;

  if t.is_per_individual_batch and p_individual is null then
    raise exception '% is chosen for each individual batch, so one must be named.', t.label
      using errcode = 'invalid_parameter_value';
  end if;
  if not t.is_per_individual_batch and p_individual is not null then
    raise exception '% is made by the whole master batch together.', t.label
      using errcode = 'invalid_parameter_value';
  end if;

  select * into loc from location where id = p_location;
  if not found then raise exception 'No such location'; end if;
  if t.vessel_kind is not null and loc.kind <> t.vessel_kind then
    raise exception '% needs a % - % is a %.', t.label, t.vessel_kind, loc.label, loc.kind
      using errcode = 'invalid_parameter_value';
  end if;
  if loc.status is distinct from 'available' then
    raise exception '% is not available (%).', loc.label, loc.status
      using errcode = 'invalid_parameter_value';
  end if;

  -- Held by ANOTHER batch right now. A batch returning to a bunker it used earlier is fine and the
  -- records show it happening, so this only looks at other batches.
  if loc.is_exclusive then
    select mb.code, o.started_at into clash
      from location_occupancy o
      join master_batch mb on mb.id = o.master_batch_id
     where o.location_id = p_location and o.ended_at is null and o.master_batch_id <> p_batch
     limit 1;
    if found then
      raise exception '% is occupied by % since %, and has not been released.',
        loc.label, clash.code, to_char(clash.started_at, 'DD Mon HH24:MI')
        using errcode = 'exclusion_violation';
    end if;
  end if;

  -- Where it comes FROM is the vessel of the previous movement, so the chain draws itself.
  select bm.to_location_id into prev
    from batch_movement bm
    join movement_template mt on mt.code = bm.movement_code
   where bm.master_batch_id = p_batch
     and mt.seq < t.seq
     and (bm.individual_batch_id is null or bm.individual_batch_id = p_individual)
     and bm.to_location_id is not null
   order by mt.seq desc limit 1;

  if p_individual is null then
    delete from batch_movement
     where master_batch_id = p_batch and movement_code = p_movement and individual_batch_id is null;
  else
    delete from batch_movement
     where master_batch_id = p_batch and movement_code = p_movement
       and individual_batch_id = p_individual;
  end if;

  insert into batch_movement
    (master_batch_id, individual_batch_id, movement_code, from_location_id, to_location_id,
     planned_at, note, recorded_by)
  values (p_batch, p_individual, p_movement, prev, p_location, p_planned_at, p_note, auth.uid())
  returning id into new_id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'set_movement_vessel', 'batch_movement',
          new_id::text, jsonb_build_object('movement', p_movement, 'location', loc.code),
          format('%s goes to %s', t.label, loc.label));
  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.import_monthly_schedule(p_schedule_month date, p_source_filename text, p_column_map jsonb, p_rows jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_import_id uuid;
  v_count integer;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'import the monthly schedule');
  if auth.uid() is null or not public.has_role('admin') then
    raise exception 'Monthly schedules may only be imported by an Admin';
  end if;
  if p_schedule_month is null
     or p_schedule_month <> date_trunc('month', p_schedule_month)::date then
    raise exception 'Choose the first day of the schedule month';
  end if;
  if jsonb_typeof(p_rows) is distinct from 'array'
     or jsonb_array_length(p_rows) = 0 then
    raise exception 'The spreadsheet contains no scheduled batch groups';
  end if;
  if jsonb_array_length(p_rows) > 2000 then
    raise exception 'A monthly schedule may contain at most 2,000 groups';
  end if;

  -- Validate before changing the current import, so a bad file cannot erase a good schedule.
  select count(*) into v_count
  from jsonb_to_recordset(p_rows) as r(
    source_row_number integer,
    group_code text,
    group_label text,
    scheduled_start_date date,
    resource_note text,
    raw_row jsonb
  )
  where r.source_row_number is null
     or nullif(trim(r.group_code), '') is null
     or r.scheduled_start_date is null
     or date_trunc('month', r.scheduled_start_date)::date <> p_schedule_month;

  if v_count > 0 then
    raise exception 'Every group needs a batch number and a start date inside the selected month';
  end if;

  update public.monthly_schedule_import
     set is_current = false
   where schedule_month = p_schedule_month and is_current;

  insert into public.monthly_schedule_import
    (schedule_month, source_filename, imported_by, source_rows, column_map)
  values
    (p_schedule_month, trim(p_source_filename), auth.uid(), jsonb_array_length(p_rows),
     coalesce(p_column_map, '{}'::jsonb))
  returning id into v_import_id;

  insert into public.monthly_schedule_group
    (schedule_import_id, source_row_number, group_code, group_label, scheduled_start_date,
     resource_note, raw_row)
  select v_import_id, r.source_row_number, trim(r.group_code), nullif(trim(r.group_label), ''),
         r.scheduled_start_date, nullif(trim(r.resource_note), ''), coalesce(r.raw_row, '{}'::jsonb)
  from jsonb_to_recordset(p_rows) as r(
    source_row_number integer,
    group_code text,
    group_label text,
    scheduled_start_date date,
    resource_note text,
    raw_row jsonb
  );

  insert into public.audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state)
  values (auth.uid(), public.current_app_role(), 'import_monthly_schedule',
          'monthly_schedule_import', v_import_id::text,
          jsonb_build_object('schedule_month', p_schedule_month, 'source_rows', jsonb_array_length(p_rows)));

  return v_import_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.cancel_monthly_schedule_group(p_group uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'cancel a monthly schedule');
  if auth.uid() is null or not public.has_role('admin') then
    raise exception 'Only an Admin can cancel a scheduled group';
  end if;

  update public.monthly_schedule_group
     set status = 'cancelled'
   where id = p_group
     and status = 'scheduled';

  if not found then
    raise exception 'Only a scheduled group can be cancelled';
  end if;

  insert into public.audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state)
  values (auth.uid(), public.current_app_role(), 'cancel_monthly_schedule_group',
          'monthly_schedule_group', p_group::text, jsonb_build_object('status', 'cancelled'));
end;
$function$;

CREATE OR REPLACE FUNCTION public.claim_monthly_schedule_group(p_schedule_group uuid, p_master_batch uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_group public.monthly_schedule_group;
  v_batch public.master_batch;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'claim a monthly schedule');
  if auth.uid() is null or not public.has_role('admin') then
    raise exception 'Only an Admin can create a Master Batch from the monthly schedule';
  end if;

  select * into v_group from public.monthly_schedule_group where id = p_schedule_group for update;
  select * into v_batch from public.master_batch where id = p_master_batch for update;

  if not found or v_group.id is null then
    raise exception 'The scheduled batch group no longer exists';
  end if;
  if v_batch.id is null then
    raise exception 'The Master Batch was not created';
  end if;
  if v_group.status <> 'scheduled' or v_group.master_batch_id is not null then
    raise exception 'This scheduled group has already been used';
  end if;
  if v_batch.status <> 'draft' then
    raise exception 'Only a draft Master Batch can be linked to the schedule';
  end if;
  if v_batch.code <> v_group.group_code or v_batch.start_date <> v_group.scheduled_start_date then
    raise exception 'The Master Batch identity and Day 0 date must match the selected schedule group';
  end if;

  update public.master_batch
     set schedule_group_id = v_group.id,
         config = config || jsonb_build_object('schedule_source', v_group.schedule_import_id::text)
   where id = v_batch.id;

  update public.monthly_schedule_group
     set status = 'instantiated', master_batch_id = v_batch.id,
         instantiated_at = now(), instantiated_by = auth.uid()
   where id = v_group.id;

  insert into public.audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state)
  values (auth.uid(), public.current_app_role(), 'instantiate_scheduled_batch',
          'monthly_schedule_group', v_group.id::text,
          jsonb_build_object('master_batch_id', v_batch.id));
end;
$function$;

CREATE OR REPLACE FUNCTION public.allocate_vessel(p_batch uuid, p_scope text, p_instance_no integer, p_location uuid, p_note text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  m        vessel_scope_map;
  loc      location;
  clash    record;
  new_id   uuid;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'allocate a bunker or tunnel');
  select * into m from vessel_scope_map where scope = p_scope;
  if not found then
    raise exception 'Unknown process scope "%". Vessel scopes come from vessel_scope_map.', p_scope;
  end if;
  if m.location_kind is null then
    raise exception 'Scope "%" is not held in a vessel: %', p_scope, m.unmapped_reason
      using errcode = 'invalid_parameter_value';
  end if;

  select * into loc from location where id = p_location;
  if not found then raise exception 'No such location: %', p_location; end if;

  if loc.kind <> m.location_kind then
    raise exception '% needs a % — % is a %.',
      p_scope, m.location_kind, loc.label, loc.kind
      using errcode = 'invalid_parameter_value';
  end if;

  if loc.status is distinct from 'available' then
    raise exception '% is not available (status: %).', loc.label, loc.status
      using errcode = 'invalid_parameter_value';
  end if;

  -- The double-allocation warning the document asks for, as a refusal. Only meaningful for an
  -- exclusive vessel; the yard is shared on purpose.
  if loc.is_exclusive then
    select mb.code, o.started_at into clash
      from location_occupancy o
      join master_batch mb on mb.id = o.master_batch_id
     where o.location_id = p_location
       and o.ended_at is null
       and o.master_batch_id <> p_batch
     limit 1;
    if found then
      raise exception '% is occupied by % since %, and has not been released.',
        loc.label, clash.code, to_char(clash.started_at, 'DD Mon HH24:MI')
        using errcode = 'exclusion_violation';
    end if;
  end if;

  insert into batch_vessel_allocation
    (master_batch_id, scope, instance_no, location_id, conflict_id, note, allocated_by)
  values (p_batch, p_scope, p_instance_no, p_location, m.conflict_id, p_note, auth.uid())
  on conflict (master_batch_id, scope, instance_no) do update set
    location_id  = excluded.location_id,
    conflict_id  = excluded.conflict_id,
    note         = excluded.note,
    allocated_by = excluded.allocated_by,
    allocated_at = now()
  returning id into new_id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'allocate_vessel', 'batch_vessel_allocation',
          new_id::text,
          jsonb_build_object('scope', p_scope, 'instance_no', p_instance_no, 'location', loc.code),
          format('%s %s of this batch is %s', p_scope, p_instance_no, loc.label));
  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.release_vessel(p_batch uuid, p_scope text, p_instance_no integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  a  batch_vessel_allocation;
  n  int;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager']::app_role[], 'release a bunker or tunnel');
  select * into a from batch_vessel_allocation
   where master_batch_id = p_batch and scope = p_scope and instance_no = p_instance_no;
  if not found then return; end if;

  select count(*) into n from location_occupancy o
   where o.location_id = a.location_id and o.master_batch_id = p_batch;
  if n > 0 then
    raise exception
      'Work has already been recorded in this vessel. Releasing it would rewrite where the '
      'material actually was.'
      using errcode = 'invalid_parameter_value';
  end if;

  delete from batch_vessel_allocation where id = a.id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'release_vessel', 'batch_vessel_allocation',
          a.id::text, format('%s %s released', p_scope, p_instance_no));
end;
$function$;

CREATE OR REPLACE FUNCTION public.record_occupancy(p_activity uuid, p_from timestamp with time zone, p_to timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba     batch_activity;
  l      location;
  new_id uuid;
  clash  record;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','manager','supervisor']::app_role[], 'record occupancy');
  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  if ba.destination_location_id is null then
    raise exception '% has no destination, so there is no vessel to occupy', ba.title;
  end if;
  select * into l from location where id = ba.destination_location_id;

  if p_from is null then
    raise exception
      'A window is required. Deriving one needs the bunker release rule, and that is unanswered — '
      'TBD-29 asks whether the source bunker is released at the start of the unload or at the end of '
      'the reload. Both readings are in resource_policy; neither is enabled.'
      using errcode = 'feature_not_supported';
  end if;

  begin
    insert into location_occupancy (
      location_id, master_batch_id, batch_activity_id, stream, started_at, ended_at, tbd_marker)
    values (l.id, ba.master_batch_id, ba.id, ba.stream, p_from, p_to,
            -- The row carries the question its window depends on, so a later reader knows the
            -- boundary was chosen by a caller and not derived from a stated rule.
            case when p_to is null then 'TBD-29' else null end)
    returning id into new_id;
  exception when exclusion_violation then
    select other.code as batch_code, oc.started_at, oc.ended_at
      into clash
      from location_occupancy oc
      join master_batch other on other.id = oc.master_batch_id
     where oc.location_id = l.id and oc.during && tstzrange(p_from, p_to)
     order by oc.started_at limit 1;
    raise exception
      '% is already held by % %. A bunker serves both streams, so a paddy occupancy blocks a '
      'compost occupancy exactly the same way (RESOURCE_MOVEMENT_MODEL §2).',
      l.label, clash.batch_code,
      case when clash.ended_at is null
           then 'from ' || clash.started_at || ' onwards, still held'
           else 'from ' || clash.started_at || ' to ' || clash.ended_at end
      using errcode = 'exclusion_violation';
  end;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'record_occupancy', 'location_occupancy',
          new_id::text,
          jsonb_build_object('location', l.code, 'from', p_from, 'to', p_to),
          l.label || ' held by ' || ba.title);
  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.open_machine_stint(p_activity uuid, p_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba   batch_activity;
  m    machine;
  at_  timestamptz;
  new_id uuid;
  clash  record;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','supervisor']::app_role[], 'record machine use');
  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  if ba.assigned_machine_id is null then
    raise exception '% has no machine assigned, so there is no stint to open', ba.title;
  end if;
  select * into m from machine where id = ba.assigned_machine_id;

  -- Same rule as a recorded actual: not in the future, not before H0. Consistent with 0016/0017
  -- rather than a second opinion about time.
  at_ := coalesce(p_at, ba.actual_start, now());
  if at_ > now() then
    raise exception 'A stint cannot start in the future (% is ahead of now)', at_
      using errcode = 'invalid_datetime_format';
  end if;

  begin
    insert into machine_usage (machine_id, master_batch_id, batch_activity_id, started_at, opened_by)
    values (m.id, ba.master_batch_id, ba.id, at_, auth.uid())
    returning id into new_id;
  exception when exclusion_violation then
    -- The constraint refused. Name the other commitment so the message is actionable.
    select mu.id, other.title, other.scope_label, mu.started_at, mu.ended_at
      into clash
      from machine_usage mu
      join batch_activity other on other.id = mu.batch_activity_id
     where mu.machine_id = m.id and mu.during && tstzrange(at_, null)
     order by mu.started_at limit 1;
    raise exception
      '% is already committed to % (%) %. One machine cannot be in two places at once.',
      m.code, clash.title, clash.scope_label,
      case when clash.ended_at is null
           then 'from ' || clash.started_at || ' onwards, still open'
           else 'from ' || clash.started_at || ' to ' || clash.ended_at end
      using errcode = 'exclusion_violation';
  end;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'open_machine_stint', 'machine_usage', new_id::text,
          jsonb_build_object('machine', m.code, 'activity', ba.title, 'started_at', at_),
          m.code || ' started on ' || ba.title);
  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.close_machine_stint(p_activity uuid, p_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba  batch_activity;
  at_ timestamptz;
  n   int;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','supervisor']::app_role[], 'record machine use');
  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  at_ := coalesce(p_at, ba.actual_end, now());
  if at_ > now() then
    raise exception 'A stint cannot end in the future (% is ahead of now)', at_
      using errcode = 'invalid_datetime_format';
  end if;

  update machine_usage mu
     set ended_at = at_, closed_by = auth.uid()
   where mu.batch_activity_id = p_activity and mu.ended_at is null
     and at_ >= mu.started_at;
  get diagnostics n = row_count;

  if n > 0 then
    insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
    values (auth.uid(), public.current_app_role(), 'close_machine_stint', 'batch_activity',
            p_activity::text, 'Machine stint closed on ' || ba.title);
  end if;
  return n;
end;
$function$;

CREATE OR REPLACE FUNCTION public.open_prebatch_sample(p_batch uuid, p_checkpoint uuid, p_label text DEFAULT NULL::text, p_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  b      master_batch;
  cp     lab_checkpoint;
  at_    timestamptz;
  new_id uuid;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','lab_tech']::app_role[], 'record initial material data');
  select * into b from master_batch where id = p_batch;
  if not found then raise exception 'No such batch: %', p_batch; end if;

  -- A PREREQUISITE, so it belongs before activation. Once the batch is running, the material it
  -- was made from is no longer a question the batch can answer.
  if b.status <> 'draft' then
    raise exception
      'Batch % is %, so an incoming-material check can no longer be recorded against it. The check '
      'is a prerequisite for activation.', b.code, b.status
      using errcode = 'invalid_parameter_value';
  end if;

  select * into cp from lab_checkpoint where id = p_checkpoint;
  if not found then raise exception 'No such lab checkpoint: %', p_checkpoint; end if;
  if not cp.is_prebatch then
    raise exception
      '% is not a pre-batch checkpoint, so it cannot be sampled before the batch starts. Use '
      'open_lab_sample against a running activity instead.', cp.code
      using errcode = 'invalid_parameter_value';
  end if;

  -- NOT BOUNDED BELOW BY H0, and that is the whole point of this function. The only rule is that a
  -- sample cannot have been collected in the future.
  at_ := coalesce(p_at, now());
  if at_ > now() then
    raise exception 'A sample cannot be collected in the future (% is ahead of now)', at_
      using errcode = 'invalid_datetime_format';
  end if;

  insert into lab_sample (checkpoint_id, master_batch_id, batch_activity_id, sample_ref_label,
                          collected_at, collected_by)
  values (cp.id, b.id, null, p_label, at_, auth.uid())
  returning id into new_id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'open_prebatch_sample', 'lab_sample', new_id::text,
          jsonb_build_object('checkpoint', cp.code, 'map', cp.checkpoint_map, 'batch', b.code,
                             'collected_at', at_),
          'Incoming material sampled at ' || cp.code || ' for ' || b.code || ', before H0');
  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.request_lab_test(p_sample uuid, p_parameter text, p_via text DEFAULT 'user'::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  s      lab_sample;
  cp     lab_checkpoint;
  spec   lab_spec;
  m      text;
  new_id uuid;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','lab_tech']::app_role[], 'request a lab reading');
  select * into s from lab_sample where id = p_sample;
  if not found then raise exception 'No such sample: %', p_sample; end if;
  select * into cp from lab_checkpoint where id = s.checkpoint_id;

  -- ── THE FREEZE ────────────────────────────────────────────────────────────
  -- Looked up only through `spec_checkpoint_code`, which is null wherever TBD-36 leaves the
  -- mapping unstated. So an unmapped checkpoint freezes NO band, `spec_found` stays false, and
  -- every result on it is `no_spec`. That is the honest outcome of an unanswered mapping — not a
  -- reason to guess which spec row was meant.
  if cp.spec_checkpoint_code is not null then
    select * into spec from lab_spec
     where checkpoint_code = cp.spec_checkpoint_code and parameter_code = p_parameter;
  end if;

  -- The method, where one exists for the parameter. `lab_method` is keyed by an upper-case code
  -- and the parameter vocabulary is lower-case; the join is by name, not by a mapping table,
  -- because no source states a parameter → method mapping beyond the shared name.
  select code into m from lab_method where code = upper(p_parameter);

  insert into lab_test (sample_id, parameter_code, method_code, requested_by, requested_via,
                        target_min, target_max, target_unit, spec_source_ref, spec_conflict_id,
                        spec_found)
  values (s.id, p_parameter, m, auth.uid(),
          case when p_via = 'system' then 'system' else 'user' end,
          spec.min_value, spec.max_value, spec.unit, spec.source_ref, spec.conflict_id,
          spec.id is not null)
  on conflict (sample_id, parameter_code) do update set
    -- Re-requesting the same parameter on the same sample must not silently re-freeze a band
    -- against a spec that may have changed. Only the method is refreshed.
    method_code = excluded.method_code
  returning id into new_id;

  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.expire_extensions()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  pol extension_policy;
  n int := 0;
begin
  -- 0101 · who may call this (cheat audit, 15 Sep 2026)
  perform public.assert_role(array['admin','gm']::app_role[], 'expire tickets');
  select * into pol from extension_policy where extension_policy.id;
  -- NULL means a request waits forever, which is the honest default: silently
  -- expiring a request nobody answered would lose the fact that nobody answered.
  if pol.request_expiry_hr is null then return 0; end if;

  update extension_request set status = 'EXPIRED', expired_at = now()
   where status in ('REQUESTED','MANAGER_APPROVED')
     and requested_at < now() - make_interval(secs => (pol.request_expiry_hr * 3600)::int);
  get diagnostics n = row_count;
  return n;
end;
$function$;

CREATE OR REPLACE FUNCTION public.request_extension(p_activity uuid, p_hours numeric, p_reason text, p_evidence uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba  batch_activity;
  b   master_batch;
  pol extension_policy;
  n   int;
  new_id uuid;
begin
  select * into pol from extension_policy where extension_policy.id;
  perform public.assert_role(pol.requester_roles, 'Requesting an extension');
  -- 0101 · a ticket is raised by the role that does the work: supervisor for field tasks, Lab for Lab checks
  perform public.assert_may_execute(p_activity, 'raise a late ticket for this task');

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;
  select * into b from master_batch where id = ba.master_batch_id;

  if b.status <> 'active' then
    raise exception 'Batch % is % — an extension only means something on a running batch', b.code, b.status;
  end if;

  if coalesce(trim(p_reason), '') = '' then
    raise exception 'An extension needs a reason — it is the whole record of why the plan was missed';
  end if;

  if p_hours is null or p_hours <= 0 then
    raise exception 'An extension must ask for a positive number of hours';
  end if;

  if pol.max_requested_hr is not null and p_hours > pol.max_requested_hr then
    raise exception 'An extension may not exceed % hours (extension_policy.max_requested_hr)',
      pol.max_requested_hr;
  end if;

  if pol.evidence_required and p_evidence is null then
    raise exception 'Policy requires evidence with an extension request (extension_policy.evidence_required)';
  end if;

  if not pol.allow_after_completion and ba.actual_end is not null then
    raise exception
      'Activity % has already finished. Extending it now would be rewriting history — record a deviation instead.',
      ba.code;
  end if;

  if not pol.allow_late_request
     and ba.planned_end_at is not null and now() > ba.planned_end_at then
    raise exception 'The planned end of % has passed and late requests are not permitted', ba.code;
  end if;

  if pol.max_total_per_activity is not null then
    select count(*) into n from extension_request where batch_activity_id = p_activity;
    if n >= pol.max_total_per_activity then
      raise exception 'Activity % already carries % extension request(s), the configured maximum',
        ba.code, n;
    end if;
  end if;

  -- The one-open-request rule is the partial unique index; this turns its
  -- constraint error into a sentence a person can act on.
  select count(*) into n from extension_request
   where batch_activity_id = p_activity and status in ('REQUESTED','MANAGER_APPROVED');
  if n >= pol.max_open_per_activity then
    raise exception 'Activity % already has an extension request awaiting a decision', ba.code;
  end if;

  insert into extension_request (
    master_batch_id, batch_activity_id,
    requested_by, requested_by_role, requested_extension_hr, requested_reason, evidence_id,
    planned_end_at_at_request, activity_state_at_request, status, overdue_at_request
  ) values (
    ba.master_batch_id, p_activity,
    auth.uid(), public.current_app_role(), p_hours, trim(p_reason), p_evidence,
    ba.planned_end_at, ba.state::text, 'REQUESTED',
    -- 0088 · was the work already past its stated maximum (plus any approved extra hours)?
    (ba.state = 'IN_PROGRESS' and ba.actual_start is not null and ba.duration_target_max_hr is not null and now() > ba.actual_start + make_interval(secs => ((ba.duration_target_max_hr + coalesce((select sum(er.approved_extension_hr) from extension_request er where er.batch_activity_id = ba.id and extension_is_effective(er.status)), 0)) * 3600)::int))
  ) returning extension_request.id into new_id;

  insert into notification (master_batch_id, batch_activity_id, to_role, kind, message, reason, sent_by)
  values (ba.master_batch_id, p_activity,
          case when pol.admin_decides then 'admin'::app_role else 'manager'::app_role end, 'alert',
          format('Late-task ticket on %s: %s more hours requested', ba.title, p_hours), trim(p_reason), auth.uid());

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'request_extension', 'extension_request', new_id::text,
          jsonb_build_object('hours', p_hours, 'activity', p_activity, 'status', 'REQUESTED'),
          trim(p_reason));

  return new_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.bind_evidence(p_activity uuid, p_requirement_key text, p_storage_path text, p_media_kind text DEFAULT 'photo'::text, p_supersedes uuid DEFAULT NULL::uuid, p_supersede_reason text DEFAULT NULL::text)
 RETURNS TABLE(media_id uuid, requirement_key text, satisfied_count integer, min_count integer, uploaded_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba      batch_activity;
  req     batch_activity_evidence_req;
  obj     record;
  segs    text[];
  new_id  uuid;
  live    int;
  tg      record;
begin
  if auth.uid() is null then
    raise exception 'bind_evidence needs a signed-in user — the uploader is taken from the JWT, never from a parameter'
      using errcode = 'insufficient_privilege';
  end if;

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  -- 5 · entitlement first, so an unauthorised caller learns nothing about the rest.
  if not public.can_capture_for_activity(p_activity) then
    raise exception
      'Not permitted: % may not capture evidence for %. Evidence is captured by the assigned '
      'operator or lab technician, or by a supervisor (ROLE_AND_APPROVAL_MODEL §2).',
      coalesce(public.current_app_role()::text, 'an unknown role'), ba.title
      using errcode = 'insufficient_privilege';
  end if;

  -- 3 · the requirement must be this activity's.
  select * into req from batch_activity_evidence_req
   where batch_activity_id = p_activity and key = p_requirement_key;
  if not found then
    raise exception 'Activity % has no evidence requirement named %', ba.title, p_requirement_key;
  end if;

  -- 0096 · A LOCKED LAB CHECK TAKES NO PHOTOGRAPH: it opens with its field step.
  if coalesce(ba.responsible_role::text, '') = 'lab_tech' and ba.state in ('LOCKED', 'BLOCKED')
     and not coalesce(ba.is_pre_h0, false) then
    raise exception '%', coalesce(nullif(ba.blocked_reason, ''), ba.title || ' is not open yet.')
      using errcode = 'check_violation';
  end if;

  -- 0100 · past its due time, the after photo (and any Lab photo) waits for an approved late ticket.
  if req.capture_phase = 'after_duration' or coalesce(ba.responsible_role::text, '') = 'lab_tech' then
    if public.late_block_reason(p_activity) is not null then
      raise exception '%', public.late_block_reason(p_activity) using errcode = 'check_violation';
    end if;
  end if;

  -- 0096 · THE AFTER PHOTOGRAPH WAITS FOR THE SOP TIME. It shows the finished work, so it cannot be
  -- taken before the work could have finished.
  if req.capture_phase = 'after_duration' then
    if ba.actual_start is null then
      raise exception '% is taken after the work. Tap Start first.', req.label
        using errcode = 'check_violation';
    end if;
    select * into tg from public.time_gate_status(p_activity);
    if tg.has_gate and not coalesce(tg.time_ok, false) then
      raise exception '% can be taken from % (% to go). The work takes % h from Start.',
        req.label, tg.ready_label, tg.remaining_label,
        trim(trailing '.' from trim(to_char(tg.hours, 'FM999990.99')))
        using errcode = 'check_violation';
    end if;
  end if;

  -- 0081 · a photograph authored as after_start cannot exist before the work began.
  if req.capture_phase = 'after_start' and ba.actual_start is null then
    raise exception '% is taken after the work has started. Tap Start first.', req.label
      using errcode = 'check_violation';
  end if;

  -- 4 · the kind must be one this requirement accepts.
  if not (p_media_kind = any (req.media_kinds)) then
    raise exception '% accepts % — % was offered',
      req.label, array_to_string(req.media_kinds, ' or '), p_media_kind;
  end if;

  -- 2 · the path must name this batch and this activity.
  segs := string_to_array(p_storage_path, '/');
  if array_length(segs, 1) <> 3
     or segs[1] <> ba.master_batch_id::text
     or segs[2] <> p_activity::text then
    raise exception
      'Storage path % does not belong to this activity. Expected %/%/<file>',
      p_storage_path, ba.master_batch_id, p_activity;
  end if;

  -- 1 · THE INTEGRITY RULE. The object has to be there already.
  select o.id, o.metadata into obj
    from storage.objects o
   where o.bucket_id = 'evidence' and o.name = p_storage_path;
  if not found then
    raise exception
      'No object at evidence/% — upload the file first, then bind it. A row claiming a photograph '
      'that is not in storage is a false record.', p_storage_path
      using errcode = 'no_data_found';
  end if;

  -- 0101 · ONE PHOTOGRAPH, ONE RECORD. The same file (same content hash) cannot be bound again — not to
  -- another task, another batch, or the same task — so an old photo cannot be reused as new evidence.
  if nullif(obj.metadata->>'eTag', '') is not null and exists (
       select 1 from evidence_media m
         join storage.objects o2 on o2.bucket_id = 'evidence' and o2.name = m.storage_path
        where o2.metadata->>'eTag' = obj.metadata->>'eTag' and o2.name <> p_storage_path) then
    raise exception 'This photo has already been used as evidence. Take a new photo of the work as it is now.'
      using errcode = 'check_violation';
  end if;

  -- 0071 · AN EMPTY FILE IS NOT A PHOTOGRAPH.
  --
  -- The object-exists rule above asks whether something is in storage. It does not ask whether that
  -- something is anything. A zero-byte upload was accepted and bound, and satisfied the requirement
  -- outright — satisfied_count 1 of 1 — so an evidence gate could be cleared with nothing at all.
  -- That is not a hypothetical: a camera that fails, a file picker cancelled at the wrong instant
  -- and a dropped connection all produce exactly this, and the operator is then told they are done.
  --
  -- Found by uploading Buffer.alloc(0) as a real signed-in operator.
  if coalesce(nullif(obj.metadata->>'size', '')::bigint, 0) <= 0 then
    raise exception
      'The file uploaded for % is empty (0 bytes). That is usually a photograph that did not '
      'capture, or an upload cut short. Take it again.', req.label
      using errcode = 'check_violation';
  end if;

  -- 6 · already satisfied? Only an explicit retake may proceed.
  select count(*) into live from evidence_media
   where requirement_id = req.id and superseded_by_id is null;

  if p_supersedes is null and live >= req.min_count then
    raise exception
      '% already has % of % item(s). Pass the id of the item this one replaces, with a reason.',
      req.label, live, req.min_count;
  end if;

  if p_supersedes is not null then
    if coalesce(trim(p_supersede_reason), '') = '' then
      raise exception 'Replacing an evidence item needs a reason — the original is kept, not deleted';
    end if;
    if not exists (
      select 1 from evidence_media
       where id = p_supersedes and requirement_id = req.id and superseded_by_id is null
    ) then
      raise exception 'No live evidence item % on %', p_supersedes, req.label;
    end if;
  end if;

  insert into evidence_media (
    master_batch_id, batch_activity_id, requirement_id, requirement_key,
    storage_path, media_kind, mime_type, byte_size, uploaded_by
  ) values (
    ba.master_batch_id, p_activity, req.id, req.key,
    p_storage_path, p_media_kind,
    nullif(obj.metadata->>'mimetype', ''),
    nullif(obj.metadata->>'size', '')::bigint,
    auth.uid()
  )
  returning id into new_id;

  -- §6 — retaking does not delete. The original stays, pointing at what replaced it.
  if p_supersedes is not null then
    update evidence_media
       set superseded_by_id = new_id, superseded_reason = p_supersede_reason
     where id = p_supersedes;
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'bind_evidence', 'evidence_media', new_id::text,
          jsonb_build_object('activity', p_activity, 'requirement', req.key, 'path', p_storage_path),
          case when p_supersedes is null then 'Evidence captured for ' || req.label
               else 'Retake of ' || req.label || ': ' || p_supersede_reason end);

  return query
    select new_id, req.key, r.satisfied_count, r.min_count,
           (select m.uploaded_at from evidence_media m where m.id = new_id)
      from batch_activity_evidence_req r where r.id = req.id;
end;
$function$;

notify pgrst, 'reload schema';
