-- ─────────────────────────────────────────────────────────────────────────────
-- 0102 · FULL ROLE AUDIT (user, 15 Sep 2026: "check for holes in every user role").
--   CRITICAL · supervisor hold_activity + release_activity completed ANY task (no photo, reading, time, ticket or
--              approval). release now only ends a supervisor hold and returns the task to its work.
--   CRITICAL · supervisor return_activity on a LOCKED/READY task made it executable past its entry rules, and could
--              reopen Lab checks. Now field work that is under way or done only.
--   CRITICAL · supervisor/manager/GM correct_actual could move a recorded Start back and beat the time gate and the
--              late rule. Now Admin only (reason required, audited).
--   HIGH     · supervisor accept_with_deviation / verify_corrective_action waived deviations on their own work. GM only.
--   HIGH     · hold_activity worked on any task in any state (Lab checks, finished work). Open field work only.
--   MEDIUM   · a deactivated account kept its role from its token. The active profile is now the authority.
-- Generated by build_0102.py. Rollback: run pre_0102__functions.sql.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.current_app_role()
 RETURNS app_role
 LANGUAGE sql
 STABLE
AS $function$
  -- 0102 · the ACTIVE profile is the authority. A deactivated account keeps a valid token (and its app_metadata
  -- role) until it expires; it must not keep its powers. A token role that disagrees with the profile gives none.
  select p.role from public.profiles p
   where p.id = auth.uid() and p.is_active
     and (nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' ->> 'app_role', '') is null
          or nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' ->> 'app_role', '')::app_role = p.role)
$function$;

CREATE OR REPLACE FUNCTION public.release_activity(p_activity uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare ba batch_activity; still_open int;
begin
  perform public.assert_role(array['supervisor']::app_role[], 'Releasing an activity');
  if coalesce(trim(p_reason), '') = '' then
    raise exception 'A release needs a reason';
  end if;

  select * into ba from batch_activity where id = p_activity for update;
  if not found then raise exception 'No such activity'; end if;
  -- 0102 · release ends a supervisor HOLD. It completed the task outright, so hold + release finished any task
  -- with no photo, reading, time or approval. Now only a held task can be released, and it returns to its work.
  perform public.assert_may_execute(p_activity, 'release a hold');
  if ba.state <> 'BLOCKED' or coalesce(ba.blocked_reason, '') not like 'Held by supervisor%' then
    raise exception '% is not held by a supervisor, so there is nothing to release.', ba.title
      using errcode = 'check_violation';
  end if;

  -- §3.1 RELEASE requires "all exit-gate conditions satisfied, OR an accept-with-deviation on
  -- each failing one". So: nothing may still be awaiting a verdict.
  select count(*) into still_open
  from v_deviation_open
  where batch_activity_id = p_activity and awaiting_verdict;

  if still_open > 0 then
    raise exception
      'Cannot release — % deviation(s) still awaiting a verdict. Accept or resolve each one first.',
      still_open;
  end if;

  update batch_activity
     set state = case when actual_start is not null then 'IN_PROGRESS'::activity_state else 'LOCKED'::activity_state end,
         blocked_reason = null
   where id = p_activity;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'release_activity', 'batch_activity',
          p_activity::text, p_reason);

  -- Whatever this was holding up is re-evaluated by the gate engine, not by this function.
  perform public.advance_batch(ba.master_batch_id);
end;
$function$;

CREATE OR REPLACE FUNCTION public.hold_activity(p_activity uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform public.assert_role(array['supervisor']::app_role[], 'Holding an activity');
  if coalesce(trim(p_reason), '') = '' then
    raise exception 'A hold needs a reason — the card has to say why on its face';
  end if;

  -- 0102 · a supervisor holds open production work only — not Lab checks, not finished or skipped work
  perform public.assert_may_execute(p_activity, 'hold a task');
  update batch_activity
     set state = 'BLOCKED', blocked_reason = 'Held by supervisor — ' || p_reason
   where id = p_activity and state::text in ('LOCKED', 'READY', 'IN_PROGRESS', 'RETURNED', 'WAITING_TIME');
  if not found then
    raise exception 'Only open work can be held.' using errcode = 'check_violation';
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'hold_activity', 'batch_activity',
          p_activity::text, p_reason);
end;
$function$;

CREATE OR REPLACE FUNCTION public.return_activity(p_activity uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform public.assert_role(array['supervisor']::app_role[], 'Returning an activity');
  if coalesce(trim(p_reason), '') = '' then
    -- §3.1 RETURN requires "reason text + what specifically to redo".
    raise exception 'A return needs a reason saying what specifically to redo';
  end if;

  -- 0102 · RETURNED is executable, so returning a LOCKED or READY task skipped its entry rules; returning Lab work
  -- reopened a GM-decided check. Only field work that is under way or done can be sent back for redoing.
  perform public.assert_may_execute(p_activity, 'return a task');
  update batch_activity
     set state = 'RETURNED', blocked_reason = 'Returned — ' || p_reason
   where id = p_activity and state::text in ('IN_PROGRESS', 'COMPLETED', 'DEVIATION');
  if not found then
    raise exception 'Only work that is under way or finished can be returned for redoing.' using errcode = 'check_violation';
  end if;

  insert into notification (master_batch_id, batch_activity_id, to_role, kind, message,
                            reason, sent_by)
  select ba.master_batch_id, ba.id, ba.responsible_role, 'returned',
         ba.title || ' — ' || ba.scope_label || ' was returned', p_reason, auth.uid()
  from batch_activity ba where ba.id = p_activity;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'return_activity', 'batch_activity',
          p_activity::text, p_reason);
end;
$function$;

CREATE OR REPLACE FUNCTION public.correct_actual(p_activity uuid, p_field text, p_value timestamp with time zone, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba  batch_activity;
  b   master_batch;
  cur timestamptz;
begin
  -- NOT the operator. Correcting the record is a supervisory act, and the person whose work is
  -- late is not the person who should be able to restate when it finished.
  perform public.assert_role(array['admin']::app_role[],
                             'correct a recorded actual');

  if p_field not in ('actual_start', 'actual_end') then
    raise exception 'correct_actual handles actual_start and actual_end, not %', p_field
      using errcode = 'invalid_parameter_value';
  end if;

  if coalesce(length(trim(p_reason)), 0) < 10 then
    raise exception
      'A correction needs a reason of at least ten characters. "typo" does not tell anyone reading '
      'this batch in six months what actually happened.'
      using errcode = 'check_violation';
  end if;

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  select * into b from master_batch where id = ba.master_batch_id;

  if p_value is null then
    raise exception 'A correction must state a value. Clearing an actual is not a correction.'
      using errcode = 'invalid_parameter_value';
  end if;
  if p_value > now() then
    raise exception
      'Cannot correct % to %: that is in the future. An actual is something that has already '
      'happened.', ba.title, p_value
      using errcode = 'invalid_datetime_format';
  end if;
  if b.start_at is not null and p_value < b.start_at then
    raise exception
      'Cannot correct % to %: the batch begins at % and nothing in it happens before that.',
      ba.title, p_value, b.start_at
      using errcode = 'invalid_datetime_format';
  end if;

  cur := case when p_field = 'actual_start' then ba.actual_start else ba.actual_end end;
  if cur is null then
    raise exception
      'There is nothing to correct: % has no % recorded. Record it through the normal execution '
      'path instead.', ba.title, p_field
      using errcode = 'check_violation';
  end if;
  if cur = p_value then
    return;                                    -- idempotent; not a correction.
  end if;

  -- Ordering still has to hold after the correction, or a supervisor can produce an activity that
  -- ended before it began by fixing one half of the pair.
  if p_field = 'actual_start' and ba.actual_end is not null and ba.actual_end < p_value then
    raise exception
      'Cannot move the start of % to %: it is already recorded as ending at %, and work does not '
      'end before it begins. Correct the end first.', ba.title, p_value, ba.actual_end
      using errcode = 'invalid_datetime_format';
  end if;
  if p_field = 'actual_end' and ba.actual_start is not null and p_value < ba.actual_start then
    raise exception
      'Cannot move the end of % to %: it is recorded as starting at %, and work does not end '
      'before it begins.', ba.title, p_value, ba.actual_start
      using errcode = 'invalid_datetime_format';
  end if;

  perform set_config('mushroomos.correction_reason', p_reason, true);

  if p_field = 'actual_start' then
    update batch_activity set actual_start = p_value where id = p_activity;
  else
    update batch_activity set actual_end = p_value where id = p_activity;
  end if;

  -- Cleared immediately. Leaving it set would let any LATER update in the same transaction
  -- overwrite a different actual under a reason written for this one.
  perform set_config('mushroomos.correction_reason', '', true);

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'correct_actual', 'batch_activity',
          p_activity::text, p_field || ': ' || p_reason);
end;
$function$;

CREATE OR REPLACE FUNCTION public.accept_with_deviation(p_deviation uuid, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare d deviation; protected boolean;
begin
  perform public.assert_role(array['gm']::app_role[], 'Accept-with-deviation');

  if coalesce(trim(p_reason), '') = '' then
    raise exception 'Accept-with-deviation needs a reason — it goes on the record permanently';
  end if;

  select * into d from deviation where id = p_deviation;
  if not found then raise exception 'No such deviation: %', p_deviation; end if;
  if d.state <> 'open' then
    raise exception 'Deviation is already %, not open', d.state;
  end if;

  -- A protected gate is the one thing a supervisor cannot wave through. §3.2.
  select coalesce(g.is_protected, false) into protected
  from gate_rule g where g.id = d.gate_rule_id;

  if protected and not public.has_role('gm') then
    raise exception
      'This gate is protected — a supervisor cannot accept it. Escalate it for a GM override.'
      using errcode = 'insufficient_privilege';
  end if;

  update deviation
     set state = 'accepted', decided_at = now(), decided_by = auth.uid(),
         decided_by_role = public.current_app_role(), decision_reason = p_reason
   where id = p_deviation;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'accept_with_deviation', 'deviation',
          p_deviation::text, p_reason);
end;
$function$;

CREATE OR REPLACE FUNCTION public.verify_corrective_action(p_action uuid, p_note text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare dev uuid;
begin
  -- 0102 · resolving a deviation is the GM's decision, not the person who raised or caused it
  perform public.assert_role(array['gm']::app_role[], 'verify a corrective action');
  perform public.assert_role(array['supervisor','gm']::app_role[],
                             'Verifying a corrective action');
  if coalesce(trim(p_note), '') = '' then
    raise exception 'Verifying a corrective action needs a note saying what proved it';
  end if;

  update corrective_action
     set verified_at = now(), verified_by = auth.uid(), verification_note = p_note
   where id = p_action
  returning deviation_id into dev;
  if dev is null then raise exception 'No such corrective action'; end if;

  -- A deviation resolves only when a corrective action has been VERIFIED. Doing the work is not
  -- the same claim as the work having worked.
  update deviation
     set state = 'resolved', decided_at = now(), decided_by = auth.uid(),
         decided_by_role = public.current_app_role(),
         decision_reason = coalesce(nullif(decision_reason, ''), p_note)
   where id = dev and state in ('open', 'accepted', 'escalated');

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
  values (auth.uid(), public.current_app_role(), 'verify_corrective_action',
          'corrective_action', p_action::text, p_note);
end;
$function$;

notify pgrst, 'reload schema';
