-- ─────────────────────────────────────────────────────────────────────────────
-- 0103 · EMPLOYEE MONITORING (user, 15 Sep 2026: "operator and supervisor mean the same thing … this is an
-- employee monitoring tool where we monitor if the employees are doing the work or not").
--   1 · operator = supervisor: an operator account acts as a supervisor everywhere on the server.
--   2 · The before photo must be taken within the grace (30 min) of Start; later, a late ticket is needed.
--       Before, both photos could be taken back to back at the end of the task.
--   3 · v_person_activity: per person, today (factory time) — starts, finishes, work open now, late finishes,
--       before photos taken late, tickets raised / rejected, photos, last action. Admin / GM / manager only.
--   4 · v_override_log: every override and decision (onboarding, DEMO flag, time corrections, ticket decisions,
--       holds, returns, cancellations, deviation and Lab decisions, process changes). Admin / GM / manager only.
--   5 · The audit trail is no longer readable by supervisors (it is the record of their own work).
-- Generated by build_0103.py. Rollback: run pre_0103__functions.sql; drop the two views; restore audit_read.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.current_app_role()
 RETURNS app_role
 LANGUAGE sql
 STABLE
AS $function$
  -- 0102 · the ACTIVE profile is the authority; a token role that disagrees with it gives none.
  -- 0103 · operator and supervisor are the same job (user, 15 Sep 2026): an operator account acts as a supervisor.
  select case when p.role = 'operator' then 'supervisor'::app_role else p.role end
    from public.profiles p
   where p.id = auth.uid() and p.is_active
     and (nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' ->> 'app_role', '') is null
          or nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' ->> 'app_role', '')::app_role = p.role)
$function$;

CREATE OR REPLACE FUNCTION public.bind_evidence(p_activity uuid, p_requirement_key text, p_storage_path text, p_media_kind text DEFAULT 'photo'::text, p_supersedes uuid DEFAULT NULL::uuid, p_supersede_reason text DEFAULT NULL::text)
 RETURNS TABLE(media_id uuid, requirement_key text, satisfied_count integer, min_count integer, uploaded_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba      batch_activity;
  req     batch_activity_evidence_req;
  obj     record;
  segs    text[];
  new_id  uuid;
  live    int;
  tg      record;
begin
  if auth.uid() is null then
    raise exception 'bind_evidence needs a signed-in user — the uploader is taken from the JWT, never from a parameter'
      using errcode = 'insufficient_privilege';
  end if;

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  -- 5 · entitlement first, so an unauthorised caller learns nothing about the rest.
  if not public.can_capture_for_activity(p_activity) then
    raise exception
      'Not permitted: % may not capture evidence for %. Evidence is captured by the assigned '
      'operator or lab technician, or by a supervisor (ROLE_AND_APPROVAL_MODEL §2).',
      coalesce(public.current_app_role()::text, 'an unknown role'), ba.title
      using errcode = 'insufficient_privilege';
  end if;

  -- 3 · the requirement must be this activity's.
  select * into req from batch_activity_evidence_req
   where batch_activity_id = p_activity and key = p_requirement_key;
  if not found then
    raise exception 'Activity % has no evidence requirement named %', ba.title, p_requirement_key;
  end if;

  -- 0096 · A LOCKED LAB CHECK TAKES NO PHOTOGRAPH: it opens with its field step.
  if coalesce(ba.responsible_role::text, '') = 'lab_tech' and ba.state in ('LOCKED', 'BLOCKED')
     and not coalesce(ba.is_pre_h0, false) then
    raise exception '%', coalesce(nullif(ba.blocked_reason, ''), ba.title || ' is not open yet.')
      using errcode = 'check_violation';
  end if;

  -- 0103 · THE BEFORE PHOTO IS TAKEN WHEN THE WORK STARTS. Taken hours later — next to the after photo — it
  -- shows nothing about the start. Past Start + grace it needs an approved late ticket on this task.
  if req.key = 'BEFORE_PHOTO' and coalesce(ba.responsible_role::text, '') <> 'lab_tech'
     and ba.actual_start is not null and not public.batch_clock_waived(ba.master_batch_id)
     and now() > ba.actual_start + make_interval(mins => coalesce((select p.late_grace_min from extension_policy p where p.id), 30))
     and not exists (select 1 from extension_request er
                      where er.batch_activity_id = ba.id and public.extension_is_effective(er.status)) then
    raise exception 'The before photo is taken when the work starts. It is now % min after Start: raise a late ticket to ask Admin.',
      round(extract(epoch from (now() - ba.actual_start)) / 60)
      using errcode = 'check_violation';
  end if;

  -- 0100 · past its due time, the after photo (and any Lab photo) waits for an approved late ticket.
  if req.capture_phase = 'after_duration' or coalesce(ba.responsible_role::text, '') = 'lab_tech' then
    if public.late_block_reason(p_activity) is not null then
      raise exception '%', public.late_block_reason(p_activity) using errcode = 'check_violation';
    end if;
  end if;

  -- 0096 · THE AFTER PHOTOGRAPH WAITS FOR THE SOP TIME. It shows the finished work, so it cannot be
  -- taken before the work could have finished.
  if req.capture_phase = 'after_duration' then
    if ba.actual_start is null then
      raise exception '% is taken after the work. Tap Start first.', req.label
        using errcode = 'check_violation';
    end if;
    select * into tg from public.time_gate_status(p_activity);
    if tg.has_gate and not coalesce(tg.time_ok, false) then
      raise exception '% can be taken from % (% to go). The work takes % h from Start.',
        req.label, tg.ready_label, tg.remaining_label,
        trim(trailing '.' from trim(to_char(tg.hours, 'FM999990.99')))
        using errcode = 'check_violation';
    end if;
  end if;

  -- 0081 · a photograph authored as after_start cannot exist before the work began.
  if req.capture_phase = 'after_start' and ba.actual_start is null then
    raise exception '% is taken after the work has started. Tap Start first.', req.label
      using errcode = 'check_violation';
  end if;

  -- 4 · the kind must be one this requirement accepts.
  if not (p_media_kind = any (req.media_kinds)) then
    raise exception '% accepts % — % was offered',
      req.label, array_to_string(req.media_kinds, ' or '), p_media_kind;
  end if;

  -- 2 · the path must name this batch and this activity.
  segs := string_to_array(p_storage_path, '/');
  if array_length(segs, 1) <> 3
     or segs[1] <> ba.master_batch_id::text
     or segs[2] <> p_activity::text then
    raise exception
      'Storage path % does not belong to this activity. Expected %/%/<file>',
      p_storage_path, ba.master_batch_id, p_activity;
  end if;

  -- 1 · THE INTEGRITY RULE. The object has to be there already.
  select o.id, o.metadata into obj
    from storage.objects o
   where o.bucket_id = 'evidence' and o.name = p_storage_path;
  if not found then
    raise exception
      'No object at evidence/% — upload the file first, then bind it. A row claiming a photograph '
      'that is not in storage is a false record.', p_storage_path
      using errcode = 'no_data_found';
  end if;

  -- 0101 · ONE PHOTOGRAPH, ONE RECORD. The same file (same content hash) cannot be bound again — not to
  -- another task, another batch, or the same task — so an old photo cannot be reused as new evidence.
  if nullif(obj.metadata->>'eTag', '') is not null and exists (
       select 1 from evidence_media m
         join storage.objects o2 on o2.bucket_id = 'evidence' and o2.name = m.storage_path
        where o2.metadata->>'eTag' = obj.metadata->>'eTag' and o2.name <> p_storage_path) then
    raise exception 'This photo has already been used as evidence. Take a new photo of the work as it is now.'
      using errcode = 'check_violation';
  end if;

  -- 0071 · AN EMPTY FILE IS NOT A PHOTOGRAPH.
  --
  -- The object-exists rule above asks whether something is in storage. It does not ask whether that
  -- something is anything. A zero-byte upload was accepted and bound, and satisfied the requirement
  -- outright — satisfied_count 1 of 1 — so an evidence gate could be cleared with nothing at all.
  -- That is not a hypothetical: a camera that fails, a file picker cancelled at the wrong instant
  -- and a dropped connection all produce exactly this, and the operator is then told they are done.
  --
  -- Found by uploading Buffer.alloc(0) as a real signed-in operator.
  if coalesce(nullif(obj.metadata->>'size', '')::bigint, 0) <= 0 then
    raise exception
      'The file uploaded for % is empty (0 bytes). That is usually a photograph that did not '
      'capture, or an upload cut short. Take it again.', req.label
      using errcode = 'check_violation';
  end if;

  -- 6 · already satisfied? Only an explicit retake may proceed.
  select count(*) into live from evidence_media
   where requirement_id = req.id and superseded_by_id is null;

  if p_supersedes is null and live >= req.min_count then
    raise exception
      '% already has % of % item(s). Pass the id of the item this one replaces, with a reason.',
      req.label, live, req.min_count;
  end if;

  if p_supersedes is not null then
    if coalesce(trim(p_supersede_reason), '') = '' then
      raise exception 'Replacing an evidence item needs a reason — the original is kept, not deleted';
    end if;
    if not exists (
      select 1 from evidence_media
       where id = p_supersedes and requirement_id = req.id and superseded_by_id is null
    ) then
      raise exception 'No live evidence item % on %', p_supersedes, req.label;
    end if;
  end if;

  insert into evidence_media (
    master_batch_id, batch_activity_id, requirement_id, requirement_key,
    storage_path, media_kind, mime_type, byte_size, uploaded_by
  ) values (
    ba.master_batch_id, p_activity, req.id, req.key,
    p_storage_path, p_media_kind,
    nullif(obj.metadata->>'mimetype', ''),
    nullif(obj.metadata->>'size', '')::bigint,
    auth.uid()
  )
  returning id into new_id;

  -- §6 — retaking does not delete. The original stays, pointing at what replaced it.
  if p_supersedes is not null then
    update evidence_media
       set superseded_by_id = new_id, superseded_reason = p_supersede_reason
     where id = p_supersedes;
  end if;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'bind_evidence', 'evidence_media', new_id::text,
          jsonb_build_object('activity', p_activity, 'requirement', req.key, 'path', p_storage_path),
          case when p_supersedes is null then 'Evidence captured for ' || req.label
               else 'Retake of ' || req.label || ': ' || p_supersede_reason end);

  return query
    select new_id, req.key, r.satisfied_count, r.min_count,
           (select m.uploaded_at from evidence_media m where m.id = new_id)
      from batch_activity_evidence_req r where r.id = req.id;
end;
$function$;

drop policy if exists audit_read on public.audit_event;
create policy audit_read on public.audit_event for select to authenticated
  using (public.has_role(variadic array['gm', 'manager', 'admin']::app_role[]));

create or replace view public.v_person_activity with (security_invoker = on) as
with tz as (select coalesce((select timezone from factory_clock limit 1), 'Asia/Kolkata') as z),
day as (select (date_trunc('day', now() at time zone tz.z)) at time zone tz.z as d0 from tz)
select p.id as person_id, p.display_name,
       case when p.role = 'operator' then 'supervisor'::app_role else p.role end as role,
       (select count(*) from batch_activity ba, day where ba.started_by = p.id and ba.actual_start >= day.d0) as started_today,
       (select count(*) from batch_activity ba, day where ba.submitted_by = p.id and ba.submitted_at >= day.d0) as finished_today,
       (select count(*) from batch_activity ba join master_batch mb on mb.id = ba.master_batch_id
         where ba.started_by = p.id and ba.state::text in ('IN_PROGRESS', 'RETURNED') and mb.status = 'active') as open_now,
       (select count(*) from batch_activity ba join master_batch mb on mb.id = ba.master_batch_id, day
         where ba.submitted_by = p.id and ba.submitted_at >= day.d0 and not mb.is_demo and not ba.is_hold
           and ba.planned_end_at is not null
           and ba.actual_end > ba.planned_end_at + make_interval(secs => (coalesce((select sum(er.approved_extension_hr) from extension_request er
                 where er.batch_activity_id = ba.id and public.extension_is_effective(er.status)), 0) * 3600)::int)
                 + make_interval(mins => coalesce((select x.late_grace_min from extension_policy x where x.id), 30))) as late_finishes_today,
       (select count(*) from evidence_media m join batch_activity ba on ba.id = m.batch_activity_id, day
         where m.uploaded_by = p.id and m.uploaded_at >= day.d0 and m.requirement_key = 'BEFORE_PHOTO'
           and ba.actual_start is not null and m.uploaded_at > ba.actual_start + interval '30 minutes') as late_before_photos_today,
       (select count(*) from extension_request er, day where er.requested_by = p.id and er.requested_at >= day.d0) as tickets_today,
       (select count(*) from extension_request er, day where er.requested_by = p.id and er.requested_at >= day.d0 and er.status = 'ADMIN_REJECTED') as tickets_rejected_today,
       (select count(*) from evidence_media m, day where m.uploaded_by = p.id and m.uploaded_at >= day.d0) as photos_today,
       (select max(a.occurred_at) from audit_event a where a.actor_id = p.id) as last_action_at,
       (select a.action from audit_event a where a.actor_id = p.id order by a.occurred_at desc limit 1) as last_action
  from profiles p
 where p.is_active
   and public.has_role(variadic array['gm', 'manager', 'admin']::app_role[]);
grant select on public.v_person_activity to authenticated;

create or replace view public.v_override_log with (security_invoker = on) as
select a.id, a.occurred_at, a.actor_id, pr.display_name as actor_name,
       case when a.actor_role::text = 'operator' then 'supervisor' else a.actor_role::text end as actor_role,
       a.action, a.entity_table, a.entity_id, a.reason, a.after_state,
       coalesce(mb.code, mb2.code) as batch_code, ba.title as activity_title, ba.scope_label
  from audit_event a
  left join profiles pr on pr.id = a.actor_id
  left join batch_activity ba on a.entity_table = 'batch_activity' and ba.id::text = a.entity_id
  left join master_batch mb on mb.id = ba.master_batch_id
  left join master_batch mb2 on a.entity_table = 'master_batch' and mb2.id::text = a.entity_id
 where a.action in ('onboard_batch', 'mark_batch_demo', 'correct_actual', 'admin_decide_extension', 'cancel_batch',
                    'hold_activity', 'release_activity', 'return_activity', 'skip_activity', 'accept_with_deviation',
                    'gm_decide_override', 'verify_corrective_action', 'decide_lab_submission', 'set_current_process',
                    'publish_process_definition', 'activate_batch', 'set_batch_start_at', 'assign_activity',
                    'request_extension', 'cancel_extension')
   and public.has_role(variadic array['gm', 'manager', 'admin']::app_role[]);
grant select on public.v_override_log to authenticated;

notify pgrst, 'reload schema';
