-- ─────────────────────────────────────────────────────────────────────────────
-- 0106 · START WAITS FOR THE PLAN; ONBOARDING CLOSES PARALLEL WORK ALREADY PASSED (user, 15 Sep 2026).
-- Found on batch 158,159,160: onboarded "at Turner T2 of pile 4" only, so the T0 passes of piles 1, 2, 3, 5, 6 were
-- open and four were started within 7 seconds; tunnel preparation (no step before it) was started ~6 days early.
--   1 · start_activity refuses a task earlier than its planned start minus extension_policy.early_start_min (30).
--       Not applied to DEMO batches, tasks with no planned time, or when the plan is already behind (planned start
--       passed). start_block_reason(task) gives the screen the same message.
--   2 · onboard_batch: field steps in a position's stream planned to end by the time that position starts are
--       before tracking (the parallel piles / bunkers are at the same stage); live steps whose steps-before are all
--       before tracking are planned too, so every remaining task has a planned time.
--   3 · evaluate_gates: a rest after a step done before tracking is met (it is in the past).
-- Generated by build_0106.py. Rollback: run pre_0106__functions.sql; drop function start_block_reason.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.extension_policy add column if not exists early_start_min integer not null default 30
  check (early_start_min >= 0 and early_start_min <= 720);

create or replace function public.start_block_reason(p_activity uuid)
returns text language plpgsql stable security definer set search_path = public
as $fn$
declare ba batch_activity; v_early int; tz text; v_from timestamptz;
begin
  select * into ba from batch_activity where id = p_activity;
  if not found or ba.planned_start_at is null or ba.before_tracking or ba.is_hold
     or public.batch_clock_waived(ba.master_batch_id)
     or ba.state::text not in ('READY', 'RETURNED') or ba.actual_start is not null then
    return null;
  end if;
  select p.early_start_min into v_early from extension_policy p where p.id;
  v_from := ba.planned_start_at - make_interval(mins => coalesce(v_early, 30));
  if now() >= v_from then return null; end if;
  select fc.timezone into tz from factory_clock fc limit 1;
  tz := coalesce(tz, 'Asia/Kolkata');
  return ba.title || coalesce(' (' || ba.scope_label || ')', '') || ' is planned for '
         || to_char(ba.planned_start_at at time zone tz, 'DD Mon HH24:MI')
         || '. It can be started from ' || to_char(v_from at time zone tz, 'DD Mon HH24:MI') || '.';
end;
$fn$;
revoke all on function public.start_block_reason(uuid) from public, anon;
grant execute on function public.start_block_reason(uuid) to authenticated;

CREATE OR REPLACE FUNCTION public.start_activity(p_activity uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform public.assert_role(array['operator', 'supervisor', 'lab_tech']::app_role[], 'start an activity');

  perform public.assert_may_execute(p_activity, 'start an activity');

  -- 0106 · A TASK IS NOT STARTED BEFORE ITS PLANNED TIME (user: "a Supervisor should not be able to access a step
  -- before its scheduled time, nor work on steps that are supposed to happen later"). Early window from
  -- extension_policy.early_start_min. DEMO batches have no clock.
  if public.start_block_reason(p_activity) is not null then
    raise exception '%', public.start_block_reason(p_activity) using errcode = 'check_violation';
  end if;

  -- 0082 · E-2 · A PASSIVE HOLD IS NOT STARTED BY A PERSON. It begins when the step before it
  -- finishes, and a person confirms it when its condition is met. A 'start' tapped on a hold would put
  -- a human start event on the record for something nobody did.
  if exists (select 1 from batch_activity where id = p_activity and is_hold) then
    raise exception '% is a passive hold: nobody starts it. It begins when the step before it finishes; confirm it when its condition is met.',
      (select title from batch_activity where id = p_activity)
      using errcode = 'check_violation';
  end if;
  -- 0071 · WHAT HAPPENED, AND WHY THIS IS NOT A COSMETIC CHANGE.
  --
  -- The update below has always been guarded by `state in ('READY','RETURNED')`, so a LOCKED
  -- activity was never started and the gate always held. But the audit insert that followed ran
  -- unconditionally, and the function returned void either way. Two things came of that:
  --
  --   · Starting a LOCKED activity over HTTP answered 204 — success — while the row stayed LOCKED.
  --     A refusal that reports success is worse than a refusal, because the caller believes it.
  --   · Five duplicate taps wrote five 'Work started' rows for one start. The trail then reads as
  --     though the work began five times. This product exists to answer "what did happen"; a trail
  --     that says something happened five times when it happened once is a defect in the answer.
  --
  -- So the audit row now follows the update instead of accompanying it, and a genuine refusal says
  -- why — using the reason the engine already computed, rather than inventing a second opinion.
  declare
    touched int;
    st      text;
    why     text;
    ttl     text;
    missing text;
  begin
    -- 0081 · THE BEFORE PHOTOGRAPH COMES BEFORE THE WORK.
    -- A requirement authored as before_start shows the material as it was. Taken after the start it
    -- would show something else, so an open task does not start without it.
    select string_agg(r.label, ', ' order by r.ordering) into missing
      from batch_activity_evidence_req r
      join batch_activity ba on ba.id = r.batch_activity_id
     where r.batch_activity_id = p_activity
       and ba.state in ('READY','RETURNED')
       and r.capture_phase = 'before_start'
       and r.gates_submission
       and r.satisfied_count < r.min_count;
    if missing is not null then
      raise exception '% cannot start yet: take % first. It records the material before the work begins.',
        (select title from batch_activity where id = p_activity), missing
        using errcode = 'check_violation';
    end if;

    update batch_activity
       set state = 'IN_PROGRESS',
           actual_start = coalesce(actual_start, now()),
           started_by = coalesce(started_by, auth.uid()),
           blocked_reason = null
     where id = p_activity and state in ('READY','RETURNED');
    get diagnostics touched = row_count;

    if touched = 0 then
      select ba.state::text, ba.blocked_reason, ba.title
        into st, why, ttl
        from batch_activity ba where ba.id = p_activity;

      -- Not found is not this function's business — 0067 settled that for assert_may_execute, and
      -- the same reasoning holds here.
      if st is null then
        return;
      end if;

      -- Already running. The second, third and fifth tap of a jittery thumb, or a phone retrying
      -- because it never heard the answer. Idempotent, and deliberately silent: nothing changed,
      -- so nothing is recorded.
      if st = 'IN_PROGRESS' then
        return;
      end if;

      raise exception '%', coalesce(
        nullif(why, ''),
        ttl || ' is ' || st || ', so it cannot be started yet. It opens when the conditions on '
             || 'its card are met.')
        using errcode = 'check_violation';
    end if;

    insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, reason)
    values (auth.uid(), public.current_app_role(), 'start_activity', 'batch_activity',
            p_activity::text, 'Work started');

    -- 0096 · a Lab check that goes "with" this step opens now that the step has started.
    perform public.advance_batch((select master_batch_id from batch_activity where id = p_activity));
  end;
end;
$function$;

CREATE OR REPLACE FUNCTION public.onboard_batch(p_batch uuid, p_h0 timestamp with time zone DEFAULT NULL::timestamp with time zone, p_positions uuid[] DEFAULT '{}'::uuid[], p_completed_streams text[] DEFAULT '{}'::text[], p_note text DEFAULT NULL::text)
 RETURNS TABLE(before_tracking_count integer, position_count integer, open_count integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  b          master_batch;
  v_pos      uuid[] := coalesce(p_positions, '{}');
  v_done     text[] := coalesce(p_completed_streams, '{}');
  v_seed     uuid[];
  v_before   uuid[] := '{}';
  v_frontier uuid[];
  v_next     uuid[];
  bad        text;
  v_now      timestamptz := now();
  n_pass     int;
begin
  perform public.assert_role(array['admin']::app_role[], 'onboard a running batch');

  select * into b from master_batch where id = p_batch for update;
  if not found then raise exception 'No such batch: %', p_batch; end if;
  if b.status <> 'draft' then
    raise exception 'Batch % is %; only a batch still being set up can be onboarded.', b.code, b.status
      using errcode = 'check_violation';
  end if;
  -- 0091 · the original physical start is NOT required to begin tracking (baseline §2).
  if p_h0 is not null and p_h0 > now() then
    raise exception 'The actual H0 of a running batch cannot be in the future (% is ahead of now).', p_h0
      using errcode = 'check_violation';
  end if;
  if cardinality(v_pos) = 0 and cardinality(v_done) = 0 then
    raise exception 'Give the current position of at least one stream.' using errcode = 'check_violation';
  end if;

  select string_agg(p::text, ', ') into bad
    from unnest(v_pos) p
   where not exists (select 1 from batch_activity ba
                      where ba.id = p and ba.master_batch_id = p_batch
                        and coalesce(ba.responsible_role::text, '') <> 'lab_tech');
  if bad is not null then
    raise exception 'These positions are not production activities of batch %: %', b.code, bad
      using errcode = 'check_violation';
  end if;

  select string_agg(distinct ba.stream::text, ', ') into bad
    from batch_activity ba
   where ba.id = any(v_pos) and ba.stream::text = any(v_done);
  if bad is not null then
    raise exception 'Stream % is given both a current activity and "completed". Choose one.', bad
      using errcode = 'check_violation';
  end if;

  -- H0 first, so every planned instant is repointed from the actual start. Without an actual H0 the
  -- draft's default instant is removed rather than kept as if it were known, and nothing is planned
  -- against it; live tracking starts at activation.
  if p_h0 is not null then
    perform public.set_batch_start_at(p_batch, p_h0);
  else
    update master_batch set start_at = null where id = p_batch;
    perform public.repoint_batch_activities(p_batch);
  end if;

  -- Streams completed before tracking: all of their production work.
  select coalesce(array_agg(ba.id), '{}') into v_seed
    from batch_activity ba
   where ba.master_batch_id = p_batch and ba.stream::text = any(v_done)
     and coalesce(ba.responsible_role::text, '') <> 'lab_tech';
  v_before := v_seed;

  -- Everything each position and each completed step depends on, transitively, from the process's own
  -- PREDECESSOR rules. Nothing is inferred beyond the dependencies the process states.
  v_frontier := v_pos || v_seed;
  loop
    select coalesce(array_agg(distinct pred.id), '{}') into v_next
      from batch_activity cur
      join gate_rule g
        on g.process_activity_id = cur.process_activity_id
       and g.phase = 'entry' and g.kind = 'PREDECESSOR' and g.is_enabled
      join batch_activity pred
        on pred.master_batch_id = cur.master_batch_id
       and pred.code in (select jsonb_array_elements_text(g.config->'activity_codes'))
       and (coalesce(g.predecessor_binding, 'ALL_INSTANCES') <> 'SAME_SCOPE_INSTANCE'
            or pred.instance_no = cur.instance_no)
     where cur.id = any(v_frontier)
       and not pred.id = any(v_before);
    exit when cardinality(v_next) = 0;
    v_before := v_before || v_next;
    v_frontier := v_next;
  end loop;

  select string_agg(ba.title, ', ') into bad from batch_activity ba where ba.id = any(v_pos) and ba.id = any(v_before);
  if bad is not null then
    raise exception 'These positions come before another position you gave in the same stream: %. Give only the current step of each stream.', bad
      using errcode = 'check_violation';
  end if;

  -- 0095 · A STAND-ALONE STEP ALREADY PASSED is before tracking too: a step with no step before or after
  -- it (e.g. the raw-material weighment) that sits earlier in its stream than the stream's first live step.
  v_before := v_before || coalesce((
    select array_agg(ba.id)
      from batch_activity ba
     where ba.master_batch_id = p_batch
       and coalesce(ba.responsible_role::text, '') <> 'lab_tech'
       and not ba.id = any(v_before) and not ba.id = any(v_pos)
       and not exists (select 1 from gate_rule g
                        where g.process_activity_id = ba.process_activity_id
                          and g.phase = 'entry' and g.kind = 'PREDECESSOR' and g.is_enabled)
       and not exists (select 1 from gate_rule g
                         join batch_activity o on o.process_activity_id = g.process_activity_id
                                              and o.master_batch_id = ba.master_batch_id
                        where g.kind = 'PREDECESSOR' and g.config->'activity_codes' ? ba.code)
       and exists (select 1 from batch_activity x
                    where x.master_batch_id = ba.master_batch_id and x.stream = ba.stream and x.id = any(v_before))
       and ba.seq < coalesce((select min(y.seq) from batch_activity y
                               where y.master_batch_id = ba.master_batch_id and y.stream = ba.stream
                                 and coalesce(y.responsible_role::text, '') <> 'lab_tech'
                                 and y.id <> ba.id and not y.id = any(v_before)), 2147483647)), '{}');

  -- 0106 · PARALLEL WORK ALREADY PASSED. "At Turner T2 of pile 4" means the other piles are at the same stage: their
  -- earlier passes are done. A field step in the same stream as a position, planned to END no later than the
  -- earliest position of that stream STARTS, is before tracking too (unless it is itself a position).
  v_before := v_before || coalesce((
    select array_agg(ba.id)
      from batch_activity ba
     where ba.master_batch_id = p_batch
       and coalesce(ba.responsible_role::text, '') <> 'lab_tech'
       and not ba.id = any(v_before) and not ba.id = any(v_pos)
       and ba.baseline_end_hour is not null
       and ba.baseline_end_hour <= (select min(p.baseline_start_hour) from batch_activity p
                                     where p.id = any(v_pos) and p.stream = ba.stream)), '{}');

  -- Lab checkpoints of work that happened before tracking are before tracking. A GATE checkpoint that
  -- guards a position is too: the factory is already past it. A RECORD / DECISION checkpoint of a
  -- position stays live, because that reading may still be due.
  v_before := v_before || coalesce((
    select array_agg(distinct lba.id)
      from batch_activity lba
      join lab_checkpoint_activity lca on lca.process_activity_id = lba.process_activity_id
      join lab_checkpoint lc on lc.code = lca.checkpoint_code and lc.checkpoint_map = lca.checkpoint_map
     where lba.master_batch_id = p_batch
       and (lca.gates_activity_code in (select ba.code from batch_activity ba where ba.id = any(v_before))
            or (lc.kind = 'GATE'
                and lca.gates_activity_code in (select ba.code from batch_activity ba where ba.id = any(v_pos))))
       and not lba.id = any(v_before)), '{}');

  update batch_activity
     set state = 'SKIPPED',
         before_tracking = true,
         skip_reason = 'Before MushroomOS tracking — batch onboarded '
                       || coalesce('with actual H0 ' || to_char(p_h0 at time zone 'Asia/Kolkata', 'DD Mon YYYY HH24:MI'),
                                   'without a recorded H0'),
         skipped_at = now(),
         blocked_reason = null
   where id = any(v_before);

  update batch_activity
     set state = 'READY',
         onboarded_position = true,
         blocked_reason = null
   where id = any(v_pos);

  -- 0095 · THE PLAN COUNTS FROM WHERE THE BATCH IS, NOW (user, 15 Sep 2026).
  -- A running batch has no usable H0 to plan from. Each current position is planned to start at the
  -- moment of onboarding; everything after it follows at the process's own hour offsets. Where streams
  -- meet, the stream that will be ready LATER sets the time. A stream that is not started and feeds a
  -- later step (paddy, CM, tunnel preparation) is planned to be ready when that step starts. Lab checks
  -- follow their field step. Work before tracking has no planned time. Nothing is planned for a process
  -- version without hours.
  create temporary table if not exists pg_temp.ob_plan (
    id uuid primary key, s numeric, e numeric, is_lab boolean, before boolean, pos boolean, h0v timestamptz) on commit drop;
  create temporary table if not exists pg_temp.ob_edge (pred uuid, succ uuid) on commit drop;
  delete from pg_temp.ob_plan where true;
  delete from pg_temp.ob_edge where true;

  insert into pg_temp.ob_plan (id, s, e, is_lab, before, pos, h0v)
  select ba.id, ba.baseline_start_hour, coalesce(ba.baseline_end_hour, ba.baseline_start_hour),
         coalesce(ba.responsible_role::text, '') = 'lab_tech', ba.before_tracking, ba.id = any(v_pos),
         case when ba.id = any(v_pos) and ba.baseline_start_hour is not null
              then v_now - make_interval(secs => (ba.baseline_start_hour * 3600)::int) end
    from batch_activity ba where ba.master_batch_id = p_batch;

  insert into pg_temp.ob_edge (pred, succ)
  select pred.id, cur.id
    from batch_activity cur
    join gate_rule g on g.process_activity_id = cur.process_activity_id
                    and g.phase = 'entry' and g.kind = 'PREDECESSOR' and g.is_enabled
    join batch_activity pred
      on pred.master_batch_id = cur.master_batch_id
     and pred.code in (select jsonb_array_elements_text(g.config->'activity_codes'))
     and (coalesce(g.predecessor_binding, 'ALL_INSTANCES') <> 'SAME_SCOPE_INSTANCE' or pred.instance_no = cur.instance_no)
   where cur.master_batch_id = p_batch;

  for n_pass in 1..3 loop
    -- 0106 · the frontier: a live step whose every step-before is before tracking (e.g. pile 1 T3 when pile 1 T2 is
    -- already done) is planned with the positions of its stream (or of the batch), at its own hour.
    update pg_temp.ob_plan t set h0v = x.m
      from (select e.succ,
                   coalesce((select min(p2.h0v) from pg_temp.ob_plan p2 join batch_activity b2 on b2.id = p2.id
                              join batch_activity b3 on b3.id = e.succ
                             where p2.pos and p2.h0v is not null and b2.stream = b3.stream),
                            (select min(p2.h0v) from pg_temp.ob_plan p2 where p2.pos and p2.h0v is not null)) m
              from pg_temp.ob_edge e join pg_temp.ob_plan p on p.id = e.pred
             group by e.succ having bool_and(p.before)) x
     where t.id = x.succ and t.h0v is null and not t.before and not t.is_lab and not t.pos and t.s is not null
       and x.m is not null;
    -- forward: a live step starts after its latest live predecessor chain (the later stream governs)
    loop
      update pg_temp.ob_plan t set h0v = x.m
        from (select e.succ, max(p.h0v) m from pg_temp.ob_edge e join pg_temp.ob_plan p on p.id = e.pred
               where p.h0v is not null and not p.before group by e.succ) x
       where t.id = x.succ and not t.before and not t.is_lab and not t.pos and t.s is not null
         and (t.h0v is null or t.h0v < x.m);
      exit when not found;
    end loop;
    -- backward: a not-started feeder is ready when the step that uses it starts
    loop
      update pg_temp.ob_plan t set h0v = x.m
        from (select e.pred, min(s.h0v) m from pg_temp.ob_edge e join pg_temp.ob_plan s on s.id = e.succ
               where s.h0v is not null group by e.pred) x
       where t.id = x.pred and t.h0v is null and not t.before and not t.is_lab and t.s is not null;
      exit when not found;
    end loop;
  end loop;

  -- a stand-alone live step (nothing before or after it) is planned with the start of its own stream
  update pg_temp.ob_plan t set h0v = x.m
    from (select ba.id, (select min(p2.h0v) from pg_temp.ob_plan p2 join batch_activity b2 on b2.id = p2.id
                          where b2.master_batch_id = ba.master_batch_id and b2.stream = ba.stream and p2.h0v is not null) m
            from batch_activity ba where ba.master_batch_id = p_batch) x
   where t.id = x.id and t.h0v is null and not t.before and not t.is_lab and t.s is not null and x.m is not null;

  -- Lab checks follow their field step
  update pg_temp.ob_plan t set h0v = f.h0v
    from batch_activity lba
    join lab_checkpoint_activity lca on lca.process_activity_id = lba.process_activity_id
    join batch_activity fba on fba.master_batch_id = lba.master_batch_id and fba.code = lca.gates_activity_code
    join pg_temp.ob_plan f on f.id = fba.id
   where t.id = lba.id and t.is_lab and not t.before and t.s is not null and f.h0v is not null;

  update batch_activity ba
     set planned_start_at = case when p.before or p.h0v is null then null
                                 else p.h0v + make_interval(secs => (p.s * 3600)::int) end,
         planned_end_at   = case when p.before or p.h0v is null then null
                                 else p.h0v + make_interval(secs => (p.e * 3600)::int) end
    from pg_temp.ob_plan p
   where p.id = ba.id;

  insert into audit_event (actor_id, actor_role, action, entity_table, entity_id, after_state, reason)
  values (auth.uid(), public.current_app_role(), 'onboard_batch', 'master_batch', p_batch::text,
          jsonb_build_object('actual_h0', p_h0,
                             'positions', (select jsonb_agg(jsonb_build_object('code', ba.code, 'stream', ba.stream, 'title', ba.title))
                                             from batch_activity ba where ba.id = any(v_pos)),
                             'completed_streams', to_jsonb(v_done),
                             'plan_counted_from', v_now,
                             'before_tracking_count', cardinality(v_before)),
          coalesce(nullif(trim(p_note), ''), 'Running batch onboarded at its current position'));

  perform public.activate_batch(p_batch);

  return query
    select cardinality(v_before), cardinality(v_pos),
           (select count(*)::int from batch_activity where master_batch_id = p_batch and state = 'READY');
end;
$function$;

CREATE OR REPLACE FUNCTION public.evaluate_gates(p_activity uuid, p_phase text DEFAULT 'entry'::text)
 RETURNS TABLE(rule_id uuid, kind text, binding text, verdict text, reason text, is_enabled boolean, mapping_confidence text, conflict_id text, ordering integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  ba        batch_activity;
  g         record;
  sub       jsonb;
  st        record;
  v_ok      boolean;
  v_vars    jsonb;
  v_verdict text;
  v_sub_ok  boolean;
  v_any_ok  boolean;
  v_fld     batch_activity_value;
  v_out_n   int;
  v_out_lbl text;
  v_actual  numeric;
  v_hours   numeric;
  v_remain  interval;
  v_machine text;
  v_stints_exist boolean;
  v_cp      int;
  v_tg      record;
  v_demo    boolean;
begin
  if p_phase not in ('entry','exit') then
    raise exception 'phase must be entry or exit, got %', p_phase;
  end if;

  select * into ba from batch_activity where id = p_activity;
  if not found then raise exception 'No such activity: %', p_activity; end if;

  -- 0098 · a DEMO / TEST batch has no clock: rests, elapsed times and Day-0 durations are met at once.
  -- Order, photos, readings, Lab approvals and roles are unchanged.
  v_demo := public.batch_clock_waived(ba.master_batch_id);

  select exists (
    select 1 from information_schema.tables
     where table_schema = 'public' and table_name = 'machine_usage'
  ) into v_stints_exist;

  for g in
    select gr.* from gate_rule gr
    where gr.process_activity_id = ba.process_activity_id
      and gr.phase = p_phase
    order by gr.ordering, gr.id
  loop
    v_vars := jsonb_build_object('scope_label', ba.scope_label);
    v_verdict := null;
    v_ok := null;

    if not g.is_enabled then
      v_verdict := 'skipped';

    elsif g.kind in ('FIELD_IN_RANGE','SENSOR_THRESHOLD')
          and g.mapping_confidence not in ('dictated','sop_direct') then
      v_verdict := 'skipped';

    elsif g.kind = 'PREDECESSOR' then
      select * into st from gate_predecessor_status(
        ba.master_batch_id, ba.instance_no, g.config->'activity_codes', g.predecessor_binding);
      v_ok := st.ok;
      -- 0096 · "WITH X": a Lab check opens when its field step has STARTED, not when it has finished.
      if coalesce(g.config->>'when', '') = 'started' then
        select coalesce(bool_and(x.actual_start is not null
                                 or x.state in ('IN_PROGRESS','COMPLETED','SKIPPED','DEVIATION')), true)
          into v_ok
          from batch_activity x
         where x.master_batch_id = ba.master_batch_id
           and x.code in (select jsonb_array_elements_text(g.config->'activity_codes'))
           and (coalesce(g.predecessor_binding, 'ALL_INSTANCES') <> 'SAME_SCOPE_INSTANCE'
                or x.instance_no = ba.instance_no);
      end if;
      -- 0051 · A rest measured from the PREDECESSOR'S ACTUAL END.
      -- The Turner: 8 h after THAT PILE'S OWN T1 end. Not T0 start + 24 h (F10),
      -- and not ELAPSED_TIME, which measures from this activity's own start.
      v_hours := case when v_demo then null else nullif(g.config->>'min_rest_hr', '')::numeric end;

      -- 0062 · The required rest is a property of the RULE, knowable long before anything
      -- finishes. 0051 populated it only inside `if v_ok` — i.e. only once the predecessor was
      -- already complete — so in the ordinary case the card read "rests not recorded h".
      if v_hours is not null then
        v_vars := v_vars || jsonb_build_object(
          -- `FM` strips trailing ZEROS but leaves the decimal POINT, so 8 renders as "8." and the
          -- card reads "rests 8. h". Trim the point too; 7.5 still renders as "7.5".
          'rest_required_hr', trim(trailing '.' from trim(to_char(v_hours, 'FM999990.99'))));

        if not v_ok then
          -- The predecessor has not finished. Say so, instead of a sentence that claims it did.
          v_vars := v_vars || jsonb_build_object(
            'rest_status',
            'That ' || coalesce(st.blocker_title, 'earlier activity') || ' has not finished yet.');

        elsif st.last_actual_end is null and not exists (
                select 1 from batch_activity x
                 where x.master_batch_id = ba.master_batch_id
                   and x.code in (select jsonb_array_elements_text(g.config->'activity_codes'))
                   and (coalesce(g.predecessor_binding, 'ALL_INSTANCES') <> 'SAME_SCOPE_INSTANCE' or x.instance_no = ba.instance_no)
                   and not x.before_tracking) then
          -- 0106 · the step before happened before MushroomOS tracking (onboarded batch): its rest is in the past too.
          v_ok := true;

        elsif st.last_actual_end is null then
          -- Complete, but with no recorded end there is nothing to measure from. Refuse:
          -- treating an unknown end as "long enough ago" is how a rest gets skipped.
          v_ok := false;
          v_vars := v_vars || jsonb_build_object(
            'rest_remaining', 'unknown — no finish time recorded',
            'rest_status',
            'It is marked complete but carries no finish time, so the rest cannot be measured. '
            || 'Ask a supervisor to record the finish.');

        else
          v_remain := greatest(
            st.last_actual_end + make_interval(secs => (v_hours * 3600)::int) - now(),
            interval '0');
          v_ok := (v_remain = interval '0');
          v_vars := v_vars || jsonb_build_object(
            'predecessor_ended_at', to_char(st.last_actual_end, 'DD Mon HH24:MI'),
            'rest_remaining',       to_char(v_remain, 'HH24:MI'),
            'rest_status',
              'It finished at ' || to_char(st.last_actual_end, 'DD Mon HH24:MI')
              || ' — ' || to_char(v_remain, 'HH24:MI') || ' still to go.');
        end if;
      end if;

      v_vars := v_vars
        || jsonb_build_object('predecessor_label', st.blocker_title)
        || jsonb_build_object('stream_label',
             case when st.blocker_stream is null then null
                  else initcap(replace(st.blocker_stream, '_', ' ')) end);

    elsif g.kind in ('BOTH','EITHER_OR') then
      v_any_ok := false;
      v_ok := (g.kind = 'BOTH');
      for sub in select * from jsonb_array_elements(coalesce(g.config->'sub', '[]'::jsonb)) loop
        v_sub_ok := null;
        if sub->>'kind' = 'PREDECESSOR' then
          select * into st from gate_predecessor_status(
            ba.master_batch_id, ba.instance_no, sub->'activity_codes', sub->>'binding');
          v_sub_ok := st.ok;
          if not st.ok then
            v_vars := v_vars
              || jsonb_build_object('predecessor_label', st.blocker_title)
              || jsonb_build_object('stream_label',
                   case when st.blocker_stream is null then null
                        else initcap(replace(st.blocker_stream, '_', ' ')) end);
          end if;
        elsif sub->>'kind' = 'ELAPSED_TIME' then
          v_hours := nullif(sub->>'hours','')::numeric;
          v_sub_ok := v_demo or (ba.actual_start is not null and v_hours is not null
                      and now() >= ba.actual_start + make_interval(secs => (v_hours * 3600)::int));
        else
          v_sub_ok := null;
        end if;

        if g.kind = 'BOTH' then
          if v_sub_ok is false then v_ok := false; end if;
        elsif v_sub_ok is true then
          v_any_ok := true;
        end if;
      end loop;

      if g.kind = 'EITHER_OR' then v_ok := v_any_ok; end if;

    elsif g.kind = 'DAY0_DURATION' then
      if v_demo then
        v_ok := true;
      elsif ba.day0_duration_hr is null then
        v_ok := false;
        v_vars := v_vars || jsonb_build_object(
          'required', 'not set' || coalesce(' (' || ba.tbd_marker || ')', ''),
          'remaining', 'unknown');
      elsif ba.unblocks_at is null then
        v_ok := false;
        v_remain := make_interval(secs => (ba.day0_duration_hr * 3600)::int);
        v_vars := v_vars || jsonb_build_object(
          'required', to_char(v_remain, 'HH24:MI'), 'remaining', 'not started');
      else
        v_ok := now() >= ba.unblocks_at;
        v_remain := greatest(ba.unblocks_at - now(), interval '0');
        v_vars := v_vars || jsonb_build_object(
          'required', to_char(make_interval(secs => (ba.day0_duration_hr * 3600)::int), 'HH24:MI'),
          'remaining', to_char(v_remain, 'HH24:MI'));
      end if;

    elsif g.kind = 'ELAPSED_TIME' then
      v_hours := nullif(g.config->>'hours','')::numeric;
      v_ok := v_demo or (ba.actual_start is not null and v_hours is not null
              and now() >= ba.actual_start + make_interval(secs => (v_hours * 3600)::int));
      v_vars := v_vars || jsonb_build_object(
        'elapsed', case when ba.actual_start is null then 'not started'
                        else round(extract(epoch from (now() - ba.actual_start)) / 3600, 1)::text end);

    elsif g.kind = 'MIN_DURATION' then
      -- 0096 · THE TIME GATE. The work cannot be finished before its SOP time has passed since Start
      -- (a hold: since the step before it finished), and a hold with a temperature trigger needs the
      -- trigger exactly as the SOP states it (OR / AND). time_gate_status carries the rule.
      select * into v_tg from public.time_gate_status(ba.id);
      v_ok := v_tg.ok;
      v_vars := v_vars || jsonb_build_object(
        'time_gate', v_tg.summary, 'ready_at', v_tg.ready_label, 'remaining', v_tg.remaining_label);

    elsif g.kind = 'EVIDENCE_COMPLETE' then
      select count(*)::int, string_agg(r.label, ', ' order by r.ordering)
        into v_out_n, v_out_lbl
      from batch_activity_evidence_req r
      where r.batch_activity_id = ba.id
        and r.gates_submission and r.satisfied_count < r.min_count;
      v_ok := coalesce(v_out_n, 0) = 0;
      v_vars := v_vars || jsonb_build_object(
        'outstanding_count', coalesce(v_out_n, 0)::text, 'outstanding_labels', v_out_lbl);

    elsif g.kind = 'FIELD_IN_RANGE' then
      select * into v_fld from batch_activity_value
       where batch_activity_id = ba.id and field_key = g.config->>'field_key';

      if not found or v_fld.actual_value is null
         or v_fld.actual_value !~ '^-?[0-9]+(\.[0-9]+)?$' then
        v_verdict := 'unevaluable';
        v_vars := v_vars || jsonb_build_object('actual', 'not recorded');
      else
        v_actual := v_fld.actual_value::numeric;
        v_ok := (v_fld.sop_min is null or v_actual >= v_fld.sop_min)
            and (v_fld.sop_max is null or v_actual <= v_fld.sop_max);
        v_vars := v_vars || jsonb_build_object(
          'actual', v_fld.actual_value,
          'min', coalesce(v_fld.sop_min::text, '—'),
          'max', coalesce(v_fld.sop_max::text, '—'));
      end if;

    elsif g.kind = 'MACHINE_STINT_CLOSED' then
      select m.code into v_machine from machine m where m.id = ba.assigned_machine_id;
      v_vars := v_vars || jsonb_build_object('machine_code', v_machine);

      if v_stints_exist then
        execute 'select not exists (select 1 from public.machine_usage mu'
                || ' where mu.batch_activity_id = $1 and mu.ended_at is null)'
          into v_ok using ba.id;
      else
        v_ok := true;
      end if;

    elsif g.kind = 'LAB_APPROVED' then
      -- 0054 · ENTERED IS NOT APPROVED.
      --
      -- Which laboratory activities are bound to hold THIS one, and has the latest decision
      -- on each of them approved it? `lab_checkpoint_activity` carries the pairing, so a
      -- per-bunker gate waits on its own bunker's assay and not on all three.
      --
      -- A REJECTED or ABSENT decision does not open the gate. Neither does a recorded
      -- result: a reading that nobody has approved is a reading, not an approval.
      select count(*)::int,
             count(*) filter (where lab.verdict = 'approved')::int,
             string_agg(distinct lab.checkpoint_code, ', ')
        into v_out_n, v_cp, v_out_lbl
      from (
        select lca.checkpoint_code,
               (select d.verdict from lab_decision d
                 where d.batch_activity_id = lba.id
                 order by d.seq desc limit 1) as verdict
          from batch_activity lba
          join lab_checkpoint_activity lca on lca.process_activity_id = lba.process_activity_id
          join lab_checkpoint cp on cp.checkpoint_map = lca.checkpoint_map
                                and cp.code = lca.checkpoint_code
         where lba.master_batch_id = ba.master_batch_id
           and lca.gates_activity_code = ba.code
           -- 0085 · a checkpoint that happened before MushroomOS tracking cannot be approved now
           and not lba.before_tracking
           and cp.kind = 'GATE'
      ) lab;

      if coalesce(v_out_n, 0) = 0 then
        -- A gate rule with nothing bound to it cannot be evaluated. Passing would silently
        -- open production; failing would lock it for ever with no way to clear it. Say so.
        v_verdict := 'unevaluable';
        v_vars := v_vars || jsonb_build_object(
          'checkpoint', 'no laboratory checkpoint is bound to this activity');
      else
        v_ok := (v_cp = v_out_n);
        v_vars := v_vars || jsonb_build_object(
          'checkpoint', coalesce(v_out_lbl, '?'),
          'approved_count', v_cp::text,
          'required_count', v_out_n::text);
      end if;

    elsif g.kind = 'UNRESOLVED_DEPENDENCY' then
      -- 0082 · E-5 · THE SOURCE DOES NOT DEFINE WHEN THIS MAY START. It stays shut, and says which
      -- registered question it is waiting on. Opening it would invent the rule; so would a GM approval.
      v_ok := false;
      select cr.question into v_out_lbl from conflict_register cr where cr.conflict_id = g.conflict_id;
      v_vars := v_vars || jsonb_build_object(
        'conflict_id', g.conflict_id,
        'question', coalesce(v_out_lbl, 'the dependency is not defined'));

    elsif g.kind = 'GM_APPROVAL' then
      -- ── B6 · CHANGED FROM 0012's `v_ok := false`. ─────────────────────────
      -- The checkpoint number is the RULE's, not this function's: `s04` seeds `'{"checkpoint":3}'`
      -- on TN-LOAD, so which checkpoint gates which activity stays data.
      --
      -- `returned` does NOT open the gate. Only an approval does, and `approved_with_conditions` is
      -- an approval — §5 puts it beside APPROVE on the screen, and the conditions live in the
      -- mandatory reason, which the snapshot preserves.
      --
      -- The LATEST decision governs. A batch approved, returned, then approved again is at its third
      -- decision, and the first two stay on the record.
      v_cp := nullif(g.config->>'checkpoint','')::int;

      if v_cp is null then
        -- An approval rule that does not say WHICH checkpoint cannot be evaluated, and guessing at
        -- one would be inventing the process's own structure.
        v_verdict := 'unevaluable';
        v_vars := v_vars || jsonb_build_object('checkpoint', 'not stated on the rule');
      else
        v_ok := exists (
          select 1 from public.v_checkpoint_status s
           where s.master_batch_id = ba.master_batch_id
             and s.checkpoint_no = v_cp
             and s.latest_verdict in ('approved','approved_with_conditions'));
        v_vars := v_vars || jsonb_build_object('checkpoint', v_cp::text);
      end if;

    else
      v_verdict := 'unevaluable';
    end if;

    if v_verdict is null then
      v_verdict := case when v_ok then 'pass' when v_ok is null then 'unevaluable' else 'fail' end;
    end if;

    return query select
      g.id,
      g.kind,
      g.predecessor_binding,
      v_verdict,
      case when v_verdict = 'fail' then render_gate_reason(g.blocked_reason_template, v_vars) end,
      g.is_enabled,
      g.mapping_confidence,
      g.conflict_id,
      g.ordering;
  end loop;
end;
$function$;

notify pgrst, 'reload schema';
